### ISSUE TITLE
Include Gradle's wrapper in a Gradle project's zip

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/initializr#100]
Using [Gradle's wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html) is considered a best practice. People could be encouraged people to do so by including the wrapper in a Gradle project's zip file. Some of the advantages of doing so are:

 - No need to install Gradle
 - No need to run `gradle wrapper`
 - Increased likelihood that people will use the project's version of Gradle, rather than whatever version that may have installed

**Comment by spencergibb** [comment]
I agree with @wilkinsona, it's the gradle best practice.

**Comment by szpak** [comment]
+1

**Comment by dguggi** [comment]
+1

**Comment by rwinch** [comment]
+1

**Comment by checketts** [comment]
+1

**Comment by grebesche** [comment]
+1

**Comment by westse** [comment]
+1

**Comment by geoand** [comment]
+1

**Comment by snicoll** [comment]
no need for any further +1s, it's implemented now :)

**Comment by geoand** [comment]
Ok, sorry about that! 
I just saw @spencergibb tweet and liked the feature! 
Glad to see it's implemented!
