### ISSUE TITLE
Keep track of the original `ProjectDescription`

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#1005]
When a `ProjectDescription` is post-processed (i.e. customized) some attributes may change due to custom logic. For instance, if you select a Java version that the selected build system does not support yet, a customizer can change the version to prevent the user to generate a broken project with it.

Unfortunately, that change is lost at the moment so if we want to further improve the project (for instance with a note in `HELP.md`) we need the original value to figure out this was changed at some point.

**Comment by snicoll** [comment]
Thinking about this a bit more, I think the only feature we need really is a way to do a deep-copy of a `ProjectDescription`. 

With that feature, `ProjectGenerator` could do a copy and then register something that would keep the copy and the post-processed description in an object with additional features, something like:

```
void ifJavaChanged(BiConsumer<String,String> diff)
```

Customizers could then inject this object and use whatever feature we'd offer there to see if they have something to do.

**Comment by bono007** [comment]
@snicoll is this a good issue to work on?

**Comment by snicoll** [comment]
Same I think. If you want to give it a try, you're more than welcome.

**Comment by bono007** [comment]
@snicoll I would like to work this issue. If you could help me understand something from your last comment that would be helpful.

So I totally get the PG cloning the original PD and registering some object that holds both the original/unmodified/clone PD and the possibly custommized PD. Here is where it gets a little fuzzy for me...

> Customizers could then inject this object and use whatever feature we'd offer there to see if they have something to do.

I am assuming you are referring to customizers that will run after the ProjectDescriptionCustomizers have run, as triggered by the call to `projectAssetGenerator.generate(context);` ? This would allow any arbitrary customizers to aceess the PDs (and delta) and do whatever they need to do w/ it. Then one of the first implementations could be to update the `HELP.md` model as listed in the original description.

Correct? Or way off in left field? 🤡

**Comment by bono007** [comment]
@stephane What are your thoughts on the deep copy portion? 

Here are some options I can think of (the first 2 are not really options) :

1. **(NO)** Java serialization manual or w/ Apache Commons SerializationUtil 
	(-) Intrustive - implement Serializable

1. **(NO)** Java cloneable 
	(-) Intrustive - implement Cloneable
	(-) Actual write the clone method

1. Manual field by field (ala deep copy constructor)
	(+) simple
         (-) maintain copy code
        (-) repeat same code in other objects if we want the same feature there

1. JSON roundtrip 
	(-) initial work to add de/sers - not currently configured to de/ser via Jackson (some of the objects are not conducive to default de/ser)
	(+) would be set to de/ser the graph after this work (if useful somewhere?)
	(+) not maintaining code or bringing in new lib

1. Google Cloning lib https://code.google.com/archive/p/cloning/source/default/source
	(-) new lib/dependency
	(+) works out of the box across any objects
	(+) no code to maintain 
	(+) lightweight lib only brings in objenesis only (apache 2.0 license)

	I have not used it before so I want to run it by you to see if you have had any experience w/ it. 
	Code looks like this and works out of the box...

	```java
	final MutableProjectDescription desc1 = new MutableProjectDescription();
	desc1.setPlatformVersion(Version.safeParse("2.0.0.RELEASE"));
	desc1.setBuildSystem(new GradleBuildSystem());
	desc1.setPackaging(Packaging.forId("jar"));
	desc1.setLanguage(Language.forId("java", "1.8"));
	desc1.setGroupId("com.foo");
	desc1.setArtifactId("bar");
	desc1.setVersion("1.0.0");
	desc1.setName("FooBar");
	desc1.setDescription("Its the FooBar jar");
	desc1.setApplicationName("TestApplication");
	desc1.setPackageName("com.foo");
	desc1.setBaseDirectory(".");
	desc1.addDependency("dep1", Dependency.withCoordinates("com.zaa", "stuff1").build());
	desc1.addDependency("dep2", Dependency.withCoordinates("com.zaa", "stuff2").build());

	final MutableProjectDescription desc2 = new Cloner().deepClone(desc1);
	```

Part of me wants to just go the manual route for simplicity. Part of me wants to try #5 cloning lib route to not have to maintain the deep copy code. 

Any vision/requirements on leveraging this technique for other objects besides ProjectDescription?

**Comment by snicoll** [comment]
> This would allow any arbitrary customizers to aceess the PDs (and delta) and do whatever they need to do w/ it.

Yes. One use case is adding a note that the Java version was downgraded. To be able to do this, we need to know what the original value is and if it was changed.

> Any vision/requirements on leveraging this technique for other objects besides ProjectDescription?

I am not keen to bring an additional library for this use case at the moment, especially considering the code will sit in the lowest level module (`initializr-generator`). I've already implemented something you can reuse [in my first hack](https://github.com/snicoll/initializr/commit/452c639c0b2ed9a6847c1940280f89df3d3c3aa0#diff-db769c2222123a3e053e085ec6be550dR70-R85). I am not saying it's perfect (as I am not really sure how I want to expose it yet) but it's a start.

**Comment by bono007** [comment]
Ok the usage is simpler than I imagined and the copy constructor implementation is simple enough. If we are only using it for ProjectDescription then its definitely not worth bringing in another dep for this use case. 

Your "first hack" looks like its almost there. One question on the `seal`. Why not just always keep the original copy and not require the call to `seal()`? I get that its 2x of the data but it looks like seal will be called by the generator every time anyways. Are there other cases where MJD get instantiated outside of the generate method?

**Comment by snicoll** [comment]
Well https://github.com/spring-io/initializr/issues/1005#issuecomment-533008975 indicates I've changed my mind and that I am not keen to introduce the `seal` part any longer. IMO that brings a lot of complexity, hence the idea of having an object that "just" stores the original and the actual with some useful methods to deal with the diff.

**Comment by bono007** [comment]
Hehe. Bear w/ me while I catch up w/ what you have already pondered. 😺 

So in the case of just storing in separate object what were you thinking in terms of "useful methods to deal w/ the diff"? Something will have to know how to figure out what has changed and feed the `void ifJavaChanged(BiConsumer<String,String> diff)` (possible signature) method. The complexity will live somewhere whether its in MPD or elsewhere.

**Comment by snicoll** [comment]
> Hehe. Bear w/ me while I catch up w/ what you have already pondered. 😺

Of course! It's not like I added a lot of details here either so I am happy to provide the context and I hope you didn't lose too much time on the previous proposal.

>  what were you thinking in terms of "useful methods to deal w/ the diff"?

Nothing, really. Having a concrete opinion about this means I know what we should be doing and I would probably have done it by now. I suggested an option with dedicated methods that I might dislike when I actually see the code. My main point was that if we offer a dedicated object, consumers should not have to check stuff themselves but something on the object should help them with that.

> The complexity will live somewhere whether its in MPD or elsewhere.

Regarding `seal` that's not that part of the complexity I was talking about. The initial plan was to "lock up" the instance and then offer the original description. That seems too invasive for such an object so moving the concept in a separate class makes more sense IMO.

**Comment by bono007** [comment]
> hope you didn't lose too much time on the previous proposal.

Nope. Every little bit that I do right now w/ the project helps me understand it a little more so its all good.

> That seems too invasive for such an object so moving the concept in a separate class makes more sense IMO

I will prototype this approach and see how the dedicated methods turn out.

**Comment by bono007** [comment]
@snicoll I took a stab at what this approach would look like. The naming is off still, I am only hooking into integration test so we can actually see it writing a custom help section for the version. I am surfacing via bean in the project gen context. I have verifed the version change is written out to the generated HELP.md

**Comment by snicoll** [comment]
Closing in favour of PR #1023
