### ISSUE TITLE
Add a "warning" section to HELP.md

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#1006]
There are a number of customizers that could change the project to tune something or to prevent an incompatible combination. Sometimes there are things the UI doesn't convey we'd like to warn the user about.

Having a dedicated model in `HELP.md` would be useful as we could be in control of where to actually display that information rather than having a collection of unrelated sections.

**Comment by bono007** [comment]
@snicoll I would like to take this issue. I am new to contributing to Initializr but am a user (we have a forked customized version) and am excited to get involved.

**Comment by snicoll** [comment]
Thanks for the offer @bono007 and glad you're using the library in a custom instance. I think the main issue is that we need to discuss the phrasing and the structure of the section as well as its location. I don't want you to waste time on a proposal that we'd heavily refactor so I think we need to come up to an agreement as what it would look like concretely. Unfortunately, we don't have a lot of bandwidth at the moment. I've added a label to make that more explicit.
