### ISSUE TITLE
Links in HELP.md should replace {bootVersion} token

### ISSUE THREAD

**Issue by zawataki** [spring-io/initializr#1009]
# Summary
`HELP.md` is generated by [Spring Initializr](https://start.spring.io/) and the file contains `Reference Documentation` section.
But when I select `Spring for Apache Kafka` as Dependencies on Spring Initializr, `{bootVersion}` in the URL on the `Reference Documentation` section is NOT converted to actual boot version.

# Confirmation Steps
1. Select `Spring for Apache Kafka` on Spring Initializr.
2. Click the Generate button.
3. `HELP.md` contained in the generated zip file will be like below.
```markdown
# Getting Started

### Reference Documentation
For further reference, please consider the following sections:

* [Official Apache Maven documentation](https://maven.apache.org/guides/index.html)
* [Spring Boot Maven Plugin Reference Guide](https://docs.spring.io/spring-boot/docs/2.1.8.RELEASE/maven-plugin/)
* [Spring for Apache Kafka](https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-kafka)
```
`{bootVersion}` should be `2.1.8.RELEASE` in this case.

**Comment by snicoll** [comment]
@zawataki oops, thank you very much for reporting it.

**Comment by zawataki** [comment]
@snicoll Thank you for your quick modification!
