### ISSUE TITLE
Gradle warning: can't cd to "./

### ISSUE THREAD

**Issue by yonigibbs** [spring-io/initializr#1014]
I created a new project created using Spring Initializr (choosing Gradle and Kotlin), running on Ubuntu.  Doing a `./gradlew build` works, but outputs this error to the console:

    ./gradlew: 39: cd: can't cd to "./

The code at this line of the `gradlew` script is this:

    cd "$(dirname \"$PRG\")/" >/dev/null

The equivalent line in a new project generated from IntelliJ, without using Spring Initializr, is this:

    cd "`dirname \"$PRG\"`/" >/dev/null

(Note the backticks instead of the `$` sign.)

Replacing the first line above with the second resolved the issue for me.  Maybe the `gradlew` script which Initializr generates should be updated to use the backticks instead of the `$`?

**Comment by wilkinsona** [comment]
Thanks for the report but I cannot reproduce the behaviour that you have described. A freshly-generated project uses backticks on line 39:

```
cd "`dirname \"$PRG\"`/" >/dev/null
```

This also matches the source for the wrapper files:

https://github.com/spring-io/initializr/blob/f3c50329bb84917eeb84ae0b5704353e85834858/initializr-generator-spring/src/main/resources/gradle/5/wrapper/gradlew#L39

Can you please describe the exact steps that you are following to produce the problematic output?

**Comment by yonigibbs** [comment]
Ah, yes, I've just realised that it only happens when creating the project from IntelliJ, not when using the website. I'm using IntelliJ Ultimate 2019.2, and my steps are:

1. File -> New -> Project
1. Choose "Spring Initializr" in left-hand pane. Leave the default Initializr URL which is https://start.spring.io
1. Click Next
1. Change the Type dropdown to Gradle Project
1. Click Next on this screen and all the rest, leaving everything as the default options.

Hope this helps you replicate it.

**Comment by snicoll** [comment]
@yonigibbs thanks for the feedback. I am using IntelliJ IDEA 2019.2 as well and followed the steps you have indicated. Issuing `./gradlew build` doesn't output such warning for me. Line 39 has the following content as well, i.e.

```
cd "`dirname \"$PRG\"`/" >/dev/null
```

I don't really know how to help you any further if we can't replicate it.

**Comment by yonigibbs** [comment]
Cool, no worries. I asked two colleagues to test: one on Mac (he couldn't replicate); one on Kubuntu (he could replicate). Maybe it's something cached somewhere on our Linux machines (we've had older versions of IntelliJ that have been updated by snap, so maybe something like that is at play). Either way, the workaround is easy enough (just manually replace the line), and you're right, if you can't replicate it there's not much you can do, so please feel free to close this issue.  Thanks for looking anyway!

**Comment by snicoll** [comment]
Alright. Thanks for the feedback and please let us know if you find something we should investigate.
