### ISSUE TITLE
Question: is it possible to customize to generate non-JVM-based projects?

### ISSUE THREAD

**Issue by dustinschultz** [spring-io/initializr#1015]
Hi,

I'm wondering how extensible spring-initialzr is outside of JVM-based languages? For instance, is it conceivable that it could be used to build Golang projects or is this entirely not a reality?

Thanks,
Dustin

**Comment by snicoll** [comment]
I guess it is conceivable though some contracts are JVM-dependent (`Language` has a `jvmLevel` attribute that would be meaningless). You'd also get less support from what this project has to offer in terms of assets that have to be generated. 

In the future, please ask question on StackOverflow or join us on Gitter, as mentioned in [the guidelines for contributing](https://github.com/spring-io/initializr/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
