### ISSUE TITLE
Override unwanted settings inherited from spring-boot-starter-parent in Maven projects

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/initializr#1017]
Maven-based projects that use `spring-boot-starter-parent` inherit the `<licenses>` and `<developers>` from the parent. We should override these in the `pom.xml` of generated Maven projects. The following appears to be the minimum effective override:

```xml
<developers>
    <developer />
</developers>
<licences>
    <license />
</licences>
```

**Comment by jaferkhan** [comment]
Hello, @wilkinsona 

I tried making this change across all such files inside the project but when I attempted to build the project, I got 20 test failures. The reason being that the tester class (`ProjectGeneratorTester.java`) generates project(s) such that their `pom.xml` has no `developers` and `licenses` tag, and the test cases that make use of this class expect the changed POMs to be equal to those without the aforementioned tags.

Therefore, I would request you to state your thoughts. Your guidance would prove valuable to me in this regard.

Thanks,
Jafer

**Comment by wilkinsona** [comment]
Thanks for taking a look, @jaferkhan. Unfortunately, I don't have time right now to guide you through the necessary changes.

**Comment by jaferkhan** [comment]
@wilkinsona, thank you for your response.

**Comment by wilkinsona** [comment]
Overriding developers and licenses is insufficient. The complete set of overrides is the following:

```xml
<developers>
    <developer/>
</developers>
<licenses>
    <license/>
</licenses>
<scm>
    <url/>
</scm>
<url/>
```

This assumes that `<description>` has already been set. If it has not, it should also be overridden.

**Comment by snicoll** [comment]
Thanks Andy. So I am feeling ambivalent on this one. What we've done on the Spring Boot side of things make total sense to me and we should let users know about the unwanted side effect of using our parent for their project. On the other hand, this is an issue in Maven in the first place that we're trying to workaround here for everyone.

While it would be the logical thing to do to apply the Spring Boot recommendations, I am actually leaning towards not doing it:

* It is a lot of noise and makes the pom not idiomatic anymore (those overrides are the only way to workaround the Maven issue and it doesn't seem to be wildly used)
* There are a number of projects/users that will not care about that (throwaway project, sample, etc)
* There are a number of reports that user switch the parent to one of their own. If we added those overrides, they would know have to switch the parent and potentially removes those override as the value in their parent is what they want

That last argument is killing it for me. We've always said we'd do our best to generate things in such a way that users don't have to remove stuff they don't want. At the same time, this feels the right thing to do but I am not convinced about the target audience that cares.

Flagging for team attention to see what the rest of the team thinks.

**Comment by snicoll** [comment]
We've discussed this one and we've agreed not to apply those for projects generated by initializr with our conventions. There is some information in the ref guide about it, I've opened https://github.com/spring-projects/spring-boot/issues/19165 to make sure that part is properly described as we already have a link in `HELP.md` to that.

**Comment by wilkinsona** [comment]
#1242 and the [discussion on Twitter](https://twitter.com/graemerocher/status/1401437646438666241) has given me cause to think about this some more. The key argument that led to us declining this, IIRC, was the following:

> There are a number of reports that user switch the parent to one of their own. If we added those overrides, they would know have to switch the parent and potentially removes those override as the value in their parent is what they want

Not having to do too much when you switch to a custom parent is undoubtedly a good thing and this is a point in favour of not having the overrides. However, it comes at a cost and I now think that cost is rather high.

If we generated the overrides and a project switched to a custom parent while leaving the overrides in place, it would have no license declared. IANAL, but my understanding is that a lack of license doesn't really indicate anything. You can't, for example, slap a license of your choosing on someone else's code just because it doesn't have a license. On the other hand, not generating the excludes leaves generated project's inheriting Spring Boot's Apache v2 license which has a high change of being the wrong license. Whether or not that inherited license has any legal weight is an unknown, but it feels to me that no license is much better than a potentially incorrect license. The same goes for the other settings that we'd have to override. They all feel to me like it's better for them to be absent than incorrect.
