### ISSUE TITLE
Minor UI Icon overlapping with text

### ISSUE THREAD

**Issue by tiarebalbi** [spring-io/initializr#1019]
## Summary
On the top-right menu when opening it from Google Chrome you can see the text is overlapping the icon. (On Safari works as expected)

## Screenshot
<img width="470" alt="Screen Shot 2019-10-20 at 7 53 23 AM" src="https://user-images.githubusercontent.com/103419/67155868-cf07d700-f30e-11e9-8d3f-c8c3e35bedb6.png">

## Chrome version:
Version 79.0.3938.0 (Official Build) dev (64-bit)

**Comment by wilkinsona** [comment]
At the time of writing, the latest version of Chrome is 77.0.3865.120. With that build I do not see the problem (on macOS). This looks like a regression in the dev builds to me, as such I'm not sure it's worth spending much, if any, time on it. @tiarebalbi Do you see the same problem with a build from the stable channel?

**Comment by tiarebalbi** [comment]
Closing this issue as I tested with the stable version and I didn't see the problem mentioned above. Thank you.

**Comment by snicoll** [comment]
Thanks for the follow-up @tiarebalbi
