### ISSUE TITLE
Add support for Maven <distributionManagement>

### ISSUE THREAD

**Issue by jpasquali** [spring-io/initializr#1021]
I want to add distributionManagement into my pom.xml in my customized implementation.
The best way I found so far is to provide my own MavenBuildProjectContributor (annotate with @Primary). I would need to overwrite the MavenBuildWriter, but it does not provide a hook to add tags before </project>.

Could the existing MavenBuildWriter be extended to allow custom tags to be added before the end tag?

Assume, same should then be valid for the GradleBuildWriter.

**Comment by snicoll** [comment]
The maven build follows a spec so I'd rather bring those features in the model itself rather than opening up the writer as you suggested. 

Perhaps you could submit a PR that implements `distributionManagement` ?

**Comment by jpasquali** [comment]
Created PR #1035

**Comment by jpasquali** [comment]
Pulled back PR #1035  and created new PR #1038.

**Comment by snicoll** [comment]
Closing in favour of PR #1038
