### ISSUE TITLE
Add support for dependency classifier

### ISSUE THREAD

**Issue by jpasquali** [spring-io/initializr#1022]
We are using the <classifier/> in our dependencies, but they are not supported in Spring inititlizr.
Can this be added to the Dependency class?

**Comment by snicoll** [comment]
Adding `classifer` to `MavenDependency` makes sense to me.

**Comment by wilkinsona** [comment]
This need not be restricted to `MavenDependency` as [Gradle supports classifiers too](https://docs.gradle.org/5.6.3/dsl/org.gradle.api.artifacts.dsl.DependencyHandler.html#N17456).

**Comment by snicoll** [comment]
Thanks Andy. So that needs to move to `Dependency` then, if at all possible with updates for Both the Maven and Gradle writers.

**Comment by jpasquali** [comment]
I worked on this. When I tried to get it running in the UI, I had to change the io.spring.initializr.metadata.Dependency object. Also actually the io.spring.initializr.metadata.support.MetadataBuildItemMapper object. Not 100% sure, how this works, but couldn't this break the other UI's?

**Comment by snicoll** [comment]
Thanks for working on it. It should be an optional feature and nothing should happen if the classifier isn't set so I don't really understand how it would break anyone. It's hard to make an informed opinion without looking at the code.

**Comment by jpasquali** [comment]
Created PR #1049

**Comment by snicoll** [comment]
Closing in favour of PR #1049
