### ISSUE TITLE
Invocation of spring.io site is not specified in "Hosting your own initializr" section of documentation

### ISSUE THREAD

**Issue by amalkurup89** [spring-io/initializr#1024]
When we host our own instance of spring intializr, there is an invocation of below endpoint to fetch boot metadata

https://spring.io/project_metadata/spring-boot

How can we handle this scenario, as this is an external call to public hosted spring.io site?

Can this be detailed out in the documentation

**Comment by snicoll** [comment]
@amalkurup89 thank you for reaching out. This is [already documented](https://docs.spring.io/initializr/docs/0.8.0.RELEASE/reference/html/#create-instance-boot-versions). I am curious why you didn't find it. Anything we could improve in the doc to make that more explicit?

**Comment by snicoll** [comment]
I am going to assume No here.
