### ISSUE TITLE
Add support for Maven profile

### ISSUE THREAD

**Issue by xjs1919** [spring-io/initializr#1025]
hope to add support for profile in pom.xml ,thanks

**Comment by xjs191919** [comment]
https://github.com/spring-io/initializr/pull/1026

**Comment by estigma88** [comment]
@snicoll I am going to work on this if that's ok

**Comment by snicoll** [comment]
@estigma88 sure thing, thank you very much.

**Comment by estigma88** [comment]
@snicoll  #1057 

Still working on unit tests for MavenBuildWriter and check styles. I just want to be sure I am in the right track.

**Comment by snicoll** [comment]
@estigma88 thanks a lot, I'll do my best to review asap. Note however that we're busy on Spring Boot 2.3 and other initiatives at the moment so that might take some time.

**Comment by HzjNeverStop** [comment]
@snicoll  Excuse me, can this PR #1057  be merged? We really wanted this feature

**Comment by snicoll** [comment]
@HzjNeverStop I don't know as I didn't have the time to review it. Supporting profiles can be a bit tricky and invasive with the API we have at the moment so we need to be careful. I am sorry for the lack of follow-up here but the team is very busy on other topics at the moment.

**Comment by snicoll** [comment]
Closing in favour of PR #1057
