### ISSUE TITLE
Produce a multi module maven / gradle project 

### ISSUE THREAD

**Issue by asaikali** [spring-io/initializr#103]
As projects grow they will become multi module projects. I would be awesome to be able to produce such multi module projects right from start.spring.io since that will save the time  to configure a multi module project out of a generated spring boot project.

**Comment by snicoll** [comment]
We need more use cases and more support in Spring Boot itself for a such a thing. Once we have such support in Boot itself, we may reconsider this use case but right now I believe we haven't not enough visibility.

**Comment by asaikali** [comment]
Here is the use case I a looking for. Consider a project with the following requirements. 

* featureA - contains JPA entities / Spring MVC Controllers /  Spring Data Repositories / Spring Services to implement feature A, it does not contain any main methods to launch the app only unit and integration tests that need to hook into the spring boot testing starter 

* featureB - contains JPA entities / Spring MVC Controllers /  Spring Data Repositories / Spring Services to implement feature B, it does not contain any main methods to launch the app only unit and integration tests that need to hook into the spring boot testing starter 

* database - a command line spring boot application that uses flyway to do database migrations, packaging the migration app as a single spring boot jar makes it easier to run it once before apps get deployed and gives a central place to place to manage a shared database 

* webapp - depends on featureA, featureB and contains a class with a main method that launches the webapp as a spring boot web app.
