### ISSUE TITLE
Add Spring Cloud CircuitBreaker to Initializr

### ISSUE THREAD

**Issue by bono007** [spring-io/initializr#1032]
As per https://github.com/spring-cloud/spring-cloud-circuitbreaker/issues/45 - this ticket is a request to add spring-cloud-circuit-breaker into Initializr. 

@snicoll 
@wilkinsona 

Is this something that is ready to be done? I would love to take a stab at it.

**Comment by snicoll** [comment]
@bono007 request for new dependencies on start.spring.io should be created on [the appropriate project](https://github.com/spring-io/start.spring.io). There is already an issue that we need to triage https://github.com/spring-io/start.spring.io/issues/319

We prefer to handle new dependencies ourselves. Thanks anyway.

**Comment by bono007** [comment]
My bad @snicoll - I did not see that related ticket. Thx - sorry for the noise.
