### ISSUE TITLE
Add support for Maven <scm>

### ISSUE THREAD

**Issue by jpasquali** [spring-io/initializr#1037]
I would like to add <scm> support for Maven. It is part of the standard Maven xsd.

**Comment by snicoll** [comment]
It is described here: https://maven.apache.org/pom.html#SCM

Sounds good to me.

**Comment by jpasquali** [comment]
Will create a pull request. However, for #1038 you removed the attribute child.site.url.inherit.append.path (add support for distributionManagement). SCM has similar attributes: child.scm.connection.inherit.append.path is one of the 3. I added them as well, as they are defined in the XSD. Would you also skip them here?

**Comment by snicoll** [comment]
Yes.

**Comment by jpasquali** [comment]
Created PR #1051

**Comment by snicoll** [comment]
Closing in favour of PR #1051
