### ISSUE TITLE
Make the initializer generate App Types

### ISSUE THREAD

**Issue by asaikali** [spring-io/initializr#104]
It would be great if the initializer could be more opinionated about the type of app that it is creating. For example when I visit the initializer I want to create a specific type of application such as.
- a micro service that supports REST end points and uses a database 
- a web application with an HTML5 server generated front end 
- a Single Page Web Application 
- a command line application 

Since there are many technology choices for building these types of applications, it would be great if the spring team had a recommendation for what combination of technologies I probably want to use.  For example for a Single Page Web Application it might automatically select Web / ThymeLeaf / and whatever else makes sense, maybe even a multi module project configured with the a starter index.html and a decent directory structure for a spa application. 

I think it is still worthwhile to keep the form with the giant set of check boxes, but it would be awesome if there was a few single click download a typical starter button. 

Maybe this could be implemented as a YAML file that specifies which other options to turn on and could be selected by a drop down menu, depending on which item is selected it would turn on the other check boxes on the page. 

Also if you want companies to fork and host a version of the initializer that is specific to them having the ability to define pre-canned application types would be a huge help.

**Comment by snicoll** [comment]
I had such an idea itself, I called that _application profile_. I think before moving forward this should go a bit deeper than just a few examples and have something more "concrete".

**Comment by snicoll** [comment]
We'd like to focus on the getting started experience with a minimal structure. Implementing this leads to a project generation phase we don't want to do.
