### ISSUE TITLE
Add support for finalName tag

### ISSUE THREAD

**Issue by jpasquali** [spring-io/initializr#1050]
Would like to add support for finalName tag for Maven projects

**Comment by snicoll** [comment]
@jpasquali thanks for the suggestion. Are you asking if we'd be willing to accept a PR? If so, there is no need to create an issue as only a PR is necessary. If you'd like to check with us, please ask on [our Gitter channel](https://gitter.im/spring-io/initializr) instead.

**Comment by jpasquali** [comment]
Created PR #1052

**Comment by snicoll** [comment]
I assume yes is the answer to my question then, thanks :) 

Closing in favour of PR #1052
