### ISSUE TITLE
Add support for nested annotation

### ISSUE THREAD

**Issue by natrem** [spring-io/initializr#1053]
When an annotation can contain complex information it often uses nested annotations. For instance with openapi :

```java
@OpenAPIDefinition(info = @Info(title = "Sample application")),
public class Application
```
When creating a `MainApplicationTypeCustomizer<TypeDeclaration> ` we can declare such annotation and the import `io.swagger.v3.oas.annotations.OpenAPIDefinition` is resolved.
But import `io.swagger.v3.oas.annotations.info.Info` is not resolved.
I narrowed it down to the [determineImports method](https://github.com/spring-io/initializr/blob/master/initializr-generator/src/main/java/io/spring/initializr/generator/language/java/JavaSourceCodeWriter.java#L282).

I think that maybe the [Annotation Builder](https://github.com/spring-io/initializr/blob/master/initializr-generator/src/main/java/io/spring/initializr/generator/language/Annotation.java#L67) could be extended to add support for nested annotations.

Would you be open to such a change? 
Do you think I miss some complexity (referring to a [comment on the complexity](https://github.com/spring-io/initializr/issues/1002#issuecomment-530863581) you want to avoid)? In particular when checking how annotations are written the size/indentation issue is the same.
Aside from writing a long line what would you consider as a acceptable solution?

**Comment by snicoll** [comment]
@natrem thanks for the suggestion. What you're asking here is support for nested annotations or am I missing something?

**Comment by natrem** [comment]
@snicoll exactly.

**Comment by snicoll** [comment]
@natrem Thanks for the feedback. I've removed the word "import" from the title to make that more clear.

**Comment by snicoll** [comment]
@natrem if you still need this and willing to contribute a PR, that would be most welcome. Thanks!

**Comment by natrem** [comment]
@snicoll I only worked on the Java version so far. I should be able to advance on other languages too.

**Comment by snicoll** [comment]
@natrem sweet. Can you share what you have for Java? The Groovy/Kotlin version should be quite similar so a review of the Java version could be interesting to avoid wasting efforts porting the current design if we have to change it.

**Comment by natrem** [comment]
I did it on work computer and am facing some network limitations at the moment.

**Comment by snicoll** [comment]
@natrem thanks for the offer and sorry for the lack off follow-up on this topic.

The current state is that we don't have the resources at this time to extend the model that we've created for our own purposes. I'd love to have more cycles to offer an extension point using JavaPoet but I haven't got the time to investigate what it would take.

**Comment by natrem** [comment]
@snicoll  then I'll keep things as is for now.

>  I'd love to have more cycles to offer an extension point using JavaPoet 

I could check it out to propose something but that would still require a review (and thus time) to keep the project consistent with your ambitions. Feel free to reach out if you have some available time and would appreciate a proposal.

**Comment by snicoll** [comment]
This issue is now superseded by https://github.com/spring-io/initializr/issues/1424
