### ISSUE TITLE
Creating a basic Kotlin Starter doesn't add the open modifier to the application class

### ISSUE THREAD

**Issue by boothgibson** [spring-io/initializr#1054]
A Kotlin application created using the Spring Boot starter plug-in for eclipse will not start up without modify the application class to be open. I am running the latest versions of the plug-in(s) and latest eclipse. The error you typically see is: 

Exception in thread "main" org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: @Configuration class 'Application' may not be final. Remove the final modifier to continue.

I came across this post that helped me resolve the issue- http://engineering.pivotal.io/post/spring-boot-application-with-kotlin/

**Comment by snicoll** [comment]
@boothgibson thanks for the feedback but that looks like an IDE setup problem to me. it doesn't have to add `open` as the `spring` plugin is applied and [does that already](https://github.com/spring-io/initializr/blob/a3209e18f9e69e9f98f16c1f7f354d7f4a1971fd/initializr-generator-spring/src/main/java/io/spring/initializr/generator/spring/code/kotlin/KotlinMavenBuildCustomizer.java#L48-L49) behind the scenes for `@Configuration`.

I believe the blog post you've referenced is outdated by now but I'd like to get some more feedback from @sdeleuze to confirm there isn't something else we could do.

**Comment by boothgibson** [comment]
Thank you, I thought the plug-in was supposed to do that.

Version Info:

Eclipse IDE for Java Developers
Version: 2019-12 (4.14.0)
Build id: 20191212-1212
OS: Windows 10, v.10.0, x86_64 / win32
Java version: 13.0.1

Kotlin Plugin for Eclipse 0.8.19
Spring Tools 3 (Standalone Edition) 39.11.RELEASE
Spring Tools 3 Add-On for Spring Tools 4 3.9.11.RELEASE
Spring Tools 4 - for Spring Boot (aka Sprint Tool Suite 4) 4.5.0.RELEASE


File -> New -> Spring Start Project..

Type: Maven (also tried Gradle)

Java Version: 13
Packaging: Jar

Language: Kotlin

Spring Boot Version: 2.2.2

No other dependencies selected.


Full Url:
https://start.spring.io/starter.zip?name=application&groupId=com.demo&artifactId=application&version=0.0.1-SNAPSHOT&description=Demo+project+for+Spring+Boot&packageName=com.demo&type=maven-project&packaging=jar&javaVersion=13&language=kotlin&bootVersion=2.2.2.RELEASE

I made sure Windows -> Preferences -> Kotlin -> Compiler -> Compiler
Plugins were checked.

But when I go to run it as a Spring Boot or Kotlin Application, I get the
following error:

org.springframework.beans.factory.parsing.BeanDefinitionParsingException:
Configuration problem: @Configuration class 'Application' may not be final.
Remove the final modifier to continue.
Offending resource: com.demo.Application

**Comment by snicoll** [comment]
Thanks for the feedback. I can see in the generated pom based on the URL you provided that the `spring` plugin has been registered.

With that, there is nothing we can do here and the error you see is an IDE setup problem. I'd suggest to search and ask on StackOverflow if you don't find a similar question.
