### ISSUE TITLE
start.spring.io has no version control，Where is start.spring.io v0.8.0.RELEASE?

### ISSUE THREAD

**Issue by haydonchou** [spring-io/initializr#1055]
Where can I get the start.spring.io web ui corresponding to initializr v0.8.0.RELEASE?

Thanks！

**Comment by snicoll** [comment]
@haydonchou as documented [on the README](https://github.com/spring-io/start.spring.io#reusing-the-web-ui), the initializr project does not have a web UI. If you have further questions, please come chat with the community on Gitter or ask on StackOverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-io/initializr/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
