### ISSUE TITLE
Include Dockerfile

### ISSUE THREAD

**Issue by ttddyy** [spring-io/initializr#1058]
Recent spring blog post ["Creating Docker images with Spring Boot 2.3.0.M1"](https://spring.io/blog/2020/01/27/creating-docker-images-with-spring-boot-2-3-0-m1) advocates usage of exploded layout and layering while creating container image.

I checked our applications. Some have applied custom script to build layer images but some are just using `java -jar`.

It would be nice to include such `Dockerfile` by Initializr **when user choose container image creation to use `Dockerfile`**.

I see such request has declined before(#712), but is it still same now?

If it is available in start.spring.io, exploded layout with layering would become common practice for spring-boot applications.

**Comment by wilkinsona** [comment]
Thanks for raising this again, @ttddyy. Now that we have layered jar support coming in Boot 2.3 and, therefore, an opinion about the `Dockerfile` for a Boot app, I think it's worth considering again if we want to reflect that opinion on start.spring.io.

I’ve found myself wondering if we should do one of the following when using Boot 2.3:

1. Generate a `Dockerfile` that uses the layer tools and with an opinion about the base image that matches what the default CNB builder uses
2. Add something to HELP.md to guide people on how to Dockerize their app

I think I’m leaning towards 1 right now. One complication is that the layered jar is opt-in (and I think it should remain that way). That means that the `Dockerfile` would only be of use once a (small) change had been made to the build.gradle or pom.xml to opt in to the layered jar support.

An alternative would be to offer another packaging option alongside jar and war, but that's a change with far broader impact. It would require changes in the IDE support, for example.

**Comment by dsyer** [comment]
Layered jars are optional, but I wouldn't want to add a `Dockerfile` unless there was a new checkbox. I think the user should be able to choose between using the Spring Boot plugins (via buildpacks), or layers or just a vanilla Dockerfile that doesn't use layers (beyond what is already available in `BOOT-INF`).

**Comment by wilkinsona** [comment]
Given the success that we've seen with the buildpack support, particularly with the recent Spring Native integration, I'm no longer in favour of generating a Dockerfile with or without a checkbox to opt in to it. start.spring.io's opinion is that buildpacks are the way to go for generating container images and I think we should stick to that. We have [a section in Boot's documentation](https://docs.spring.io/spring-boot/docs/2.4.4/reference/htmlsingle/#boot-features-container-images-docker) for those that want to take a lower-level approach and use a Dockerfile. Thanks anyway for the suggestion, @ttddyy.
