### ISSUE TITLE
Feature request: Enable `-java-parameters` compile option for kotlin and `-parameters` for Java by default

### ISSUE THREAD

**Issue by tokuhirom** [spring-io/initializr#1063]
`-java-parameters` for kotlin and `-parameters` for Java is required compile option.

Some of the libraries take parameter names using reflection. e.g. MyBatis, Jackson, and spring boot actuator's `configprops`.

ref. https://kotlinlang.org/docs/reference/compiler-reference.html#-java-parameters

**Comment by tokuhirom** [comment]
https://github.com/spring-projects/spring-boot/blob/2c1e81adf085f35c09f778a728a878c7a96e43fd/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/context/properties/ConfigurationPropertiesReportEndpoint.java#L398-L399

Spring boot's ConfigurationPropertiesReportEndpoint depends on the parameter name.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. Spring Boot already takes care of this via `spring-boot-starter-parent` and its Gradle plugin. The former provides plugin management that enables `-java-parameters` for Kotlin's Maven plugin and `-parameters` for Maven's Compiler plugin. The latter does the equivalent for Gradle-based projects.
