### ISSUE TITLE
Build customizer for private repository which requires authentication

### ISSUE THREAD

**Issue by chihaiaalex** [spring-io/initializr#1064]
Hi,

Is there a way I can use an instance of a BuildCustomizer to add a private repository which requires authentication?

The way I used to configure it is:
```
maven {
            url 'http://link.to.my.private.repo:8081/artifactory/repo'
            credentials {
                username = "${artifactory_user}"
                password = "${artifactory_password}"
            }
        }
```

Where artifactory_user and artifactory_password are variables stored in gradle.properties.

Thanks!

**Comment by snicoll** [comment]
@chihaiaalex there is already an issue about supporting such construct, see #997.
