### ISSUE TITLE
MavenBuildWriter does not escape reserved characters

### ISSUE THREAD

**Issue by CloakingOcean** [spring-io/initializr#1066]
If in the options, a certain character is put inside of the Description area, it results in an invalid pom.xml.

![image](https://user-images.githubusercontent.com/26285018/76311257-2561bc00-6296-11ea-84f7-43be188aea70.png)

![image](https://user-images.githubusercontent.com/26285018/76311291-3b6f7c80-6296-11ea-8573-a9cb0bc4e900.png)

Solution:
To resolve this, the initializr should replace any invalid characters with escape characters. For example, the ampersand should be switched to its corresponding escape sequence: 

![image](https://user-images.githubusercontent.com/26285018/76311375-6fe33880-6296-11ea-994e-184b86964450.png)

I quickly found this website that shows a handful of escape characters: https://www.advancedinstaller.com/user-guide/xml-escaped-chars.html

**Comment by snicoll** [comment]
@CloakingOcean thanks for the report. I think `MavenBuildWriter` should be updated to make sure content  in general is escaped properly.

**Comment by snicoll** [comment]
Closing in favour of PR #1073
