### ISSUE TITLE
Groovy gradle files for Kotlin projects

### ISSUE THREAD

**Issue by dmitvitalii** [spring-io/initializr#1069]
Trying to generate a `2.3.0.BUILD-SNAPSHOT` Kotlin Gradle project, but initializr generates `*.gradle.kts` files.
It would be cool to have groovy Gradle configurations for a Kotlin project, instead of Kotlin DSL configurations.

**Comment by snicoll** [comment]
Thanks for the suggestion. The current arrangement does not need an extra option or a duplication of the build system. 

We think that a groovy based build with a kotlin project is unusual so I am not keen to offer an option for it.

**Comment by alwyn** [comment]
@snicoll Would you consider support for kotlin build scripts when selecting Java as the language?  Many of us prefer Kotlin, but are forced to use Java on our projects.

**Comment by snicoll** [comment]
@alwyn thanks for the feedback. We have no plan of switching to Kotlin for Java-based projects and adding the option was considered before and proved to be challenging. That said, if you feel strongly about it, please create an issue in the start.spring.io issue tracker https://github.com/spring-io/start.spring.io/issues
