### ISSUE TITLE
Allow arbitrary code snippet to be added to GradleBuild

### ISSUE THREAD

**Issue by jjathman** [spring-io/initializr#1079]
In my custom Spring initializr instance I would like to include this block in every `build.gradle` file that is produced. As far as I could tell there was no way to produce a `from` block that took a string parameter as well as a closure parameter. It's possible I was missing this though.

```
distributions {
    main {
        contents {
            from('src/main/resources/application.yml') {
                into "conf"
                rename "(.*)", '$1.j2'
            }
        }
    }
}
```

**Comment by wilkinsona** [comment]
Thanks for your patience.

I'm afraid I don't think I understand the request. The original title of the issue was "Unable to customize distributions fully" but Initializr has no support at all at the moment for configuring a Gradle build's distributions. If you are extending the Groovy and Kotlin DSL writers' capabilities to support the configuration of distributions, can you not implement support for the `from` block that meets your needs?

**Comment by jjathman** [comment]
Sorry about the confusion, I was trying to show what I'm attempting to do with my code block in my original post. I want to be able to customize the generated `build.gradle` file by customizing the `distributions` block. The problem is due to `GradleTask.Builder` having an `invoke` method but that method does not allow for passing a closure to the method to invoke. I'm trying to generate the code from my original post, but it is very difficult to do. The code below was the solution I came up with, but it is definitely a hack. 

```

    private void customizeDistributionContents(GradleBuild build) {
        build.tasks().customize("distributions") { task ->
            task.nested("main") { mainBuilder ->
                mainBuilder.nested("contents") { contentsBuilder ->
                    contentsBuilder.invoke("from(", """ 'src/main/resources/application.yml') {
                        into 'conf'
                        rename '(.*)', '\$1.j2'
                    }
                    """)
                }
            }
        }
    }
```

An alternative that would be fine with me would to be able to customize the final content of the file and just being able to add this additional block of content. I realize my use case is probably rather unique. The existing `GradleBuild.Builder` API is really close, but just wasn't quite flexible enough for my needs.

**Comment by wilkinsona** [comment]
Thanks for the clarification. Your code above is treating `distributions` as a task when it's actually an extension. It's purely accidental that you can get as close as you have done.

I don't think we want to provide a complete API for writing arbitrary Groovy or Kotlin DSL code so an escape hatch that allows customisation of the end result may be the best option here.

**Comment by jjathman** [comment]
Thanks for the help. I think you are right that just some kind of callback that allows for final customization before writing the file would work just great for me.
