### ISSUE TITLE
error with install the project local by tags:0.6\0.7\0.8 and master

### ISSUE THREAD

**Issue by wangqinyu** [spring-io/initializr#1081]
i try to make install with maven and idea,but many errors in  process.can you install suceesful?

**Comment by snicoll** [comment]
@wangqinyu we have a CI that is green with [the build instructions](https://github.com/spring-io/initializr#building-from-source). It is impossible for us to help based on the details you've provided. What is the error on the command line? Please share more details about your environment.

**Comment by wangqinyu** [comment]
I pick two problems ,then i start up the project (tags:0.6),now i list these:
bug 1：in module initializr-service pom.xml  version is incorrect,the right version is below:
`<parent>
		<groupId>io.spring.initializr</groupId>
		<artifactId>initializr</artifactId>
		<version>**_0.6.0.RELEASE_**</version>
</parent>`

bug 2:
when i use maven installing the project ,i need add skip tests params ,or the project will be done,i think there are some problems in test codes maybe . i also find other people talking about it in websites.

(I need to start the spring initializr server on my local computer ,and my computer is offline.)

**Comment by wangqinyu** [comment]
I pick two problems ,then i start up the project (tags:0.6),now i list these:
bug 1：in module initializr-service pom.xml version is incorrect,the right version is below:
```
<parent>
		<groupId>io.spring.initializr</groupId>
		<artifactId>initializr</artifactId>
		<version>0.6.0.RELEASE</version>
</parent>
```

bug 2:
when i use maven installing the project ,i need add skip tests params ,or the project will be done,i think there are some problems in test codes maybe . i also find other people talking about it in websites.

(I need to start the spring initializr server on my local computer ,and my computer is offline.)

**Comment by snicoll** [comment]
@wangqinyu I understand that building against a tag is important and I remember a problem when tagging 0.6 but there's nothing I can do about that now. 0.6.0.RELEASE is available on `repo.spring.io` so please use that.

You still haven't shared your logs and your environment. Can you please do that rather than maybes?

**Comment by wangqinyu** [comment]
sorry，i have some trouble yesterday,now i reimport the branch of master and use maven to install the project .
[error logs]
Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.1.1:single (build-assets) on project initializr-web: Failed to create assembly: Error creating assembly archive snippets: archive cannot be empty`

[env]
Windows 10 + IDEA 2019.2 + Oracle jdk 1.8 + apache-maven-3.6.2 
i also add skip test params before maven install.

**Comment by snicoll** [comment]
You can’t skip tests unfortunately. Please follow the build instructions in the README.
