### ISSUE TITLE
Add option to download generated project to local directory instead of HTTP response

### ISSUE THREAD

**Issue by dsyer** [spring-io/initializr#1088]
@BoykoAlex has prototyped this and it's not a huge amount of code. What he did was add a new API endpoint `/generate' alongside `/starter.zip` (essentially). We could discuss the merits of doing that versus in some way overloading the existing endpoint to generate locally instead of download. This is a useful feature for people that want to embed Initializr in a developer portal.

**Comment by snicoll** [comment]
This is quite a specific use case that does not warrant code in the library. If you want to add your own endpoints, you can have your own `ProjectGenerationController`.
