### ISSUE TITLE
Spring 2.4.0 spring-boot docs version issue

### ISSUE THREAD

**Issue by adzeeman** [spring-io/initializr#1089]
Hi,

I noticed that the released spring-boot/docs/ version format changed from `Major.Minor.Patch.Qualifier` to`Major.Minor.Patch-Qualifier`. Was this intended, or is it a bug?

Unfortunately, it breaks the Spring Initializr project: https://github.com/benwilcock/axon-initializr when it is trying to fetch the metadata from https://spring.io/project_metadata/spring-boot
```
Could not determine version based on '2.4.0-SNAPSHOT': version format is Major.Minor.Patch.Qualifier (e.g. 1.0.5.RELEASE)
```

https://docs.spring.io/spring-boot/docs/
![image](https://user-images.githubusercontent.com/16647829/83266578-4fef5100-a1c3-11ea-9268-afacab8517bf.png)

**Comment by wilkinsona** [comment]
Yes, this was intentional. Please see [this blog post](https://spring.io/blog/2020/04/30/updates-to-spring-versions) for the announcement of the change to the versioning scheme. The Axon Initializr project needs to be updated to use a version of Initializr that includes [these changes](https://github.com/spring-io/initializr/commit/0b7614c4f06046b453a01885e347220d913d9f59).

**Comment by adzeeman** [comment]
> Yes, this was intentional. Please see [this blog post](https://spring.io/blog/2020/04/30/updates-to-spring-versions) for the announcement of the change to the versioning scheme. The Axon Initializr project needs to be updated to use a version of Initializr that includes [these changes](https://github.com/spring-io/initializr/commit/0b7614c4f06046b453a01885e347220d913d9f59).

Noted. Thanks for the speedy response!

**Comment by jjathman** [comment]
Any chance this fix could get back ported to 0.8 if 0.9 won’t be released soon? Or is there a workaround?

**Comment by snicoll** [comment]
@jjathman we will release 0.9 sooner than latter as I didn't anticipate it would be a problem for users on 0.8 using live  versions.

>  is there a workaround?

Yes. Register your own `DefaultInitializrMetadataUpdateStrategy` and override `fetchSpringBootVersions` to remove any `2.4` versions.

**Comment by adzeeman** [comment]
Thanks, @snicoll. Your suggestion worked.

For those interested: https://github.com/adzeeman/axon-initializr
