### ISSUE TITLE
Metadata is not backward compatible when using SemVer or CalVer versions

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#1092]
The new SemVer and CalVer formats are unfortunately breaking existing clients as they parse ranges and expect versions to be in a quite specific format. To be able to use the new format publicly, we should translate those versions to the previous format.

Replacing a `-` with a `.` for the version qualifier isn't such a big deal. Unfortunately version comparison is also probably broken (`.RELEASE` vs. no qualifier).

**Comment by snicoll** [comment]
So to make sure version ordering works properly we'd have to replace `SNAPSHOT` with `BUILD-SNAPSHOT`. This [is documented](https://docs.spring.io/initializr/docs/current/reference/html/#dependencies-compatibility-range) (and I can see now it is outdated too) so we'll have to do that too I am afraid.

**Comment by snicoll** [comment]
After a brainstorming with @wilkinsona we feel that the library should address this concern. Offering a new format for the version should not impact existing clients so we should:

* Translate all versions from the new format to the previous one in outgoing metadata with the current version (v2.1)
* Introduce a new version that allows the new format to be used (v2.2)
* Provide a strategy to translate an incoming request from the previous format to the new one. This is required as the version that's transformed in the metadata will be used to issue a request for a new project.

**Comment by snicoll** [comment]
Wow, this turned out to be more involved than I thought it would be. As a result, we're now introducing a new metadata version `v2.2` that serves version with both the original format and the SemVer format. 

Clients that are requesting `v2.1` gets backward compatible formats. We should make sure that they upgrade to `v2.2` ASAP.

**Comment by pstitt** [comment]
Just checking, we have run into what looks like this issue. Our initializr service is failing with:

`Caused by: io.spring.initializr.generator.version.InvalidVersionException: Could not determine version based on '2.4.0-M1': version format is Major.Minor.Patch.Qualifier (e.g. 1.0.5.RELEASE)`

We download the config daily from:

https://raw.githubusercontent.com/spring-io/start.spring.io/master/start-site/src/main/resources/application.yml

Is there a fix now for this? We are on the latest release 0.8.0.RELEASE

**Comment by wilkinsona** [comment]
@pstitt The fix is in 0.9.0 snapshots that are available from https://repo.spring.io/snapshot.

**Comment by pstitt** [comment]
Thanks @wilkinsona it took a while as there were some breaking changes, but it is now working again.
