### ISSUE TITLE
Validation selection should include "hibernate-validator-annotation-processor"

### ISSUE THREAD

**Issue by candrews** [spring-io/initializr#1097]
When the "Validation" option is selected, it currently only adds a dependency on `spring-boot-starter-validation`. It would be a nice improvement to also add a dependency on "org.hibernate.validator:hibernate-validator-annotation-processor"

For Gradle:
`annotationProcessor 'org.hibernate.validator:hibernate-validator-annotation-processor'`

For Maven:
```
<dependency>
  <groupId>org.hibernate</groupId>
  <artifactId>hibernate-validator-annotation-processor</artifactId>
</dependency>
```
"org.hibernate.validator:hibernate-validator-annotation-processor" is really helpful:
> Have you ever put a constraint annotation to an unsupported location and wished to find out about that at build time rather than at runtime? Then the Hibernate Validator Annotation Processor is the right thing for you.
>
> It helps to detect glitches such as:
>
>    * Putting a constraint to bean properties which are not supported by that constraint (e.g. putting `@Date` to a String)
>    * Annotating the setter of a bean property instead of the getter
>    * Adding constraints to static fields or methods
> When detecting these and other unsupported constraint usages, the Hibernate Validator Annotation Processor will raise an error at build time, saving you valuable time.

--- https://hibernate.org/validator/tooling/

**Comment by snicoll** [comment]
Thanks for the suggestion but that use case isn't common enough to warrant us to do this automatically.
