### ISSUE TITLE
Offer the possibility to change dependency order in MavenBuildWriter or GradleBuildWriter

### ISSUE THREAD

**Issue by ggerbaud** [spring-io/initializr#1098]
In `MavenBuildWriter` dependencies are sorted regarding their scope then with this `Comparator` [here](https://github.com/spring-io/initializr/blob/master/initializr-generator/src/main/java/io/spring/initializr/generator/buildsystem/maven/MavenBuildWriter.java#L217). This comparator sort Spring-Boot dependencies first. But there is no way to change this comparator without re-write entirely the `MavenBuildWriter`.

It would be nice to have the ability to use a custom comparator here

**Comment by snicoll** [comment]
In both Maven and Gradle, indeed. Sounds about right, thanks for the suggestion.
