### ISSUE TITLE
gradle daemon keeps spawning

### ISSUE THREAD

**Issue by young-zy** [spring-io/initializr#1099]
I noticed that configuration of gradle wrapper has updated the daemon version to 6.4.1, and when building new spring boot project using kotlin(not tested with other language), it keeps starting new daemons until all of the memory is used(then it crashed)
change the version in wrapper properties down to 6.3 seems to solve the issue

to reproduce:
start a new project on spring initializr(in my case, i generate the project in intellij)
set as gradle project
use kotlin as language
spring boot version 2.3.0
java version 11
then let it build(it takes up all the memory, then crash)

if you use gradlew in cli, you may notice that daemons keep spawning and stays in busy state.

i'm not quite sure where I should post this issue, if I did anything wrong, please let me know.

Best Regards.

**Comment by wilkinsona** [comment]
Thanks for the report but I cannot reproduce the behaviour that you have described. Building on the command line I see a single Gradle daemon being started. This daemon is then reused each time I build the project. After numerous builds, `./gradlew --status` shows that there is a single daemon running.

If you are using IntelliJ, it delegates its build actions to Gradle by default. Given that I cannot reproduce the problem on the command line, I would guess that the problem you are seeing is being caused by IntelliJ and how it delegates to Gradle. You may want to check that you have the latest version of IntelliJ installed. If the problem persists, I would recommend reporting it to JetBrains.

**Comment by young-zy** [comment]
> Thanks for the report but I cannot reproduce the behaviour that you have described. Building on the command line I see a single Gradle daemon being started. This daemon is then reused each time I build the project. After numerous builds, `./gradlew --status` shows that there is a single daemon running.
> 
> If you are using IntelliJ, it delegates its build actions to Gradle by default. Given that I cannot reproduce the problem on the command line, I would guess that the problem you are seeing is being caused by IntelliJ and how it delegates to Gradle. You may want to check that you have the latest version of IntelliJ installed. If the problem persists, I would recommend reporting it to JetBrains.

Thanks for the reply. I've solved the issue. The cause are as follows.
I checked the daemon log and noticed that in every log,  there's an error on connecting to the daemon on 127.0.0.1 after created one. 
I tried to ping 127.0.0.1 and the result was time out!(Pretty unexpected)
So it is obvious that gradle wrapper created a daemon and could not connect to it. It then tried to create another one, and on and on, without an end.

I tried to reset winsock and network interface, but it didn't work.
I then tried changing the locale settings and checked the experimental utf-8 support(which i used to checked but some of the software i use may misbehave), restart, and I can ping to 127.0.0.1 again.

I'm not quite sure which part I did solve the issue(i guess it was the locale and OS problem. Since i tried to reboot some times before, but that didn't work)

Sorry for wasting your precious time.

All the best.

**Comment by ccsugar** [comment]
Same problem,your solution really help!

**Comment by young-zy** [comment]
> Same problem,your solution really help!

well actually, some days after I posted the solution, I found out that opening a wlan mobile hot spot on my laptop can also cause issue pinging or connecting to 'localhost'. Not really sure which one was the real cause, but I'm unable to test it since the issue has never showed up again after i upgraded my windows 10 to 2004 (in percise, after a major update).

**Comment by ccsugar** [comment]
Yes,my windows is 1809,just moment ago I found when my wlan hot spot is opening I can not connect 127.0.0.1(localhost),but I can connet to ::1.

> > Same problem,your solution really help!
> 
> well actually, some days after I posted the solution, I found out that opening a wlan mobile hot spot on my laptop can also cause issue pinging or connecting to 'localhost'. Not really sure which one was the real cause, but I'm unable to test it since the issue has never showed up again after i upgraded my windows 10 to 2004 (in precise, after a major update).
