### ISSUE TITLE
Clarify that Initializr does not provide a web UI

### ISSUE THREAD

**Issue by silloy** [spring-io/initializr#1100]
I build my own instance, but only json, how can I open the web ui?

I build the instance base on spring boot 2.2.7.RELEASE
```
 <dependencies>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>

    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <optional>true</optional>
    </dependency>

    <dependency>
      <groupId>io.spring.initializr</groupId>
      <artifactId>initializr-web</artifactId>
    </dependency>
    <dependency>
      <groupId>io.spring.initializr</groupId>
      <artifactId>initializr-generator-spring</artifactId>
    </dependency>

    <dependency>
      <groupId>io.spring.initializr</groupId>
      <artifactId>initializr-generator</artifactId>
    </dependency>

  </dependencies>
<dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.spring.initializr</groupId>
        <artifactId>initializr-bom</artifactId>
        <version>0.8.0.RELEASE</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

when I execute jar, open localhost:9090 (I have changed the port), it show:
![image](https://user-images.githubusercontent.com/12909107/84849374-b0b5cf00-b087-11ea-8021-d964133916aa.png)

how can I get the web ui just like start.spring.io

**Comment by silloy** [comment]
And I follow the doc: https://docs.spring.io/initializr/docs/current-SNAPSHOT/reference/html/

**Comment by wilkinsona** [comment]
The start.spring.io web UI is managed as part of a [separate project](https://github.com/spring-io/start.spring.io). If you are considering reusing it, please note the [advice in the README](https://github.com/spring-io/start.spring.io#reusing-the-web-ui).

I think we should update this project’s reference documentation to clarify the separation. The docs currently talk about the web UI without making it clear where the source for that web UI can be found. We also need to consider to what extent we want to mention start.spring.io as it creates a cycle between the two projects.

**Comment by dvsingh9** [comment]
I can write that clarification on docs

**Comment by snicoll** [comment]
Thanks for the offer @dvsingh9 but we'd like to restructure the reference guide as Andy explained in a comment above yours, which will make this task more involved than adding a clarification.
