### ISSUE TITLE
SemVer backward compatibility for V1 format keeps wrong id for default in `bootVersion`

### ISSUE THREAD

**Issue by ggerbaud** [spring-io/initializr#1112]
When calling a V2 format server with a V1 client (`Accept: application/vnd.initializr.v2.1+json`) we get something like that:

```json
"bootVersion": {
    "type": "single-select",
    "default": "2.4.2",
    "values": [
      {
        "id": "2.5.0.BUILD-SNAPSHOT",
        "name": "2.5.0-SNAPSHOT"
      },
      {
        "id": "2.4.2-RELEASE",
        "name": "2.4.2"
      }
    ]
  }
```

but `"default"` value should be `2.4.2-RELEASE`

EDIT : fix proposal in PR below

**Comment by snicoll** [comment]
@ggerbaud thanks for the PR. FTR there is no need to create an issue and a PR as one supersedes the other.

Closing in favour of #1112
