### ISSUE TITLE
Use the latest version of Gradle in gradle projects

### ISSUE THREAD

**Issue by karuppiah7890** [spring-io/initializr#1117]
Currently v6.4.1 is being used while generating gradle projects. Latest as of this writing is 6.6

I'll raise a PR for the same 😄

**Comment by snicoll** [comment]
Thanks for the suggestion. For the record we don’t need a PR and an issue as one supersedes the other.

**Comment by karuppiah7890** [comment]
Ah okay! 👍 Didn't know 😅 Probably something worth mentioning the [CONTRIBUTING](https://github.com/spring-io/initializr/blob/master/CONTRIBUTING.adoc) doc too
