### ISSUE TITLE
Generated tgz file leads to "end of file error"

### ISSUE THREAD

**Issue by mikzuit** [spring-io/initializr#1120]
not 100% sure (haven't found otherwise rules in documentation) but please let me now if this is intended:

error:

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

steps to reproduce:

1. gives an end of file error because groupId has more than 1 dot ( . ) like:

```
curl https://start.spring.io/starter.tgz -d dependencies=web,jpa,h2,lombok -d groupId=com.mikzuit.developer -d javaVersion=14 -d language=java -d type=maven-project -d baseDir=java-springboot-project | tar -xzvf - 
```

```
curl https://start.spring.io/starter.tgz -d dependencies=web,jpa,h2,lombok -d groupId=com.mikzuit.v1 -d javaVersion=14 -d language=java -d type=maven-project -d baseDir=java-springboot-project | tar -xzvf - 
```

also: 
2. gives and end of file error cause "artifactId" and "name" are not equal or contain more than 1 dash ( - )

```
curl https://start.spring.io/starter.tgz -d dependencies=web,jpa,h2,lombok -d groupId=com.mikzuit -d artifactId=school-service-artifact -d name=school-service -d javaVersion=14 -d language=java -d type=maven-project -d baseDir=java-springboot-project | tar -xzvf - 
```

```
curl https://start.spring.io/starter.tgz -d dependencies=web,jpa,h2,lombok -d groupId=com.mikzuit -d artifactId=school-service-micro -d name=school-service-micro -d javaVersion=14 -d language=java -d type=maven-project -d baseDir=java-springboot-project | tar -xzvf - 
```

**Comment by snicoll** [comment]
@mikzuit there are some best efforts cleaning rules to avoid the use of reserved characters. Can you please double check the two commands you've shared as they don't generate the problems you've describe. In particular 2

**Comment by mikzuit** [comment]
I double check before and I tried now inside a Fedora 7.8 docker container with same results. I extend my first comment with few more command not allowed.

**Comment by snicoll** [comment]
Unfortunately, I don't think there is anything we can do here about it. This looks like a limitation of your shell on the version of `tar` you're using.

This command generates a project:

```
curl https://start.spring.io/starter.tgz -d dependencies=web,jpa,h2,lombok -d groupId=com.mikzuit.developer -d javaVersion=14 -d language=java -d type=maven-project -d baseDir=java-springboot-project -o java-springboot-project.tgz
```

If extracting this tgz leads to an error for you, it does not for me.

You may want to try a zip instead:

```
curl https://start.spring.io/starter.zip -d dependencies=web,jpa,h2,lombok -d groupId=com.mikzuit.developer -d javaVersion=14 -d language=java -d type=maven-project -d baseDir=java-springboot-project -o java-springboot-project.zip
```

I am going to close this now. If you need more support using `tag`on Fedora, I suggest asking on StackOverflow.

**Comment by mikzuit** [comment]
how about this, does create a non empty project for you?

curl https://start.spring.io/starter.tgz -d dependencies=web,jpa,h2,lombok -d artifactId=service-school -d name=service-school -d groupId=com.mikzuit.developer -d javaVersion=14 -d language=java -d type=maven-project -d baseDir=java-springboot-project -o java-springboot-project.tgz

**Comment by snicoll** [comment]
This command is a totally different problem, I've created #1121.
