### ISSUE TITLE
Bind to custom project request example

### ISSUE THREAD

**Issue by FPS-Lyon** [spring-io/initializr#1129]
Hello,
Can you provide an code example of how to bind to custom project request. 
I tried with the instructions provided in the documentation but I always get a Nullpointer exception when building the project.

thanks

**Comment by snicoll** [comment]
@FPS-Lyon there's not much more to it, really. There is also an [integration test that exercises the feature](https://github.com/spring-io/initializr/blob/80b82c9042d2a629b7984077de8b9a4502c76d65/initializr-web/src/test/java/io/spring/initializr/web/controller/custom/ProjectGenerationControllerCustomRequestIntegrationTests.java). If you want support, please take the time to share a minimal sample that we can run ourselves that demonstrates the problem you've described.

**Comment by FPS-Lyon** [comment]
@snicoll Thanks for your help. Integration test was very useful. I share my [repository](https://github.com/FPS-Lyon/custom-spring-initializr) with a working example.
I have another question regarding the possibility of making the request custom fields appear in the metadata when I query the service.

**Comment by snicoll** [comment]
>  Thanks for your help. Integration test was very useful

I am glad it was useful. Thank you for sharing your example with the rest of the community. 

> I have another question

As mentioned in [the guidelines for contributing](https://github.com/spring-io/initializr/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Please ask questions on StackOverflow or come chat with the community on our Gitter channel.
