### ISSUE TITLE
No all-open config with Kotlin + Spring Data JPA

### ISSUE THREAD

**Issue by timmyyy** [spring-io/initializr#1130]
When generating Spring project with Kotlin and JPA options it creates a maven / gradle config with "jpa" and "spring" plugins:
```
...
    <build>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <configuration>
                    <compilerPlugins>
                        <plugin>spring</plugin>
                        <plugin>jpa</plugin>
...
```

But to enable Hibernate to generate proxies for Entity classes it must create "all-open" plugin config for them as well:
```
...
           <compilerPlugins>
                        <!-- no-arg constructor for jpa entities -->
                        <plugin>jpa</plugin>
                        <!-- open @Component, @Async, @Transactional, @Cacheable and @SpringBootTest classes -->
                        <plugin>spring</plugin>
                        <!-- open Entities to let them using Lazy with ManyToOne -->
                        <plugin>all-open</plugin>
                    </compilerPlugins>
                    <pluginOptions>
                        <!-- open Entities to let them using Lazy with ManyToOne -->
                        <option>all-open:annotation=javax.persistence.Entity</option>
                        <option>all-open:annotation=javax.persistence.Embeddable</option>
                        <option>all-open:annotation=javax.persistence.MappedSuperclass</option>
                    </pluginOptions>
...
```
We can see the same config in Spring Boot + Kotlin tutorial on [the official website](https://spring.io/guides/tutorials/spring-boot-kotlin/). Also there was a discussion about adding this behaviour in "jpa" plugin in [KT-28594](https://youtrack.jetbrains.com/issue/KT-28594)

Otherwise we easily get into N+1 problem when querying an entity collection with `@ManyToOne` mapping in it:
```kotlin

@Entity
@Table(name = "commits")
class Commit(
    @Id var id: Int = 0,
    var hash: String? = null,

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "author_id")
    var author: Author
)

@Table(name = "authors")
@Entity
class Author (
    @Id var id: Int = 0,

    @OneToMany(mappedBy = "author")
    var commits: MutableList<Commit> = mutableListOf()
)

interface CommitRepository : JpaRepository<Commit, Int> 

```
Calling `commitRepository.findAll()` causes Hibernate to fetch firstly all commits and then, as it fails to create a proxy for the mapped fields, their authors, each in a separate query. Moreover, if commit has other `@ManyToOne` mappings - they'd go in a separate query too, and if author has it's own `@ManyToOne` mappings ...you know where it leads. 

When I select Java to use in a generated project this lazy fetch behavior is supported out-of-the-box due to the fact that all classes in Java are "open" from Kotlin perspective.

So I am absolutely sure that this config should be added in standard Kotlin + Spring Data JPA project initializr as I constantly see how such applications go in production causing enormous overhead there😩

**Comment by snicoll** [comment]
Thanks for the report. Paging @sdeleuze to see if your setup is inconsistent or if something else is going on.

**Comment by snicoll** [comment]
There is some discussion on the JetBrains issue I can see where it looks like the fix should go in the Kotlin plugin. Should this issue still be pursued?

**Comment by timmyyy** [comment]
@snicoll I found two issues on JetBrains tracker related to this one: [KT-28594](https://youtrack.jetbrains.com/issue/KT-28594) and [KT-28189](https://youtrack.jetbrains.com/issue/KT-28189). Both created 2 years ago. Until they're fixed this one is actual. Let's see if JB team has any plans for it, and if the plans are not very short term then I believe it has to be fixed at least in Initializr. What do you think?

**Comment by sdeleuze** [comment]
@timmyyy I think this should be fixed via [KT-28594](https://youtrack.jetbrains.com/issue/KT-28594), I have contacted JetBrains to move forward on solving it. As a consequence, I think this issue should be closed.

**Comment by snicoll** [comment]
Thanks @sdeleuze, I feel the same way and I prefer not having to add too much knowledge here for something that is a limitation in the Kotlin plugin. Thanks for the report, in any case.
