### ISSUE TITLE
Add support for Maven defaultGoal

### ISSUE THREAD

**Issue by mikomatic** [spring-io/initializr#1133]
For my use case, i would like support `defaultGoal` element in pom.xml generation.

Would love to contribute a PR if that is acceptable, it seems that impacts are restrained to:

- MavenBuildSettings
- MavenBuildWriter
- MavenBuildWriterTests
- Maybe MavenBuildTests

**Comment by snicoll** [comment]
@mikomatic thanks for the suggestion. That sounds reasonable and thank you for offering to contribute. I'd love reviewing a PR for that feature.

**Comment by snicoll** [comment]
Closing in favour of PR #1134
