### ISSUE TITLE
Add Gradle build customizations for Devtools in spring conventions

### ISSUE THREAD

**Issue by jjathman** [spring-io/initializr#1135]
I think the default behavior of the [Spring Initializr](https://start.spring.io) website for DevTools is a reasonable thing to incorporate in to the Spring Intializr library itself as it helps prevent DevTools from being accidentally deployed in to production.

See https://github.com/spring-io/start.spring.io/blob/master/start-site/src/main/java/io/spring/start/site/extension/dependency/springboot/DevToolsGradleBuildCustomizer.java for how this can be accomplished.

**Comment by snicoll** [comment]
Thanks for the suggestion. Yeah I guess an argument could be made that this code can move although we can't move the registration as `devtools` is the id of the dependency and can be something entirely different in a custom instance. 

We don't have much customisations that check the version of Spring Boot (The gradle version condition is the main one). I've flagged this for team attention to see if anyone else feels differently.

**Comment by snicoll** [comment]
We discussed this one at the team meeting and while we can keep that `devtools` reference in the code, we could make it a second argument of the constructor.
