### ISSUE TITLE
Upgrade to GMavenPlus 1.11.0

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/initializr#1140]
When generating a Groovy project, 1.8.1 of the GMavenPlus plugin is added to the project. It is not compatible with Java 15. We should consider upgrading.

**Comment by snicoll** [comment]
We can upgrade to `GMavenPlus` 1.11.0 but that one requires Groovy 3 which we don't provide dependency management for. We could override the version of Groovy when Java 15 is selected or just downgrade to 11 as we usually do when this isn't supported. I'd like to do the latter as using Java 15 shouldn't be important for someone working on a Groovy project.

Let's reuse this issue to upgrade to a more recent version of `GMavenPlus`
