### ISSUE TITLE
Project generated by Spring Initializr has wrong build path

### ISSUE THREAD

**Issue by ngoc199** [spring-io/initializr#1149]
I have created a project using Spring Extension in Visual Studio Code. That extension uses Spring Initializr to create new Spring project.

Then when I try to run the generated project without making any changes, VS Code throws the error `The project was not built since its build path is incomplete. Cannot find the class file for java.lang.Object. Fix the build path then try building this project`.

When I create new file, the package start from `src.main.java.com.bank`, which should be `com.bank`.

I also try using online Spring Initializr, but there is no magic.

I have made sure that my Environment Variable is correct. I am using JDK 11. And my other Java projects (not Spring) is still working well.

How can I solve this issue?

**Comment by snicoll** [comment]
Thanks for the report but the VSCode extension is not managed here. I am not sure if that's a problem specific to Spring Initializr at all though. Please report this issue in the VSCode extension https://github.com/microsoft/vscode-spring-initializr with a step-by-step description of how you generated the project.

**Comment by ngoc199** [comment]
@snicoll I have tried to create the project using the Spring Initializr on the web, but the result still the same. I have mentioned it in the issue detail too. So I believe this is the Spring Initializr issue.

**Comment by snicoll** [comment]
I don't understand the issue so you'll have to provide a step-by-step guide and something that reproduces the problem outside of VSCode. If you can provide that, I am happy to reconsider.

**Comment by ngoc199** [comment]
I have installed Spring Tool Suite to try to reproduce the problem with different IDE.

I created new project using Spring Tool Suite, which still use Spring Initializr to create the project and then download it.

Then I got this error
![image](https://user-images.githubusercontent.com/53241275/99675787-3829c300-2aaa-11eb-93fc-847fef68a0e7.png)

Can you help me fix this problem?

**Comment by snicoll** [comment]
> Can you help me fix this problem?

I am afraid I can't as the error there is yet another issue (a network problem on your box).  As mentioned in [the guidelines for contributing](https://github.com/spring-io/initializr/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements so please follow-up on StackOverflow for usage question.

**Comment by ngoc199** [comment]
> > Can you help me fix this problem?
> 
> I am afraid I can't as the error there is yet another issue (a network problem on your box) and unrelated to this project. As mentioned in [the guidelines for contributing](https://github.com/spring-io/initializr/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements so please follow-up on StackOverflow for usage question.

Thank you for taking your time!
I will try looking on stackoverflow.

**Comment by ngoc199** [comment]
I have found what the problem is. It's surprisingly I have a `.metadata` folder that do something I don't know but changing the build path. I have deleted it and everything works fine in VS Code. =)))
