### ISSUE TITLE
Generated zip distribution does not produce a green build on Windows

### ISSUE THREAD

**Issue by alecss131** [spring-io/initializr#1150]
First i have errors **Formatting violations found in the following files** on generator but fix this with **mvnw spring-javaformat:apply**
And have next error
```
-------------------------------------------------------------------------------
Test set: io.spring.initializr.generator.test.buildsystem.gradle.GroovyDslGradleBuildAssertTests
-------------------------------------------------------------------------------
Tests run: 10, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.084 s <<< FAILURE! - in io.spring.initializr.generator.test.buildsystem.gradle.GroovyDslGradleBuildAssertTests
containsOnlyExtProperties  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError: 

Expecting:
 <"plugins {
	id 'com.example' version '1.0.0.RELEASE'
	id 'java'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '1.8'

repositories {
	mavenCentral()
}

ext {
	set('acmeVersion', "Brussels.SR2")
}

dependencies {
	implementation 'com.example.acme:library'
	testImplementation 'com.example.acme:library-test'
}

dependencyManagement {
	imports {
		mavenBom "com.example.acme:library-bom:${acmeVersion}"
	}
}

">
to contain:
 <"ext {
	set('acmeVersion', "Brussels.SR2")
}"> 
	at io.spring.initializr.generator.test.buildsystem.gradle.GroovyDslGradleBuildAssertTests.containsOnlyExtProperties(GroovyDslGradleBuildAssertTests.java:85)
```
How fix this? **Generator (Test Infrastructure) FAILURE** Idonthave dump files in initializr-0.9.2\initializr-generator-test\target\surefire-reports

**Comment by snicoll** [comment]
The build is green and it looks like you're building on a tag so even more so. I can only guess that you are on Windows and some line ending problem tricked you? We have a build on Windows that's green too so I am not sure what's happening. 

Please review your git configuration and make sure you're not converting line endings.

**Comment by loginmen** [comment]
yes on windows 10, i download source from code -> download zip or releases -> Source code (zip). after unpack using 7zip and give this errors. now i try **git clone** and **mvnw clean install** and all build fine

**Comment by snicoll** [comment]
Thank you for the feedback, this zip is generated by GitHub so I don't really know yet what happened and how we can control it but I don't think this problem should be addressed in this project specifically. I'll investigate a bit more. Please clone the project if you want to build from source.

**Comment by lagooned** [comment]
confirming this is still an issue

**Comment by mhalbritter** [comment]
I'm closing this issue, as building the project is possible on Windows, as proven by our CI.
