### ISSUE TITLE
Is support remove default ProjectContributor?

### ISSUE THREAD

**Issue by liaomengge** [spring-io/initializr#1156]
i need to generator custom skeleton file, but i don't need the default ProjectContributor, Whether configuration can be developed

**Comment by snicoll** [comment]
`initializr-generator-spring` is an optional module and you don't have to include it if you don't want to use it. If you need some of the features but don't want the contributors, you can filter them out using an override of `ProjectGenerator`. 

Going forward, please ask questions on our Gitter channel or StackOverflow, as mentioned in [the guidelines for contributing](https://github.com/spring-io/initializr/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements.
