### ISSUE TITLE
JCache configuration customization cannot be easily customized

### ISSUE THREAD

**Issue by ggerbaud** [spring-io/initializr#1157]
What the best way, if any, to override [the cache configuration](https://github.com/spring-io/initializr/blob/master/initializr-web/src/main/java/io/spring/initializr/web/autoconfigure/InitializrAutoConfiguration.java#L187)  ?

I want to increase expiry policy

**Comment by snicoll** [comment]
@ggerbaud thanks for the report. It's not  great at the moment if you're using JCache. The intent was to auto-provide a sensible configuration for caches that we use but with a better split between the services and the library, the situation was not revisited.

What cache library are you using?

**Comment by ggerbaud** [comment]
I am using ehcache (but I can use another if needed) but if I define a cache named `initializr.metadata` in my ehcache.xml, then the `InitializrAutoConfiguration$InitializrCacheConfiguration` fails because cache already exists

**Comment by snicoll** [comment]
Thanks for the feedback. Yep, that's far from ideal, we'll have to change the logic there.
