### ISSUE TITLE
BOM may lead to inconsistent boot dependencies

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#116]
Use case: latest Spring Boot build (relying on Spring Framework 4.2) with a Cloud dependency. Currently we had the BOM for spring cloud in the `dependencyManagement` section of the generated project.

Since we rely on the parent for all the rest, we end up with mixed dependencies since the cloud dependency has a _shorter_ dependency path than all the rest. 

Updating the dependency management to add the `spring-boot-dependencies` BOM as the first entry fixes the problem, something like:

```xml
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.boot</groupId>
		        <artifactId>spring-boot-dependencies</artifactId>
		        <version>1.3.0.BUILD-SNAPSHOT</version>
		        <type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-starter-parent</artifactId>
				<version>1.0.1.RELEASE</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
```

Not sure how we could fix that:

1. Switch the projet to be parent-less (and always add this entry). I suspect that users are actually relying on the parent pom and adapt that to their own once the project is created. 
2. Add the `spring-boot-dependencies` BOM if another bom should be added

Note that in both cases, the simple overriding of dependency version via a property will not work anymore since the BOM declaration will _fix_ them.

**Comment by snicoll** [comment]
Similar case with gradle in #129

**Comment by snicoll** [comment]
Another user [got caught by that one](https://jira.spring.io/browse/SPR-13682) with a very nasty (and hard to track) side effect so we should really fix this one.

**Comment by dsyer** [comment]
I never had a problem with a project generated from start.spring.io. Do you have an example of a curl request that generates a bad one?

**Comment by snicoll** [comment]
Add `web` and `config-client` with `1.2.7.RELEASE` then run `mvn dependency:list -Dsort`

```
[...]
[INFO]    org.springframework:spring-aop:jar:4.1.6.RELEASE:compile
[INFO]    org.springframework:spring-beans:jar:4.1.6.RELEASE:compile
[INFO]    org.springframework:spring-context:jar:4.1.6.RELEASE:compile
[INFO]    org.springframework:spring-core:jar:4.1.8.RELEASE:compile
[INFO]    org.springframework:spring-expression:jar:4.1.6.RELEASE:compile
[INFO]    org.springframework:spring-test:jar:4.1.6.RELEASE:test
[INFO]    org.springframework:spring-web:jar:4.1.6.RELEASE:compile
[INFO]    org.springframework:spring-webmvc:jar:4.1.6.RELEASE:compile
[INFO]    org.yaml:snakeyaml:jar:1.14:compile
```

**Comment by dsyer** [comment]
OK so this:

```
$ curl start.spring.io/pom.xml -d style=web -d style=cloud-config-client
```

**Comment by snicoll** [comment]
right now, yes but since it uses the default version you may want to add `-d bootVersion=1.2.7.RELEASE`
