### ISSUE TITLE
@ConditionalOnBuildSystem fails to locate bean ProjectDescription

### ISSUE THREAD

**Issue by mmoayyed** [spring-io/initializr#1166]
## Problem

Given the following configuration class:

```java
@ProjectGenerationConfiguration
@ConditionalOnBuildSystem(CasOverlayBuildSystem.ID)
public class CasOverlayProjectGenerationConfiguration {   
}
```

...and the following spring.factories file:

```
io.spring.initializr.generator.project.ProjectGenerationConfiguration=\
	org.apereo.cas.config.CasOverlayProjectGenerationConfiguration
io.spring.initializr.generator.buildsystem.BuildSystemFactory=\
	org.apereo.cas.overlay.buildsystem.CasOverlayBuildSystemFactory
```

Spring Initializr `0.9.2` produces the following error on startup:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

A component required a bean of type 'io.spring.initializr.generator.project.ProjectDescription' that could not be found.


Action:

Consider defining a bean of type 'io.spring.initializr.generator.project.ProjectDescription' in your configuration.


Process finished with exit code 1
```

It seems as though the configuration class is initialized eagerly on startup, rather than on demand when the project is requested.

## Reproduce

```
git clone https://github.com/mmoayyed/initializr-sample .
./gradlew bootRun 
```

**Comment by snicoll** [comment]
`CasOverlayInitializrApplication` is a `@SpringBootApplication` and will enable classpath scanning for the app. On startup, it will find `CasOverlayProjectGenerationConfiguration` and process it in the root context (not the project generation context).

The javadoc of `ProjectGenerationConfiguration` states:

> @ProjectGenerationConfiguration-annotated types should not be processed by the main ApplicationContext so make sure regular classpath scanning is not enabled for packages where such configuration classes reside.

**Comment by mmoayyed** [comment]
Thanks for the note, @snicoll.
