### ISSUE TITLE
How can I create a new project using kotlin and groovy as the gradle lang?

### ISSUE THREAD

**Issue by PaoloTorregroza** [spring-io/initializr#1171]
I'm trying to start a new project with kotlin, but if I select Kotlin as the language the gradle scripts are also wrote in kotlin

**Comment by wilkinsona** [comment]
We don't support generating Kotlin projects that use Gradle and its Groovy DSL as we don't want to complicate things with another option in the UI. See https://github.com/spring-io/initializr/issues/1069 for some more details.
