### ISSUE TITLE
Use 'Toolchains for JVM projects' of Gradle 6.7+

### ISSUE THREAD

**Issue by KENNYSOFT** [spring-io/initializr#1187]
Gradle 6.7 introduced 'Toolchains for JVM projects'.

Reference: https://docs.gradle.org/6.8.2/userguide/toolchains.html

So my suggestion is changing `sourceCompatibility` to:

```groovy
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(generation)
    }
}
```

https://github.com/spring-io/initializr/blob/835f69986cf7c09246ebdfd33478a70c411910de/initializr-generator/src/main/java/io/spring/initializr/generator/buildsystem/gradle/GroovyDslGradleBuildWriter.java#L89-L92

https://github.com/spring-io/initializr/blob/8cef356bcf1f28033077f767bc78cab36fd10d89/initializr-generator/src/main/java/io/spring/initializr/generator/buildsystem/gradle/KotlinDslGradleBuildWriter.java#L83-L86

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but I don't think we should do this. Using Gradle's Toolchain support may result in it attempting to download a JDK to meet the project's needs. That's something that may not always be desirable and in some organisations it wouldn't be permitted. I think it's better if we leave it as an opt-in.

Let's see what the rest of the team thinks.

**Comment by KENNYSOFT** [comment]
Cool, I think it will also be great if the feature added as opt-in. Thanks for your reply.

**Comment by wilkinsona** [comment]
To be clear, I meant an opt-in once the project has been generated. We certainly won't add it as an option when generating a project as we don't want to overwhelm users with too much choice. We'll either implement it for all Gradle projects or it'll be a change that you can make yourself once the project has been generated.

**Comment by KENNYSOFT** [comment]
Ok I see.

**Comment by snicoll** [comment]
As Andy mentioned, we really need to add what is strictly necessary out-of-the-box and let users complete their build with additional options if necessary. Thanks for the suggestion, in any case.

**Comment by tryfilter** [comment]
I come to this issue from a broken Java 21 project (Gradle 8.4):
    Project: Gradle - Groovy
    Language: Java
    Spring Boot: 3.1.5
    Java: 21
Running ./gradlew build on a project generated by this config fails with
"Execution failed for task ':compileJava'.
> error: invalid source release: 21".

I don't follow the reasoning provided for declining this issue: from what I can tell, automatically downloading JDKs is [opt-in](https://docs.gradle.org/current/userguide/toolchains.html#sec:provisioning) from Gradle's POV. A toolchain download repository must be explicitly configured for any download to happen. I would argue that if such a repository is added to the config by the user, their intention is clear.  
The Gradle docs do explicitly [say](https://docs.gradle.org/current/userguide/java_plugin.html#toolchain_and_compatibility) that toolchains are generally preferred over `sourceCompatibility` and `targetCompatibility` and the above failure is one possible reason why.  

My use case is admittedly somewhat niche as it should disappear when Gradle 8.5 is released, but I wanted to add another vote for toolchain support in favor of the current sourceCompatibility approach.

**Comment by snicoll** [comment]
> My use case is admittedly somewhat niche as it should disappear when Gradle 8.5 is released

That, and I am not sure you should get that issue in the first place. It looks like your shell is not using Java 21. What does `./gradlew --version` output?

**Comment by tryfilter** [comment]
You are correct, my shell was using Java 17.
I assumed this was not the only problem since Gradle [claims](https://docs.gradle.org/8.4/release-notes.html#support-for-building-projects-with-java-21) that 8.4 does not yet support running on Java 21 (and IntelliJ was reporting errors along the lines of "JDK 21.0.1 isn't compatible with Gradle 8.4").
But it seems like Gradle 8.4 runs on Java 21 just fine (making Gradle run on Java 21 fixed the error).
Thank you.
