### ISSUE TITLE
Integration tests won't be run, even with -P smokeTests

### ISSUE THREAD

**Issue by MarkyMarkMcDonald** [spring-io/initializr#119]
The current configuration looks for Java files instead of groovy files for tests. I tried swapping the patterns over to be file agnostic (e.g. `**/*SmokeTests*`), but couldn't get the tests to run (`org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms.`). I'm hoping this is just a "fails on my machine" problem, or that someone with more context on the project knows how to get these tests up and running quickly.

Here's the current config for reference:
``` xml
<profile>
			<id>smokeTests</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
						<executions>
							<execution>
								<id>integration-test</id>
								<phase>integration-test</phase>
								<goals>
									<goal>test</goal>
								</goals>
								<configuration>
									<includes>
										<include>**/*SmokeTests.java</include>
									</includes>
									<excludes>
										<exclude>**/Abstract*.java</exclude>
									</excludes>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
```

**Comment by snicoll** [comment]
works for me. You need to have a default Firefox installation on your box.
