### ISSUE TITLE
NPE with SaganInitializrMetadataUpdateStrategy and empty initializr.env.spring-boot-metadata-url

### ISSUE THREAD

**Issue by yisiliang** [spring-io/initializr#1211]
if we configured the initializr.env.spring-boot-metadata-url as empty.
The io.spring.initializr.web.support.SaganInitializrMetadataUpdateStrategy.fetchSpringBootVersions function will return null.

```
	protected List<DefaultMetadataElement> fetchSpringBootVersions(String url) {
		if (StringUtils.hasText(url)) {
			try {
				logger.info("Fetching Spring Boot metadata from " + url);
				return new SpringBootMetadataReader(this.objectMapper, this.restTemplate, url).getBootVersions();
			}
			catch (Exception ex) {
				logger.warn("Failed to fetch Spring Boot metadata", ex);
			}
		}
		return null;
	}
```

But the invoker does not check the result is null or not.

```
	@Override
	protected List<DefaultMetadataElement> fetchSpringBootVersions(String url) {
		List<DefaultMetadataElement> versions = super.fetchSpringBootVersions(url);
		return versions.stream().filter(this::isCompatibleVersion).collect(Collectors.toList());
	}

```

And the NullPointerException will be thrown.
```
java.lang.NullPointerException
	at io.spring.start.site.support.StartInitializrMetadataUpdateStrategy.fetchSpringBootVersions(StartInitializrMetadataUpdateStrategy.java:47)
	at io.spring.initializr.web.support.SaganInitializrMetadataUpdateStrategy.update(SaganInitializrMetadataUpdateStrategy.java:54)
	at io.spring.initializr.web.support.DefaultInitializrMetadataProvider.get(DefaultInitializrMetadataProvider.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by snicoll** [comment]
Thanks for the report. Sagan metadata is optional, if you don't want update to happen please do not configure the `SaganInitializrMetadataUpdateStrategy` at all as it's only purpose is to use ` initializr.env.spring-boot-metadata-url` to refresh the versions. In your case, not configuring anything will disable this behavior.

**Comment by yisiliang** [comment]
Thank you.
But I want to hosted the application in the intranet, and the application can not access internet.

**Comment by snicoll** [comment]
I understood that. Do not configure `SaganInitializrMetadataUpdateStrategy` at all is what I suggesting as it won't do any external calls. What version of Initializr are you using? Perhaps you're on an older version where it's configured automatically? You can override that rather than hacking the metadata url (or upgrade to a more recent versio).

**Comment by snicoll** [comment]
I just saw your PR and realized the problem you're referencing is not in this code base so I am going to close this one. If you've cloned start.spring.io, you should remove the bean rather than hacking the metadata url.

**Comment by yisiliang** [comment]
> I just saw your PR and realized the problem you're referencing is not in this code base so I am going to close this one. If you've cloned start.spring.io, you should remove the bean rather than hacking the metadata url.

OK, Thank you.
