### ISSUE TITLE
How do I add a custom property to initializRProperties

### ISSUE THREAD

**Issue by fm-19** [spring-io/initializr#1212]
example：

```yaml
initializr:
  demo:
    - name: aa
 ```

demo type MetadataElement

**Comment by snicoll** [comment]
@fm-19 You can't sub-class the metadata and expect it to work in all clients as the metadata is versioned and clients expect a given format and content.

you'll have to tell us more about what you're trying to do.

**Comment by fm-19** [comment]
Access '/metadata/client' to add custom options to the original return
```
demo: {
        type: "single-select",
        default: "demo-1",
        values: [
            {
                id: "demo-1",
                name: "demo-1"
            },
            {
                id: "demo-2",
                name: "demo-2"
            }
        ]
    }
```

**Comment by snicoll** [comment]
Thanks  for following-up. As I'[ve noted previously](https://github.com/spring-io/initializr/issues/1212#issuecomment-811807626), custom types are not supported out-of-the-box as it would break the metadata format.

Rather than some fake data, would you be able to provide more information about your use case?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
