### ISSUE TITLE
MavenRepository should explicitely set whether release and snapshots are enabled

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#1226]
The default for `releases.enabled` and `snapshots.enabled` are both true (see https://stackoverflow.com/questions/61684312/in-a-maven-repository-entry-in-the-pom-are-snapshots-enabled-by-default). 

Right now, our API is such that releases are enabled by default (with no way to turn that off) and snapshots are disabled by default. We could keep drifting from those defaults but we should at least make sure they're properly applied in generated poms.

**Comment by sdeleuze** [comment]
For the record, [here](https://github.com/spring-projects-experimental/spring-native/blob/be0c7856170fb4275cb86b74b7873d19a30a41ae/pom.xml#L254-L282) is what we configured in Spring Native with the goal of preventing downloads of snapshot dependencies from `releases` repositories and of release dependencies from `snapshots` repositories.
