### ISSUE TITLE
 A way to lookup spring configuration properties

### ISSUE THREAD

**Issue by arvindkgs** [spring-io/initializr#1230]
It would be helpful to have simple form with a single input text field to search for spring properties and it's definitions. 

> For example, if I want to know if there is `timeout` on spring cloud stream producer while connecting to kafka, then I search for `spring cloud stream timeout` and the form does a fuzzy search and returns and matching entries.

> Would also help to have a tree structure

**Comment by snicoll** [comment]
Thanks for the suggestion but this project focuses on creating a project with different opinions, not providing a way to figure out if a given property is exposed by one of the projects. Your IDE to a large extent already does that on a generated project.
