### ISSUE TITLE
Cannot download 'https://start.spring.io': Request failed with status code 403

### ISSUE THREAD

**Issue by springapidev** [spring-io/initializr#1248]
Today I can not create new Spring Boot Initialize project, Here is screenshot.
![boot_issue](https://user-images.githubusercontent.com/21154929/124348947-9d33c280-dc0e-11eb-825b-d312f0846e29.png)

Please check and fix.

With Best Regards

Rajaul

**Comment by snicoll** [comment]
Make sure to use https, we don't accept traffic on http. 

Before creating an issue here, please consider trying another client, like your browser.

**Comment by springapidev** [comment]
I think, issue was at site, now I see, issue has been fixed in my IDE.

Thanks.
