### ISSUE TITLE
Upgrade dependency-management-plugin to 0.5.2

### ISSUE THREAD

**Issue by criesbeck** [spring-io/initializr#126]
Initializr generates 

        classpath("io.spring.gradle:dependency-management-plugin:0.5.1.RELEASE")

which cause `gradle wrapper` to get a build failure. Works if edited to 0.5.2.

**Comment by snicoll** [comment]
Works for me so I guess you did upgrade gradle locally maybe? In any case, it's done and pending a push on CI. Thanks for the report!

**Comment by criesbeck** [comment]
Bad timing on my part. I installed gradle Monday and tried Initializr Tuesday, and got an error similar to the one [here] (https://github.com/spring-projects/spring-boot/issues/3334).

**Comment by snicoll** [comment]
Right. Thanks for the reply.
