### ISSUE TITLE
Support for compileOnly dependencies

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#128]
The new devtools could use to have an `<optional>true</optional>` entry as it shouldn't ship with the actual app by default.

Provided scope is not managed properly in Intellij IDEA so that's not a great candidate unfortunately (and the semantic would be wrong anyway).

**Comment by dsyer** [comment]
I guess that means we have to have an answer to the question "what does 'optional' mean for a gradle dependency?". Refs: https://issues.gradle.org/browse/GRADLE-1749, https://github.com/nebula-plugins/gradle-extra-configurations-plugin.

**Comment by snicoll** [comment]
We [already have a plugin of our own that does that](https://github.com/spring-projects/gradle-plugins/tree/master/propdeps-plugin) and we use it in the Spring Framework build so all it takes really is integrating the plugin in the gradle build when an optional and/or provided dependency is added to the project

**Comment by snicoll** [comment]
OK so I've started to work on this. We have 3 cases at this point:

* Lombok (annotation processor)
* The Spring Boot configuration processor (ditto)
* Devtools

We can deal with all these with "optional" in Maven. And ignore Gradle but the first two could be handled with the new `compileOnly` thing in Gradle. I am not sure that devtools will work (and even if it did, it's a bit weird).

@wilkinsona any insight?

**Comment by wilkinsona** [comment]
`compileOnly` is perfect for annotation processors. It won't work for DevTools as `compileOnly` dependencies aren't on the class path at runtime.
