### ISSUE TITLE
Document how to configure Kotlin version resolution

### ISSUE THREAD

**Issue by srinivasvsk** [spring-io/initializr#1280]
Hello,
i tried to follow the latest documentation and the sample project. When i try to generate a kotlin project, it is erroring out with missing mapping for spring boot 2.5.6 with kotlin.  Could you point to where the mapping can be configured and also if there is a way to just extend the whole configuration that would be great. Not able to find that information in docs

`io.spring.initializr.metadata.InvalidInitializrMetadataException: No Kotlin version mapping available for 2.5.6.RELEASE
	at io.spring.initializr.metadata.InitializrConfiguration$Env$Kotlin.resolveKotlinVersion(InitializrConfiguration.java:424) ~[initializr-metadata-0.11.1.jar:na]
	at io.spring.initializr.generator.spring.code.kotlin.InitializrMetadataKotlinVersionResolver.resolveKotlinVersion(InitializrMetadataKotlinVersionResolver.java:39) ~[initializr-generator-spring-0.11.1.jar:na]
	`

**Comment by wilkinsona** [comment]
start.spring.io uses a custom `KotlinVersionResolver` bean for this purpose: https://github.com/spring-io/start.spring.io/blob/a82ad12ca1ed372b4d95d9a092d41bf63ece9f1e/start-site/src/main/java/io/spring/start/site/extension/code/kotlin/ManagedDependenciesKotlinVersionResolver.java.

You can either define your own bean or update your `application.yaml` file to declare some mappings beneath `initializr.env.kotlin.mappings`.

**Comment by srinivasvsk** [comment]
thank you for the details!
