### ISSUE TITLE
Divide initializr-generator-spring into two modules, one for its API and one for its @Configuration classes

### ISSUE THREAD

**Issue by EightMonth** [spring-io/initializr#1283]
hi spring team
thanks for open source initializr, that's gold for me. the code style is so beautiful, the code design is so wonderful. Gives me a lot of learning space，thanks again.
but i have a issue.Is it possible to add @ConditionalOnMissingBean to the default project contributor.

my English is so poor, forgive me .
Best Regards
eightmonth

**Comment by wilkinsona** [comment]
If you don't want the defaults, have you considered not using the `initializr-generator-spring` module? If you'd lose too much taking that approach, perhaps you can describe what you'd like to be able to override.

**Comment by EightMonth** [comment]
thanks for reply

first the JavaProjectGenerationDefaultContributorsConfiguration.mainMethodContributor() default use SpringApplication as ApplicationStarter but I have extends class by SpringApplication. i want to replace it.

second the DefaultStarterBuildCustomizer. perhaps this is unnecessary without dependency

**Comment by wilkinsona** [comment]
As currently implemented, we can't make `mainMethodContributor` `@ConditionalOnMissingBean`. Existing users may be defining their own `MainApplicationTypeCustomizer` that adds to the code created by the default customizer. If it was `@ConditionalOnMissingBean` that default customizer's code would be lost and the additions would no longer work.

As things stand, I think your best option is not to use `initializr-generator-spring`. Instead, you should just copy the parts of it that you want to use into your own codebase.

**Comment by EightMonth** [comment]
Thanks for your advice

**Comment by wilkinsona** [comment]
Something that we could do to help with this sort of requirement is to split the Spring module into two pieces. The first would provide all of the customisers and contributors and the second would provide the configuration classes that creates the default arrangement. Anyone wanting complete control could then use the first module on its own. This is somewhat analogous to Spring Boot's `spring-boot-actuator` and `spring-boot-actuator-autoconfigure` modules.

**Comment by EightMonth** [comment]
if it can be implemented, it will be very welcome

**Comment by snicoll** [comment]
@EightMonth please do not close this issue.

**Comment by EightMonth** [comment]
If you do not wanna enhance the issue，please close it. the issue is opening two years！

**Comment by snicoll** [comment]
Unfortunately, we don't have unlimited resources and we have to process issues based on priority. We've identified this issue as an improvement to the project but couldn't get to it yet.

**Comment by EightMonth** [comment]
Unfortunately！i also do not want this keep stay in my issue list any more！
