### ISSUE TITLE
Generating a Gradle Kotlin project that uses DevTools with spring boot dependency management plugin won't work without workaround.

### ISSUE THREAD

**Issue by bgvit** [spring-io/initializr#1291]
Hi. This problem was mentioned in theses tickets:

- https://github.com/spring-projects/spring-boot/issues/16251
- https://github.com/spring-io/initializr/issues/917

Although it was fixed in these links, my case is a little bit different. I am using the spring boot dependency management in order to manage the version using BOM and I noticed that this problem have appeared. When I try to compile, gradle throws this error:

`developmentOnly("org.springframework.boot:spring-boot-devtools") ^`

I resolved this using the solution mentioned in one of those links:

/*Workaround used to make devolpmentOnly works. I think that is a bug */
`val developmentOnly = configurations.create("developmentOnly")
configurations.runtimeClasspath.get().extendsFrom(developmentOnly)
`

But, I came here to report. 

- Here is my build.gradle.kts:

`import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

val projectVersion: String by ext
val groupPath: String by ext
val springBootStarterVersion: String by ext
val kotlinVersion : String by ext
val kotlinxCoroutinesVersion : String by ext

java.sourceCompatibility = JavaVersion.VERSION_11
java.targetCompatibility = JavaVersion.VERSION_11

plugins {
	id("org.springframework.boot") version "2.6.2" apply false
	id("io.spring.dependency-management") version "1.0.11.RELEASE"
	kotlin("jvm") version "1.6.10"
	kotlin("plugin.spring") version "1.6.10"
	idea
}

group = groupPath
version = projectVersion
java.sourceCompatibility = JavaVersion.VERSION_11

allprojects {
	version = projectVersion
	repositories {
		mavenCentral()
	}
}

subprojects {
	apply {
		plugin("kotlin")
		plugin("kotlin-kapt")
		plugin("io.spring.dependency-management")
		plugin("kotlin-spring")
		plugin("idea")
	}
}

dependencyManagement {
	imports {
		mavenBom("org.springframework.boot:spring-boot-dependencies:$springBootStarterVersion")
		mavenBom("org.springframework.boot:spring-boot-starter-parent:$springBootStarterVersion")
	}
	dependencies {
		dependency("org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:$kotlinxCoroutinesVersion")
		dependency("org.jetbrains.kotlinx:kotlinx-coroutines-core:$kotlinxCoroutinesVersion")
		dependency("org.jetbrains.kotlinx:kotlinx-coroutines-reactor:$kotlinxCoroutinesVersion")
		dependency("org.jetbrains.kotlinx:kotlinx-coroutines-slf4j:$kotlinxCoroutinesVersion")
		dependency("org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion")
		dependency("org.jetbrains.kotlin:kotlin-reflect:$kotlinVersion")
	}
}
/**/
// Workaround used to make devolpmentOnly works. I think that is a bug
val developmentOnly = configurations.create("developmentOnly")
configurations.runtimeClasspath.get().extendsFrom(developmentOnly)

dependencies {
	implementation("org.springframework.boot:spring-boot-starter-webflux")
	implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
	implementation("io.projectreactor.kotlin:reactor-kotlin-extensions")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
	implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactor")
	developmentOnly("org.springframework.boot:spring-boot-devtools")
	testImplementation("org.springframework.boot:spring-boot-starter-test")
	testImplementation("io.projectreactor:reactor-test")
}

tasks.withType<KotlinCompile> {
	kotlinOptions {
		freeCompilerArgs = listOf("-Xjsr305=strict")
		jvmTarget = "11"
	}
}

tasks.withType<Test> {
	useJUnitPlatform()
}
`

And my gradle.properties:

groupPath=br.teste
projectVersion=0.0.1-SNAPSHOT
springBootStarterVersion=2.6.2
kotlinVersion=1.6.10
kotlinxCoroutinesVersion=1.4.2

**Comment by snicoll** [comment]
@bgvit I don't understand why you're reporting this against Spring Initializr, this is nowhere near a build that start.spring.io or a vanilla Spring Initializr instance would produce.

**Comment by bgvit** [comment]
Ok, I understand. You're right, sorry for this. I think it's better to report this on https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/

I'll close this ticket. Thanks for reply.
