### ISSUE TITLE
Add extensions section to Maven projects

### ISSUE THREAD

**Issue by herder** [spring-io/initializr#1303]
We are running a fork of this project to be able to add an `extensions` section to the Maven project, and it would be fantastic if this feature could be added to this project so that we can follow the mainline.

I have created a PR to add this in #1290 , if you have time to take a look?

Thanks!

**Comment by wilkinsona** [comment]
We'd seen the PR but, unfortunately, haven't had time to look at in detail as we have a number of other higher priority things taking up all of our time at the moment. Thanks for your patience until we get a time to look at it properly.
