### ISSUE TITLE
Include an appropriately configured .gitignore file in the generated project

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/initializr#131]
One of the first things I do after generating a project is to create an appropriately configured `.gitignore` file for it. What goes in the file is build system specific. For Gradle projects, I'd like `.gradle`, `build`, and `bin` (thanks, Eclipse) to be ignored by default. For Maven projects, I'd like `target` to be ignored by default.

I realise that this is VCS specific, so perhaps it shouldn't be switched on by default, although I suspect that the vast majority of people will be using Git these days.

**Comment by mikegehard** [comment]
Great find @wilkinsona.

I had this same thought today so I am going to +1 this.

I agree that is is VCS dependent but the gradle generator already includes a gradle.bat file that most people will delete shortly after unzipping so why not include a .gitignore and if people aren't using Git they can delete it as well.

**Comment by spencergibb** [comment]
Could use https://www.gitignore.io

**Comment by cy6erGn0m** [comment]
The issue with this approach is that the generator couldn't guess which IDE do you use so you will need to genrate/modify .gitignore anyway

**Comment by dsyer** [comment]
I'd be happy to ignore the IDE I wasn't using. All Spring projects have eclipse and intellij ignores already.

**Comment by shakuzen** [comment]
+1 and I agree it's fine to ignore both Eclipse and IntelliJ specific files.

**Comment by KyleChamberlin** [comment]
really ignoring swap files for vim, bak file from notepad++, build files for gradle, build files for maven, and Eclipse and IntelliJ seems perfectly fine, even if you aren't using any of those, it seems pretty unlikely that it would be ignoring files you need using a different tool set.
