### ISSUE TITLE
Add the Maven Wrapper debug scripts

### ISSUE THREAD

**Issue by breun** [spring-io/initializr#1310]
https://maven.apache.org/wrapper/maven-wrapper-plugin/usage.html says:

> The apache-maven-wrapper distributions all contains the `mvnwDebug`-script for both Windows and Unix based operating systems. This makes it possible to debug through Apache Maven, Maven Plugin or Maven Extension. You can exclude these scripts by calling `mvn wrapper:wrapper -DincludeDebug=false`

When I run `mvn wrapper:wrapper -Dmaven=3.8.5` on a project, I indeed get `mvnwDebug` and `mvnwDebug.cmd`, but Spring Initializr doesn't create these files by default, only the non-debug scripts. Could the debug ones also be generated by default? They are very handy when you need to debug an issue which occurs during a Maven run, for instance in some Maven plugin.

**Comment by snicoll** [comment]
@breun thanks for the suggestion but I don't think we should ship these by default. If you need them you can run the command above.

**Comment by breun** [comment]
Maven Wrapper adds these debug scripts by default now, so I thought it would make sense to have the same default for projects generated by Spring Initializr. They’re also pretty small scripts if that makes any difference. They’re basically one-liners (plus comments).

**Comment by wilkinsona** [comment]
Aligning with what Maven generates by default makes sense to me. I'll flag this for team attention so that we can consider it again.

**Comment by mhalbritter** [comment]
The default has been flipped, it now must be included explicitly:

```
mvn wrapper:wrapper -DincludeDebug=true
```
