### ISSUE TITLE
Group cloud support by technology/vendor

### ISSUE THREAD

**Issue by mdeinum** [spring-io/initializr#132]
Currently the list of supported cloud technologies is growing. For clarity it might be useful to add a sub group (or multiple cloud groups) for different vendors/technologies (AWS, CloudFoundry, Netflix) etc. the list is becoming quite large.

**Comment by dsyer** [comment]
cc @joshlong because we were talking about this OOB already

**Comment by snicoll** [comment]
Yeah well, I want to add multi hierarchical support for quite some time now. This needs to be taken into account meta-data wise as it's probably going to be a breaking change. 

If we break it, I'd rather implement a few extra ideas I have in mind.

**Comment by dsyer** [comment]
I was thinking more like we'd just break up the "Cloud" group into multiple "Cloud *" groups. That's easy and it works now.

**Comment by mdeinum** [comment]
That would at least clarify/cleanup things. Something like (Cloud - AWS and Cloud - Netflix etc.) without breaking anything. Breaking things api wise might also break tool support in STS and Intellij (not sure just a thought).

**Comment by snicoll** [comment]
I see. It won't break anything  as we manage a version for meta-data so if the IDE is asking for meta-data V2 we'll just send a hierarchy with one level as we're doing now. We still support the very first implementation done in STS that is parsing the HTML ;)

Anyway. we can apply this simple solution right the way, I am all for it. Dave, you want me to do it?

**Comment by mdeinum** [comment]
@snicoll  After looking at the sources that is what I noticed, nice usage of versioned content types :+1: .

**Comment by dsyer** [comment]
Josh wanted to think about using "functional" groups instead of "vendor" groups (e.g. "Cloud Discovery"). I think we should consider that as well before doing anything.

**Comment by spring-operator** [comment]
Hurray nice work

On Tuesday, October 6, 2015, Dave Syer <notifications@github.com> wrote:

> Closed #132 <https://github.com/spring-io/initializr/issues/132> via
> 42f2c2f
> <https://github.com/spring-io/initializr/commit/42f2c2f6b7edd173f569fbbfb051c997611b4980>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spring-io/initializr/issues/132#event-427727543>.
>


-- 


Thanks,
Josh Long
Spring Developer Advocate
Pivotal
http://www.joshlong.com || joshlong.com || http://twitter.com/starbuxman
