### ISSUE TITLE
Option for Kotlin DSL + Java application

### ISSUE THREAD

**Issue by hanct** [spring-io/initializr#1320]
Hi,
    I notice that if I am to choose

1.   Gradle Project and Java Language, it uses groovy DSL for the gradle build, , but catered for java application
2.   Gradle Project and Kotlin Language, it uses kotlin DSL for the gradle build, but catered for kotlin-based application

Can we have an option that allow us to choose Kotlin DSL for the build, but catered for Java-based application??

**Comment by wilkinsona** [comment]
Duplicates https://github.com/spring-io/start.spring.io/issues/956.
