### ISSUE TITLE
REST API not respecting jvmVersion=11

### ISSUE THREAD

**Issue by moksamedia** [spring-io/initializr#1325]
When I use the `jvmVersion` flag in the REST API, the resulting Gradle file does not have the `sourceCompatibility` set to 11 and is set to 17 instead.

```bash
curl https://start.spring.io/starter.tgz \
  -d bootVersion=2.6.10 \
  -d jvmVersion=11 \
  -d dependencies=web,data-rest,lombok,data-jpa,h2,okta \
  -d type=gradle-project \
  -d baseDir=resource-server
```

**Comment by snicoll** [comment]
As stated by the output of `curl https://start.spring.io` the property is `javaVersion`, not `jvmVersion`. See also https://github.com/spring-io/initializr/issues/958

**Comment by moksamedia** [comment]
Ah. Thanks.
