### ISSUE TITLE
Invalid dependency when open by shared url.

### ISSUE THREAD

**Issue by dbses** [spring-io/initializr#1326]
When open shared url of https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.6.11&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=solace, the dependency is invalid.

However, when I click on the spring boot version of 2.6.11, the dependency becomes valid.

I think it's a bug

**Comment by snicoll** [comment]
Please do not cross-post. Duplicate https://github.com/spring-io/start.spring.io/issues/984
