### ISSUE TITLE
Add Hazelcast as a Data option from Boot 1.3.0.M5

### ISSUE THREAD

**Issue by shakuzen** [spring-io/initializr#133]
Since 1.3.0.M5 added auto-configuration for Hazelcast in general, it should be available as an option from the Data category like Redis and others are now.

**Comment by snicoll** [comment]
We don't add options for single dependency (database being the only exception to the rule). There is no `spring-boot-starter-hazelcast` and I don't see any reason to add one. 

(There's also a bunch of libraries that Spring Boot support that are not listed here).
