### ISSUE TITLE
Add open liberty to Spring Initializer

### ISSUE THREAD

**Issue by gitexp2050** [spring-io/initializr#1331]
Is it possible to add openliberty support in https://start.spring.io/ and also provide provision for embedded server switch for spring boot application? Need to start with development of a spring boot application. On search found openliberty was a good one to choose but the above are missing.

Also, if possible, one demo application with source code which has spring boot with open liberty

https://openliberty.io/

**Comment by wilkinsona** [comment]
We don't offer any "web server" options on start.spring.io, even for the embedded servers that Spring Boot supports (Jetty, Tomcat, and Undertow). If you want to develop a Spring Boot application and deploy it to OpenLiberty, you should choose war packaging.

**Comment by gitexp2050** [comment]
Can you please add the OpenLibery and Quarkus as embedded server option in Spring Boot like Jetty/Tomcat/Undertow if it is not a hard one. Many started using OpenLiberty and Quarkus and wanted to built app with Spring Boot. Even it is there in initializer it would easy to train people or develop.

**Comment by wilkinsona** [comment]
I'm afraid that doesn't make sense. Quarkus is an alternative to Spring Boot, not something that can be used as an embedded server within Spring Boot. And, as I said above, to use OpenLiberty and Spring Boot together, you should package your Spring Boot application as a war file and deploy it to OpenLiberty.

**Comment by gitexp2050** [comment]
I understand your concern now, Quarkus s an alternative to spring boot..How about OpenLiberty can it be added or it is also an alternative to Spring Boot
