### ISSUE TITLE
Add Quarkus to Spring Initializer 

### ISSUE THREAD

**Issue by gitexp2050** [spring-io/initializr#1332]
Is it possible to add Quarkus support in https://start.spring.io/ and also provide provision for embedded server switch for spring boot application? Need to start with development of a spring boot application. On search found quarkus was a good one to choose but the above are missing.

Also, if possible, one demo application with source code which has spring boot with quarkus

https://quarkus.io/

**Comment by wilkinsona** [comment]
Thanks for the suggestion, but there's no support for Quarkus in Spring so it's out of scope for start.spring.io.

**Comment by gitexp2050** [comment]
@wilkinsona I think you are not looked into Quarkus. Please kindly have a look at the image. Please kindly add the support.

![image](https://user-images.githubusercontent.com/115112320/195414365-d9d5a135-a639-4004-a850-f12ba5d905da.png)

**Comment by wilkinsona** [comment]
This is Quarkus' support for Spring, that is to say it's part of Quarkus. As such code.quarkus.io is the correct (and only) place for it.

**Comment by gitexp2050** [comment]
I thought Quarkus provides support, similar kind of support can be given in spring initializer as we would be using Quarkus and Intern Spring as well.
