### ISSUE TITLE
Unuable to generate Maven Project with Spring initializr

### ISSUE THREAD

**Issue by natalia-pokrovskaya** [spring-io/initializr#1338]
Hello!

I'm unable to generate a new Maven project with spring initializr with following configuration:
* Maven Projec
* Java
* Spring boot 2.7.5
OS: MacOS Monterey 12.6
Browser: Safari, Chrome, Firefox, Edge

Gradle projects generation is OK.
For Maven project, downloaded zip file is broken and when I'm trying to "Explore", I'm getting "Could not load the ZIP project" error.

Thank you in advance for you help!

Best regards,
Natalia

**Comment by wilkinsona** [comment]
It's working fine for me. Can you please use the Share button on https://start.spring.io to get a URL for your exact configuration and paste it here?

**Comment by natalia-pokrovskaya** [comment]
yes, sure, here it is for Java 17
https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.7.5&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo

And the same issue for Java 11
https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.7.5&packaging=jar&jvmVersion=11&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo

**Comment by natalia-pokrovskaya** [comment]
The GET request fails with error 307

```
URL de la demande: https://start.spring.io/starter.zip?type=maven-project&language=java&bootVersion=2.7.5&baseDir=demo&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&packaging=jar&javaVersion=11
Méthode de demande: GET
Code d’état: 307 
Adresse distante: 10.60.168.135:8080
Stratégie de point d’accès: strict-origin-when-cross-origin

Response headers;
location: https://start.spring.io/mwg-internal/de5fs23hu73dt/progress?id=rhCf_E80Dv5tQQlSQB_VzIdEdPF9_3Krh8tAtgeOafg,
```

**Comment by wilkinsona** [comment]
Thank you. Those URLs both work fine for me in my browser. I can curl the other URL too:

```
$ curl -s https://start.spring.io/starter.zip?type=maven-project&language=java&bootVersion=2.7.5&baseDir=demo&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&packaging=jar&javaVersion=11 > starter.zip
$ unzip -l starter.zip 
Archive:  starter.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  10-21-2022 14:29   demo/
     6734  10-21-2022 14:29   demo/mvnw.cmd
    10284  10-21-2022 14:29   demo/mvnw
     1222  10-21-2022 14:29   demo/pom.xml
        0  10-21-2022 14:29   demo/.mvn/
        0  10-21-2022 14:29   demo/.mvn/wrapper/
      233  10-21-2022 14:29   demo/.mvn/wrapper/maven-wrapper.properties
    58727  10-21-2022 14:29   demo/.mvn/wrapper/maven-wrapper.jar
        0  10-21-2022 14:29   demo/src/
        0  10-21-2022 14:29   demo/src/main/
        0  10-21-2022 14:29   demo/src/main/resources/
        1  10-21-2022 14:29   demo/src/main/resources/application.properties
        0  10-21-2022 14:29   demo/src/main/java/
        0  10-21-2022 14:29   demo/src/main/java/com/
        0  10-21-2022 14:29   demo/src/main/java/com/example/
        0  10-21-2022 14:29   demo/src/main/java/com/example/demo/
      305  10-21-2022 14:29   demo/src/main/java/com/example/demo/DemoApplication.java
        0  10-21-2022 14:29   demo/src/test/
        0  10-21-2022 14:29   demo/src/test/java/
        0  10-21-2022 14:29   demo/src/test/java/com/
        0  10-21-2022 14:29   demo/src/test/java/com/example/
        0  10-21-2022 14:29   demo/src/test/java/com/example/demo/
      206  10-21-2022 14:29   demo/src/test/java/com/example/demo/DemoApplicationTests.java
      395  10-21-2022 14:29   demo/.gitignore
      429  10-21-2022 14:29   demo/HELP.md
---------                     -------
    78536                     25 files
```

When you try it, you're being temporarily redirected to `https://start.spring.io/mwg-internal/de5fs23hu73dt/progress?id=rhCf_E80Dv5tQQlSQB_VzIdEdPF9_3Krh8tAtgeOafg`. It looks like `mwg-internal` is McAfee Web Gateway and it's blocking the request somehow. This is a problem with your machine or the network to which your machine is connected. Perhaps you can get someone who maintains the gateway to add https://start.spring.io to an allow list?
