### ISSUE TITLE
Provide a frequently used section in the web UI

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/initializr#134]
Use local storage or a cookie to keep track of the projects that the user has selected in the past and display the top n (5? 10?) most-used projects in a frequently used section.

**Comment by snicoll** [comment]
I like that.

**Comment by snicoll** [comment]
I had a similar discussion with someone else (can't remember who right now) and we brainstormed about   fetching statistics from the redis instance to:

1. Create a list of frequently used starters (globally, not for the current user) and filtered (I believe AOP should not be that high on the list)
2. Create a list of frequent combinations (not based on live stats but updated from time to time based on a background analysis)

What do you think @wilkinsona? Is this a better solution from your perspective or should I create a  separate issue?

**Comment by wilkinsona** [comment]
I think there's merit in both approaches. Neither will be perfect so probably just need to pick one. The danger with a global list is that it'll bury any new projects and will probably never change as the most popular projects are pretty predictable. A user-specific list avoids that problem but has the problem that it's using a much smaller data set and will skew towards assuming that a particular user is always going to build the same kind of app.

Some options, in my order of preference:

1. Order based on the user's individual history
2. Leave things as they are now
3. Order based on the global history.

**Comment by snicoll** [comment]
We'd like to organize user interviews for this one.

**Comment by snicoll** [comment]
Alright let's close this one for now.
