### ISSUE TITLE
Push generated projects to GitHub

### ISSUE THREAD

**Issue by fangjian0423** [spring-io/initializr#1341]
hi, community.

I find there are some similar issues(https://github.com/spring-io/initializr/issues/63, https://github.com/spring-io/start.spring.io/issues/177) to discuss "Push to Github" feature.

For the https://github.com/spring-io/initializr/issues/63#issuecomment-430581120 and https://github.com/spring-io/initializr/issues/63#issuecomment-430605168, I have some different thoughts:

> While being able to go from a UI to a github project is nice for demoing CI/CD, we don't believe this is something our users are doing concretely. At the very least, I expect the user to actually implement something before pushing a first version.

[Github Codespaces](https://github.com/features/codespaces) could make users develop their codes in cloud any time. So I think generate github project firstly is very userful.

> If we push to github, it also means that we own the first commit on the repository which brings a potential compliance problem

The first commit with "Initial commit" commit message(or something better) looks good to me, I don't think it will bring potential compliance problems.

Actually, when creating a github repository on github dashboard, the first commit message also is "Initial commit".

> If we push code to Github, it is reasonable users expect to be able to chose a license for the code and we are not keen to add this extra complexity.

Now [Every developer and team can now get private repositories with unlimited collaborators at no cost with GitHub Free](https://github.blog/2020-04-14-github-is-now-free-for-teams/).

For private repositories, I think they don't care which license they use.

For public repositories, we could don't choose any licenses or choose a default license.

> I also think it justifies not investing in integration with public GitHub as it would only be of use to 9.6% of users.

Now we can include github private repository users.

Finally, I hope community could reconsider this feature, thanks!

**Comment by wilkinsona** [comment]
@fangjian0423 Please add your comments to #63 rather than splitting the discussion across two separate issues. If a compelling argument is made, #63 can be re-opened.
