### ISSUE TITLE
spring initializr sets `java.version` as 17 when generating for 8

### ISSUE THREAD

**Issue by liyi93319** [spring-io/initializr#1350]
Steps:

Here is the info to generate the codebase:

Project: Maven
Spring Boot: 3.0.0
Packaging: Jar
Java version: 8

![image](https://user-images.githubusercontent.com/43629316/203909452-9c278f09-4321-456b-8489-38681ee83662.png)

Expected: generate the codebase for Java 8

Actual result: generate the codebase for Java 17

**Comment by wilkinsona** [comment]
This is intentional as Spring Boot 3.0 requires Java 17. The is some information in the generated `HELP.md` that explains what has happened:

> ### Read Me First
>
> The following was discovered as part of building this project:
>
> - The JVM level was changed from '1.8' to '17', review the [JDK Version Range](https://github.com/spring-projects/spring- framework/wiki/Spring-Framework-Versions#jdk-version-range) on the wiki for more details.
