### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError -> SpringToolSuite4

### ISSUE THREAD

**Issue by AAdewunmi** [spring-io/initializr#1353]
**Hi,**

**I created a new SpringBoot project in SpringToolSuite4 and selected Java 11 as the perfered JDK.**

![Screenshot 2022-11-28 at 09 09 40](https://user-images.githubusercontent.com/15172744/204252238-16bdb158-14a1-4202-8695-1b1e8b43b136.png)

**However, Spring Initializr overrode my selection and created the project using Java 17.** 

![Screenshot 2022-11-28 at 09 12 16](https://user-images.githubusercontent.com/15172744/204252970-608e391f-4aae-44f5-bfa6-6770a4c50457.png)

**Running the project produces the following error:** 

`Exception in thread "main" java.lang.UnsupportedClassVersionError: org/springframework/boot/SpringApplication has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0`

![Screenshot 2022-11-28 at 09 23 56](https://user-images.githubusercontent.com/15172744/204241032-ce784f3e-e4a1-40c5-9179-a26f1380b71e.png)

**Overriding selected JDK; Is this a bug?**

**Comment by wilkinsona** [comment]
Spring Boot 3 requires Java 17. Please check the generated project's `HELP.md` file for details.

**Comment by AAdewunmi** [comment]
@wilkinsona thanks!

However, it would make sense to remove Java 19 / 11 / 8 from the UI, so users know Java 17 is the default. 

![Screenshot 2022-11-28 at 10 29 27](https://user-images.githubusercontent.com/15172744/204255361-042597be-c7c4-4f97-ae4e-1e0bd1dbce99.png)

**Comment by wilkinsona** [comment]
They can't be removed as they're supported with other versions of Spring Boot. https://github.com/spring-io/start.spring.io/issues/250 is tracking some improvements in this area.

**Comment by AAdewunmi** [comment]
Ok 👍
