### ISSUE TITLE
Change @Controller to @RestController

### ISSUE THREAD

**Issue by mbhave** [spring-io/initializr#1354]
It seems like the controllers in `initializr-web` can all be `@RestController`s. It would read better and avoid the need for `@ResponseBody` [here](https://github.com/spring-io/initializr/blob/89e59ddca76080e943b6fab773a3f68c7280a82d/initializr-web/src/main/java/io/spring/initializr/web/controller/ProjectMetadataController.java#L70).

**Comment by kamalkumar789** [comment]
Yes, we don't need to use @ResponseBody annotation if we are using @RestController because @RestController itself is assigned with @ResponseBody internally.

**Comment by kamalkumar789** [comment]
Its good to change this responseBody instead of changing controller to restController.
I have changed it. 
Should I push it?

**Comment by ayushdubey755** [comment]
Can I work on this issue?
@mbhave  I would love to work on it since I am currently working on spring boot and also previously resolve jkube issue.

**Comment by snicoll** [comment]
Closing in favor of PR #1401
