### ISSUE TITLE
Projects generated

### ISSUE THREAD

**Issue by dalexandrias** [spring-io/initializr#1356]
Good Morning.

Projects generated with java in versions 11 and 8 are being created with version 17
Can check?

**Comment by dalexandrias** [comment]
Options:
Project: Maven
Packaging: Jar
Language: java
Spring boot: 3.0.0
Java: 11 or 8

**Comment by philwebb** [comment]
This is intentional as Java 17 is the minimum supported version for Spring Boot 3.0 / Spring Framework 6.0
