### ISSUE TITLE
Sping Initializr web set incorrect settings to java version properties

### ISSUE THREAD

**Issue by tarunsamal** [spring-io/initializr#1358]
Go to https://start.spring.io/ and select java version as 8 and download
![image](https://user-images.githubusercontent.com/17237647/206480386-2f7ffb38-fe47-41ac-9c6b-4189b0c973cc.png)

In the downloaded zip , check the pom.xml it should be 8 instead of 17
![image](https://user-images.githubusercontent.com/17237647/206480912-74a41db8-0fc2-4db6-9eb1-47be40c73523.png)

Kindly disable version 3.0.0 or provide warning if user select springboot version as 3.0.0 (need jdk 17+) and java 8 otherwise 
we may get 

![image](https://user-images.githubusercontent.com/17237647/206492961-6465ce80-5e46-473c-b07f-69de4a1f15b5.png)

**Comment by zanto001** [comment]
Same for java 11, the generated pom.xml java version is 17. 
If you pick spring boot [2.7.6] with java 11 it generates it correctly though.

**Comment by philwebb** [comment]
Spring Boot 3.0 requires Java 17 or higher, that's why the version is changed.

**Comment by sbmvirdi** [comment]
Ideally we should not allow user to select java versions which are not compatible with the versions of the spring boot. it should maintain the compatible java versions for each spring boot version and should show a info message that older versions of java is not compatible with this spring boot version.

**Comment by philwebb** [comment]
@sbmvirdi That's an option for the web UI, but a bit more difficult for current IDE integrations.

**Comment by wilkinsona** [comment]
Duplicates https://github.com/spring-io/initializr/issues/1350.

**Comment by gbyteinfo** [comment]
Honestly, I can't believe that there is this lack of consideration for lay users. Add a message in Sping Initializr to inform that versions 3.0.0+ is only compatible with java 17+.

**Comment by wilkinsona** [comment]
@gbyteinfo The HELP.md file that's generated as part of every project should do just that. We prefer to include the information in the generated project as it means the information is provided, irrespective of how the project is generated (CLI, IDE, https://start.spring.io, etc). If you're not seeing such an entry in the HELP.md file, please let us know.

**Comment by gbyteinfo** [comment]
> @gbyteinfoO arquivo HELP.md gerado como parte de cada projeto deve fazer exatamente isso. Preferimos incluir as informações no projeto gerado, pois isso significa que elas são fornecidas independentemente de como o projeto é gerado (CLI, IDE, https://start.spring.io , etc). Se você não estiver vendo essa entrada no arquivo HELP.md, informe-nos.

I appreciate the feedback, I found and viewed the MD and understand better.
