### ISSUE TITLE
Error On Version Missing from MySQL Dependency

### ISSUE THREAD

**Issue by codeboarder** [spring-io/initializr#1362]
In the Azure documentation located here: https://learn.microsoft.com/en-us/training/modules/deploy-java-spring-boot-app-service-mysql/3-exercise-build, the step when curling: **https://start.spring.io/starter.tgz -d type=maven-project -d dependencies=web,data-jpa,mysql -d baseDir=azure-spring-workshop -d bootVersion=2.3.2.RELEASE -d javaVersion=1.8 | tar -xzvf -**, I get an error when I run **./mvnw spring-boot:run** indicating that I am missing a version on the mysql-connector-j dependency in the pom.xml file. When I add <version>8.0.32</version> to the dependency element, the error is fixed.

![Error](https://user-images.githubusercontent.com/92164158/208967819-0aca3179-7b97-4e5c-b7d2-78f3938d793a.png)

**Comment by wilkinsona** [comment]
Thanks for letting us know. Spring Boot 2.3.x is [no longer supported](https://spring.io/projects/spring-boot#support) in open source or commercially. Please reach out to Microsoft and ask them to update their documentation. You should not see the problem you have described with supported versions of Spring Boot.
