### ISSUE TITLE
Any plan to use dependencyResolutionManagement  instead of repository

### ISSUE THREAD

**Issue by hannah23280** [spring-io/initializr#1364]
Any plan to replace **repository** (in build.gradle) with **dependencyResolutionManagement** (in settings.gradle)?

In case anyone ask what is the advantage of introducing this minor change, i think it will be
1) **dependencyResolutionManagement** is newly introduced in gradle v6.8,  hence good to keep up with the edge
2) By defining it in settings gradle,  reduce clutterness at the build.gradle side.

**Comment by wilkinsona** [comment]
Thanks for the suggestion. We don't have any plans at this time but we can certainly consider it. A disadvantage of this change would be that it's only really of benefit to multi-module builds. It's also interesting that Gradle's own documentation still leads with declaring repositories in `build.gradle`, only mentioning using `settings.gradle` [later on](https://docs.gradle.org/current/userguide/dependency_management.html#sub:centralized-repository-declaration).

**Comment by mhalbritter** [comment]
We talked about it and we decided to keep the current state.
