### ISSUE TITLE
Generated folder structure to include app folder?

### ISSUE THREAD

**Issue by hannah23280** [spring-io/initializr#1365]
Starting from v6.x of gradle, running gradle init will generate a template folder structure with a newly introduced **app** folder at the root project folder, which in turn host the src folder.  I think the main reason for such change is to easily support multiple gradle subprojects.   In other word, we now can have app folder, app2 folder , app3 folder, etc....under the root project folder.

This is useful, especially, for project that contain multiple microservices sub-project.

Hopefully there are plans to update the structure of the generated folder from the Spring.io initializr to adhere to the aforementioned

**Comment by wilkinsona** [comment]
Thanks for the suggestion. I'm not sure that we should do this by default. Arguably, it's extra clutter and indirection for single module projects that don't need it. If we were to provider it as an option, it should also be supported for Maven projects. https://github.com/spring-io/initializr/issues/663 is tracking general multi-module support.
