### ISSUE TITLE
Append instead of replace `freeCompilerArgs` Kotlin property

### ISSUE THREAD

**Issue by sdeleuze** [spring-io/initializr#1368]
Based on the discussion on [KT-41985](https://youtrack.jetbrains.com/issue/KT-41985/Disallow-error-prone-removal-of-freeCompilerArgs-elements#focus=Comments-27-4967616.0-0), I am wondering if we should use `freeCompilerArgs += "-Xjsr305=strict"` instead of `freeCompilerArgs = listOf("-Xjsr305=strict")` (this is for Kotlin DSL, the code should be adapted for Groovy DSL as well). cc @wilkinsona @bclozel

**Comment by wilkinsona** [comment]
Sounds like a good idea to me.
