### ISSUE TITLE
Integrate takari maven-wrapper into initializr

### ISSUE THREAD

**Issue by spencergibb** [spring-io/initializr#137]
This would reduce the requirements to just java 7/8.

We have done this in spring-cloud: https://github.com/spring-cloud/spring-cloud-build/commit/be8590222b5a235c531c5ee9e23717419138ca8d

/cc @dsyer @joshlong @dussab @mstine

**Comment by snicoll** [comment]
See #100

**Comment by spencergibb** [comment]
Though not as popular as `gradlew`, it solves many of the same problems. We did it in spring-cloud so that devs didn't have to have the 'right' version of maven installed.

**Comment by paskos** [comment]
:+1:

**Comment by making** [comment]
+1

**Comment by gregturn** [comment]
+1

**Comment by dussab** [comment]
+1

**Comment by snicoll** [comment]
Even the boss. Oh well :)
