### ISSUE TITLE
(🐞) 3.0.2 all generate with jvm 17

### ISSUE THREAD

**Issue by KotlinIsland** [spring-io/initializr#1375]
Here I select java 8, get the generated build file uses 17.

![image](https://user-images.githubusercontent.com/65446343/220517549-3d5464e7-fefd-412f-bcda-6b6cb0fb2fd1.png)
![image](https://user-images.githubusercontent.com/65446343/220517568-0bee22a6-a94f-4251-87f0-b35f28eb0514.png)

**Comment by philwebb** [comment]
This is intentional as Java 17 is the minimum supported version for Spring Boot 3.0 / Spring Framework 6.0

**Comment by KotlinIsland** [comment]
> This is intentional as Java 17 is the minimum supported version for Spring Boot 3.0 / Spring Framework 6.0. See also [spring-io/start.spring.io#1041](https://github.com/spring-io/start.spring.io/issues/1041)

Could the options for JVM 11/8 be disabled for 3.0? Because this looks like a bug

**Comment by KotlinIsland** [comment]
@philwebb Additionally, when `19` is selected `17` is still present in the generated project.
