### ISSUE TITLE
Disable invalid combinations of options

### ISSUE THREAD

**Issue by KotlinIsland** [spring-io/initializr#1377]
Such as:
- Kotlin + Java 19
- Spring 3 + Java 8/11

Otherwise different options are selected and the generated project is wrong.

Relates to #1227 

(On further investigation, I think this is a duplicate of https://github.com/spring-io/start.spring.io/issues/250)

**Comment by wilkinsona** [comment]
@KotlinIsland please don't open multiple issues and make multiple comments for the same problem. It creates a lot of noise in the issue trackers and for everyone watching them.
