### ISSUE TITLE
Add custom user provided service papertrail in manifest?

### ISSUE THREAD

**Issue by bclozel** [spring-io/initializr#138]
I've configured initializr to send its logs to our papertrail account: I've created a custom service in our PWS instance and linked it to a dedicated syslog endpoint. The name of that custom service is `papertrail-initializr`.

Should we add that service name in the application manifest?

**Comment by dsyer** [comment]
Sounds good.

**Comment by snicoll** [comment]
The one for redis is `start-redis`. Maybe we could name things consistently?

**Comment by snicoll** [comment]
I see no reason to use papertail in dev & staging. Adding that to the manifest will prevent the app to deploy AFAIK.
