### ISSUE TITLE
reload configuration info dynamically

### ISSUE THREAD

**Issue by liweijian199011** [spring-io/initializr#1389]
what can i do that enable initializr to reload configuration info in properties or yaml file dynamically by using distributed config center, eg. alibaba nacos or apollo config center。

**Comment by wilkinsona** [comment]
I'm afraid there's nothing that you can do as this isn't supported. We recommend redeploying the application when making a configuration change. This is what we do for https://start.spring.io. With two instances, it can be done with zero downtime and, in our experience, is less brittle than refreshing configuration at runtime.
