### ISSUE TITLE
Choosing Java 11 does not change the pom target version

### ISSUE THREAD

**Issue by jeremy-brooks** [spring-io/initializr#1390]
![image](https://user-images.githubusercontent.com/1654657/224347923-ca56415c-3e88-4490-a2bc-9e064c62215b.png)

But pom shows:

![image](https://user-images.githubusercontent.com/1654657/224347468-38e79233-3114-4067-a5ae-2b3090b88cd8.png)

So when I download and try to build against JDK 11, it fails with:

```
java: warning: source release 17 requires target release 17

Module demo SDK 11 is not compatible with the source version 17.

Upgrade Module SDK in project settings to 17 or higher. Open project settings.
```

**Comment by wilkinsona** [comment]
Duplicates #1378.
