### ISSUE TITLE
Document default metadata cache expiration policy

### ISSUE THREAD

**Issue by mmoayyed** [spring-io/initializr#1391]
Using version `0.13.0`; At the moment, the default cache customizer does the following:

```java
                @Override
		public void customize(javax.cache.CacheManager cacheManager) {
			createMissingCache(cacheManager, "initializr.metadata",
					() -> config().setExpiryPolicyFactory(CreatedExpiryPolicy.factoryOf(Duration.TEN_MINUTES)));
			createMissingCache(cacheManager, "initializr.dependency-metadata", this::config);
			createMissingCache(cacheManager, "initializr.project-resources", this::config);
			createMissingCache(cacheManager, "initializr.templates", this::config);
		}
```

- Could the expiration policy, that is `Duration.TEN_MINUTES`, be configurable via application properties? (I am not sure if it's possible to customize this after the fact)
- Could this be documented? Was not able to [find it here](https://docs.spring.io/initializr/docs/current/reference/html/#create-instance-advanced-config-caching).

I am happy to help and submit a PR if you find this to be reasonable.

**Comment by wilkinsona** [comment]
I'm not sure that we want to provide this level of control.  The documentation recommends the following approach:

```
The caches are created with an auto-configured JCacheManagerCustomizer with order `0` and only if they don’t exist already. You can contribute a bean of the same type with a lower `@Order` to override some of the configuration to suit your specific needs.
```

Does this not meet your needs?

**Comment by mmoayyed** [comment]
I am not sure that it does. I don't see how to change the expiration policy duration after the cache is built. This turns into an immutable, complete cache and I don't think any customizer can change those settings without some very ugly hacks. I could of course entirely skip this and supply my own cache, or I could entirely skip the feature altogether and do caching entirely on my own but I don't see how that would be immediately better than having a single-lined setting that says "cache duration is X number of minutes".

**Comment by mmoayyed** [comment]
I went ahead with:

```java
    @Bean
    @Order(Ordered.HIGHEST_PRECEDENCE)
    public JCacheManagerCustomizer initializrMetadataCacheManagerCustomizer() {
        return cacheManager -> {
            var cacheDuration = Duration.ONE_DAY;
            var config = new MutableConfiguration<>()
                .setStoreByValue(false)
                .setManagementEnabled(true)
                .setStatisticsEnabled(true)
                .setExpiryPolicyFactory(CreatedExpiryPolicy.factoryOf(cacheDuration));
            log.info("Initialize metadata is cached for 1 day");
            cacheManager.createCache("initializr.metadata", config);
        };
    }
```
You can certainly close this out, if you still feel like this level of control is unwarranted. (I would nonetheless consider documenting this) 

Thank you!

**Comment by mmoayyed** [comment]
Certainly, yes; To clarify, I meant that the default duration for the cache should be documented as well. i.e. 

> The initializr metadata cache by default is configured with an expiration policy that allows entries to remain in the cache for 10 minutes.
