### ISSUE TITLE
Use of Password Hash With Insufficient Computational Effort

### ISSUE THREAD

**Issue by vignesh7056** [spring-io/initializr#1392]
The MD5 hash (used in org.springframework.util.DigestUtils.appendMd5DigestAsHex) is insecure. Consider changing it to a secure hash algorithm

file path = initializr\initializr-web\src\main\java\io\spring\initializr\web\controller\AbstractMetadataController.java

![Screenshot 2023-03-19 080158](https://user-images.githubusercontent.com/37074210/226185216-2f9728d4-1ede-4877-a5b5-392d3b0fd0f2.png)

**Comment by wilkinsona** [comment]
The hash is used in ETag headers in HTTP responses where MD5 hashes are common. [Amazon's S3](https://docs.aws.amazon.com/AmazonS3/latest/API/API_Object.html) is one example.
