### ISSUE TITLE
[Q] How can we integrate Spring Initializr into Backstage templates?

### ISSUE THREAD

**Issue by artemptushkin** [spring-io/initializr#1394]
There is a great feature Backstage developer portal - [Software templates](https://backstage.io/docs/features/software-templates/configuration) I wonder how can we integrate Spring Initializr into this?

Corresponded discussion in Backstage https://github.com/backstage/backstage/discussions/17146

**Comment by snicoll** [comment]
Thanks but I'd rather have the conversation in a single place. And we don't use the issue tracker for questions anyway.

**Comment by bgalek** [comment]
is there a valid link to track? :)

**Comment by bgalek** [comment]
@wilkinsona thanks! I'll go for discord then :)
