### ISSUE TITLE
Clarify start.spring.io

### ISSUE THREAD

**Issue by berlin-ab** [spring-io/initializr#14]
start.spring.io is a good way to introduce a new developer to Spring and spring-boot but some of the nomenclature can be confusing as well.

I  was ramping up a new developer and here are some questions that came up:

1. What are the 'group', 'artifact', 'name', 'description' and 'package name'  values used for? Is it okay to not specify them? How does it affect the application? 
2. What are styles? In this section there's a list of dependencies but not everyone knows what they are for. Adding some description or categories (logging, development mode, datasources, templating, etc) may help the user and prevent him to make a selection that doesn't make much sense (JDBC and JPA).
3. What are types? Maybe renaming to Build tools or 'What is your preferred build tool?'  makes it more straight forward
4. Another suggestion is to have a pre set that allows the user to start a working project such as: 'dynamic web' (web + some persistence + some template language + actuator) or 'restful API'  (web + persistence + actuator).

**Comment by snicoll** [comment]
You last point is handled in #104. Each dependency has now a description. As for the rest I don't think there is much more we should do. Feel free to propose a PR if you think otherwise.
