### ISSUE TITLE
Upgrade to Maven resolver provider 3.9.1

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#1400]

**Comment by prithvitewatia** [comment]
Hi @snicoll , can i work on this issue ?

**Comment by snicoll** [comment]
Thanks for the offer. I tried to upgrade and something wasn't working but I can't remember what it was. Usually dependency upgrades are straightforward and we prefer to handle them but if you have some cycles to look into, please do!

**Comment by prithvitewatia** [comment]
@snicoll , I have solved this issue. Could you please review it ? Thanks.

**Comment by snicoll** [comment]
Thanks for that @prithvitewatia 

Closing in favor of PR #1415
