### ISSUE TITLE
Gitignore does not handle custom sections

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#1426]
Right now our support for `.gitignore` contains a list of hard-coded sections. Adding additional sections has been requested in the past so we should look if we want to do that.

**Comment by liyifango** [comment]
> Right now our support for `.gitignore` contains a list of hard-coded sections. Adding additional sections has been requested in the past so we should look if we want to do that.

why not :technologist:

**Comment by mhalbritter** [comment]
Superseded by #1324.
