### ISSUE TITLE
Requesting application/hal+json returns 406 Not Acceptable

### ISSUE THREAD

**Issue by olivergierke** [spring-io/initializr#143]
`http http://start.spring.io Accept:application/hal+json` yields a `406 Not Acceptable` although the content returned from the following request is valid HAL.

`http http://start.spring.io Accept:application/json` returns:

```
Content-Type: application/vnd.initializr.v2.1+json;charset=UTF-8
```

which is basically invalid, as `application/vnd.initializr.v2.1+json` is not `application/json`. Unfortunately media types are not hierarchical (i.e. `application/vnd.initializr.v2.1+json` is not a specialized form of `application/json`).

I'd recommend to return the following headers:

`Accept: application/json` -> `Content-Type: application/json`
`Accept: application/hal+json` -> `Content-Type: application/hal+json`
`Accept: application/*-json` -> `Content-Type: application/vnd.initializr.v2.1+json`

**Comment by snicoll** [comment]
I am afraid we can't easily change that as IDEs are relying on that to request a relevant version of the met-data. This allows us to add extra fields (or even change the structure) without any impact on older versions. 

Considering this, what would be your recommendation?

**Comment by olivergierke** [comment]
I am not sure I can follow. If the IDE is requesting `application/json`, how can it expect to get a dedicated version? It's basically expressing: I don't care. If they request `application/vnd.initializr.v2.1+json` that of course can/should be returned.

**Comment by dsyer** [comment]
There are legacy IDEs that don't send an "Accept" header, and they expect to get the results in the old format. This is a perfect case study in API evolution, and maybe we screwed it up, but I don't see an easy exit. We have to wait for the legacy clients to be patched or become obsolete / unsupported before we can start demanding that they send a "legacy" header to indicate their legacy status.

**Comment by olivergierke** [comment]
Not sending an Accept header is equivalent to sending `Accept: */*`, in which case you can return what you want anyway. If you continue to return the versioned one than that's just fine. I wasn't complaining about that. I was pointing out that *if* the client sends an accept header, we return invalid values, values not matching what the client has requested.

**Comment by snicoll** [comment]
That clarifies, thanks. I'll have a look.

**Comment by dsyer** [comment]
That makes sense. I guess we need to verify that the IDEs are actually sending no header (that was a guess on my part).

**Comment by olivergierke** [comment]
IIRC, Spring MVC is defaulting that to `Accept: */*`. Shouldn't it just do the right thing™, if the controllers use `produces = { "application/vnd.initializr.v2.1+json", "application/hal+json", "application/json" }` and let the content negotiation do the heavy lifting?

**Comment by snicoll** [comment]
I think they send `application/json` but I am not sure if they care about the return type. The oldest one is parsing the `html` [page](http://start.spring.io/sts) anyway ( :scream: )
