### ISSUE TITLE
Consider using latest Gradle release when generating projects

### ISSUE THREAD

**Issue by rpalcolea** [spring-io/initializr#1434]
Hi folks,

I noticed that creating a new project with Spring Boot 3.1.x + Gradle results in using Gradle 7.6.1 where latest is 8.1.1

I'm wondering if you have considered creating new projects using latest gradle available in https://services.gradle.org/versions/current

**Comment by ysb33r** [comment]
@wilkinsona Finally, finally, finally asciidoctor-gradle 4.0 final will be out shortly and has been tested up to Gradle 8.5.https://github.com/asciidoctor/asciidoctor-gradle-plugin/pull/662

**Comment by wilkinsona** [comment]
Great stuff. Thanks very much, @ysb33r.
