### ISSUE TITLE
Use @GetMapping etc. where possible

### ISSUE THREAD

**Issue by dsyer** [spring-io/initializr#1453]
All the endpoints in initializr use `@RequestMapping` with no explicit `RequestMethod`, probably for historical reasons (`@GetMapping` and friends didn't exist when we started this project). It would be more expressive to show which methods are expected to be used, and I doubt anyone actually relies on being able to PATCH, PUT or POST these endpoints. They might get a surprise if they tried to DELETE as well.

https://github.com/spring-io/initializr/pull/1401 switched to `@RestController` from `@Controller`. It seems like this change is in the same spirit.

**Comment by dsyer** [comment]
There is a possible answer to why we support GET and POST. Because we want `curl start.spring.io?dependencies=web` and `curl start.spring.io -d dependencies=web` to be the same - i.e. for the convenience of CLI agents.

**Comment by snicoll** [comment]
Closing in favor of PR #1456
