### ISSUE TITLE
Add Kotlin language support

### ISSUE THREAD

**Issue by sdeleuze** [spring-io/initializr#147]
Add Kotlin language support in addition to Java and Groovy.
I will contribute a PR.

**Comment by winterbe** [comment]
Awesome! :+1:

Here's a sample app, running Kotlin M14, Spring Boot 1.2 and React.js: https://github.com/winterbe/spring-kotlin-react-demo

**Comment by yyYank** [comment]
:+1:

**Comment by spencergibb** [comment]
And one with kotlin M14, Spring Boot 1.3.M5 https://github.com/spencergibb/springbootkotlin

**Comment by sdeleuze** [comment]
Starting to work on this.

I like the alternative version proposed on the [Creating a RESTful Web Service with Spring Boot](https://kotlinlang.org/docs/tutorials/spring-boot-restful.html) tutorial, I think I am going to use that one:

```kotlin
@SpringBootApplication
open class Application

fun main(args: Array<String>) {
	SpringApplication.run(Application::class.java, *args)
}
```

Seems to me simpler and more "Kotlin native" than:

```kotlin
@SpringBootApplication
open class Application {
    companion object {
        @JvmStatic public fun main(args: Array<String>) {
            SpringApplication.run(Application::class.java, *args)
        }
    }
}
```

**Comment by winterbe** [comment]
Thanks for pointing that out. I've updated my repo to Kotlin 1.0-beta and also use this simplified application bootstrap: https://github.com/winterbe/spring-kotlin-react-demo

**Comment by cy6erGn0m** [comment]
:+1:

**Comment by sdeleuze** [comment]
Pull request #161 submitted, any feedback appreciated.
