### ISSUE TITLE
There are too few samples!

### ISSUE THREAD

**Issue by mengxzh** [spring-io/initializr#1470]
1. For the first, I want to use initializr to build own start initializr. The Samples are to few, they couldn't help me well.
2. Furthermore, I want to build a multi maven project, there are one parent module and two sub-modules in this project. I couldn't find a best sample as i say
3. Last, spring-initializr has many functions in build project, I wish you should improving the documentation for complex situations

**Comment by snicoll** [comment]
I don't understand what you're asking. Or rather you asking 3 things and I don't understand what samples you're looking for. 

Have you [seen the reference guide](https://docs.spring.io/initializr/docs/current/reference/html/)? The project does not support generating mullti-modules project (if that's what you are asking). Please clarify.

**Comment by mengxzh** [comment]
Yes, i see the doc in spring.io. I want to build a maven multi module project. But I couldnt found any samples.

**Comment by snicoll** [comment]
Again, what do you mean by building? Creating? I already shared this feature is not supported.

**Comment by snicoll** [comment]
Duplicate #663
