### ISSUE TITLE
project with java version of 17 getting downloaded from spring initializer. I needed java version,8.

### ISSUE THREAD

**Issue by ANCHALAGEORGE** [spring-io/initializr#1472]
While downloading the project from Spring initializer , I am not able to download required project of java version 8. java 17 get downloaded. I am clicking on the correct button only. Please help

**Comment by wilkinsona** [comment]
To use Java 8, you must also select Spring Boot 2.7. Spring Boot 3.0 and later require Java 17. If you select an invalid combination, the Java version will be changed automatically.
