### ISSUE TITLE
React.js support

### ISSUE THREAD

**Issue by winterbe** [spring-io/initializr#148]
React.js is now the 5th most popular JavaScript project on GitHub: 

https://github.com/search?l=JavaScript&p=1&q=stars%3A%3E1&s=stars&type=Repositories

While Spring Boot plays nicely with React.js it's not that obvious how to get started when creating a React app with Spring Boot. So I'd like to see a Spring Starter option for using React.js to build the frontend part of the Spring Boot webapp.

You can find a minimal example here: https://github.com/winterbe/spring-kotlin-react-demo

The project uses the following things:

- NPM `package.json` to manage frontend dependencies (e.g. react)
- Babel to compile ES6/JSX syntax into valid ES5 javascript files
- ESLint as Javascript linter
- Webpack as build tool, creates a `bundle.js` to be included into `index.html`

In my opinion this is the defacto standard when writing modern webapps in React. I'm not entirely sure what's the best way to integrate NPM/Webpack into the Maven/Gradle build cycle. I'm using NPM to run Maven but maybe the other way around would make more sense from a Java perspective: 

https://github.com/winterbe/spring-kotlin-react-demo/blob/master/package.json#L13-L17

**Comment by snicoll** [comment]
I think client-side development has to be tackled in Spring Boot itself first. We should have examples of that and a enough cycles to warrant the requested maturity. Then we can think integrating it here.

Besides, your request duplicates #104 (what belongs here, that is). Thanks for the example.
