### ISSUE TITLE
Add option for Spring Retry

### ISSUE THREAD

**Issue by mdeinum** [spring-io/initializr#149]
> If you expect that the config server may occasionally be unavailable when your app starts, you can ask it to keep trying after a failure. First you need to set `spring.cloud.config.failFast=true`, and then you need to add `spring-retry` and `spring-boot-starter-aop` to your class path.

It would be nice if `spring-retry` could be added as a dependency from the UI. Currently only `spring-boot-starter-aop` can be selected.

**Comment by snicoll** [comment]
I'd rather argue that a cloud starter should take care of this. I am not super fan of adding isolated components like that. Ping @dsyer

**Comment by mdeinum** [comment]
The fact that it is possible to use and that there is auto configuration for it makes me think that it is already somewhere but as an `<optional>true</optional>` dependency. @dsyer ?

**Comment by dsyer** [comment]
I think it should be available and it's not a cloud dependency.
