### ISSUE TITLE
[Enhancement] Use Java toolchain for gradle

### ISSUE THREAD

**Issue by CXwudi** [spring-io/initializr#1494]
Would you consider replacing:

``` kotlin
java {
  sourceCompatibility = JavaVersion.VERSION_21
}
```

with:

``` kotlin
java {
  toolchain {
    languageVersion.set(JavaLanguageVersion.of(21))
  }
}
```
Since the java toolchain is what Gradle preferred in its [guide](https://docs.gradle.org/current/userguide/building_java_projects.html#introduction)

Also, toolchain has the benefit of automatically download the declared Java distribution if one is missing in the host machine

**Comment by wilkinsona** [comment]
Duplicates #1227.
