### ISSUE TITLE
Use non-deprecated Kotlin DSL for Kotlin compile options

### ISSUE THREAD

**Issue by CXwudi** [spring-io/initializr#1495]
In recent version of Kotlin Gradle Plugin, `tasks.withType<KotlinCompile>.kotlinOptions` is marked as deprecated

![image](https://github.com/spring-io/initializr/assets/17377423/52667866-23e4-44ce-bd61-a60a585cd52e)

A better DSL is:

``` kotlin
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

kotlin {
  compilerOptions {
    freeCompilerArgs = freeCompilerArgs.get() + listOf("-Xjsr305=strict")
    jvmTarget = JvmTarget.JVM_21
  }
}
```

**Comment by mhalbritter** [comment]
One problem I stumbled upon is that there's no `JvmTarget.JVM_22`.
