### ISSUE TITLE
Shouldn't @JooqTest also load Repositories

### ISSUE THREAD

**Issue by simasch** [spring-io/initializr#1498]
Currently @JooqTest only creates the datasource and the DSLContext.
Often, we use @Repository to separate the data access layer, like with Spring Data.
But beans annotated with @Repository are not created with @JooqTest.

JooqTest makes little sense because what can be tested just with having the DSLContext? One would need to write the jOOQ queries in the test directly.
Therefore it would be great if also Repositories would be created in this test slice.

**Comment by snicoll** [comment]
wrong repository?

**Comment by simasch** [comment]
What do you mean with wrong?

**Comment by snicoll** [comment]
You're asking for a Spring Boot test slice to do something different here. I don't really understand what Spring Initializr could do about that.

**Comment by simasch** [comment]
Oh, sorry not I understand 😅

I should not work on weekends...
