### ISSUE TITLE
Migrate build to GitHub actions

### ISSUE THREAD

**Issue by mhalbritter** [spring-io/initializr#1508]
- [x] Build on Linux
- [x] Build on Windows
- [x] Publish snapshots
- [x] Release from GHA
- [x] Update Build badge
- [x] Google Chat notifications

**Comment by jongwooo** [comment]
I want to work on remaining tasks.

**Comment by mhalbritter** [comment]
Thanks for the offer, but you'd have no way to test that.

**Comment by mhalbritter** [comment]
Deployment can be seen in Spring Boot: https://github.com/spring-projects/spring-boot/blob/72441637ce5bad07043a259d86ea013dad7b4c31/.github/workflows/build-and-deploy-snapshot.yml#L20

**Comment by mhalbritter** [comment]
A draft of the release workflow is available here: https://github.com/mhalbritter/initializr/tree/mh/release-from-gha

**Comment by mhalbritter** [comment]
Release workflow has been put into main in https://github.com/spring-io/initializr/commit/9decc528cad776dd9c6d21c22dd405502cacb6af.

**Comment by mhalbritter** [comment]
0.21.0 has been released from GHA.
