### ISSUE TITLE
Add Spring Session

### ISSUE THREAD

**Issue by rwinch** [spring-io/initializr#151]
It would be nice if Spring Session were listed as a dependency. This is important to any application that needs clustering support and requires a session.

Perhaps it would even be "Spring Session (Redis)" which would add the spring-session and spring-boot-starter-redis dependencies in one option.

**Comment by snicoll** [comment]
That's not how this is working. The usual way of getting an entry here is to have a starter. There is also a minority of dependencies that are added on their own (to save you from typing the groupId/artifactId yourself). 

My take would be to either have a starter for it or add only Spring session itself (if you confirm a single artifact is enough for the 80% use case).

**Comment by rwinch** [comment]
Typically Spring Boot users should be adding the combination of spring-session and spring-boot-starter-redis. Does that mean you think we need a spring-boot-starter-session-redis and then it could be added?

**Comment by snicoll** [comment]
I am just saying that when we have a typical use case for 'Foo' we end up with a `spring-boot-starter-foo`. 

What you are mentioning here is different; it's a combination of a spring dependency + another stack (redis). I don't have any opinion regarding creating an extra starter for `spring-session-redis` but you should get that before asking here, that's all I am saying.

Spring Initializr doesn't support (yet) that a single dependency entry (checkbox) adds several dependencies. I was thinking of adding that feature at some point so it can be a good start if you feel it's the best way to handle this issue.

**Comment by rwinch** [comment]
@snicoll Thanks for the reply

> Spring Initializr doesn't support (yet) that a single dependency entry (checkbox) adds several dependencies. I was thinking of adding that feature at some point so it can be a good start if you feel it's the best way to handle this issue.

I think this is the best option. Is there a distinct issue for this to track?

**Comment by snicoll** [comment]
#152 :)

**Comment by snicoll** [comment]
I just had an interesting discussion on this one with @dsyer and we already have that kind of use case with `data-jpa` that requires a database (driver) in order to operate properly. Maybe we should consider adding `spring-session` has an additional artifact and the user would have to chose the backend store as well.

How does that sound? Any preferred location for the artifact?

**Comment by rwinch** [comment]
I recently gave this more thought and realized that Spring Session also has an optional dependency on Spring Web. This means with an optional dependency on a data store and optional dependency on web, we are already at a large number of permutations. For this reason, I think requiring the user to select other pieces for their integration makes sense.

I wonder if we could support a help icon to assist users in understanding what is required. Supporting an error message if no data store was selected might also make sense. Of course these two items can be spun off in separate issues.

I think the location that makes the most sense is core since the only required Spring Session dependency is commons-logging. Thoughts?

**Comment by snicoll** [comment]
> I wonder if we could support a help icon to assist users in understanding what is required. 

I don't know. We can put that as part of the description (PR welcome).

>  Supporting an error message if no data store was selected might also make sense

There are tricky case (some starter may bring a database, the batch one does) so avoiding false positive can be hard and we need a way to express that in the meta-data (the web UI is just one frontend and I don't want to implement any custom logic in there).
