### ISSUE TITLE
support for Spring Boot 2.7.18 in options

### ISSUE THREAD

**Issue by avatar21** [spring-io/initializr#1511]
why there's no support for Springboot 2.7.18 in versions, it's a secure version for ppl. who still uses Java 1.8.

With this question raised, there goes another question, will more than one active major version be supported?
e.g. 2.7.x, 3.1.x, ... etc

**Comment by philwebb** [comment]
Spring Boot 2.7 is no longer supported as open source software and as such we don't want to offer it on start.spring.io. More than one active major version can be supported, and in fact this was the case previously when we offered Spring Boot 2.7 and 3.0 at the same time. It will likely happen again when there is another major Spring Boot release.
