### ISSUE TITLE
Set Gradle - Kotlin DSL as the default option

### ISSUE THREAD

**Issue by Vladislav-Zolotaryov** [spring-io/initializr#1547]
Hello.

As of Gradle 8.2 (Jun 30, 2023), [Gradle proposes to use Kotlin DSL](https://blog.gradle.org/kotlin-dsl-is-now-the-default-for-new-gradle-builds) as the default option.

As a Java developer I frequently see inconsistency in new project creation, because gradle init and Intellij IDEA "New Java Project" dialog uses Kotlin DSL by default, but when I use Initializr I get Groovy by default.

It would be great to make it uniform across the board.

Thank you!

**Comment by mhalbritter** [comment]
Duplicates https://github.com/spring-io/start.spring.io/issues/1155.
