### ISSUE TITLE
Generating a Kotlin project with a package name containing keywords will result in an unusable project

### ISSUE THREAD

**Issue by Ant00000ny** [spring-io/initializr#1550]
For example if package name is `fun.fantasea.demo`, generated project files are like below:

<img width="804" alt="image" src="https://github.com/spring-io/initializr/assets/20972206/7cda31af-366f-430e-a79e-a22d160b5c1c">

<img width="772" alt="image" src="https://github.com/spring-io/initializr/assets/20972206/02b2bb79-54b7-4a00-928d-a2945ddcca32">

Correct package name should be 
```
`fun`.fantasea.demo
```

**Comment by mhalbritter** [comment]
For (Java) projects, we use `io.spring.initializr.metadata.InitializrConfiguration#hasReservedKeyword` to check for reserved keywords. We should do something similar for Kotlin. It could even be that Kotlin generated projects are checked against Java keywords, which might be another bug.

**Comment by Ant00000ny** [comment]
Maybe we can use kotlin.reflect.jvm.internal.impl.renderer.KeywordStringsGenerated#KEYWORDS for this? Didn't find any documentation explaining its purpose, but the list matches the hard keywords in the documentation though.

**Comment by mhalbritter** [comment]
Superseded by https://github.com/spring-io/initializr/pull/1555. Thanks @Ant00000ny!
