### ISSUE TITLE
Generate gitattributes file

### ISSUE THREAD

**Issue by xenoterracide** [spring-io/initializr#1569]
it's annoying when I create a new project, the first thing I have to do is copy my `.gitattributes` from somewhere else lest something be committed incorrectly (like line ending fixes to `lf` in a `.bat`. autocrlf isn't really the recommended way to go these days. The best way is gitattributes. This is a good enough default for `.gitattributes` since these are the extensions/files that will get generated. I'm not certain if you generate with `mvnw` if you do then you will need to update for that.

```
* text=auto eol=lf
*.sh text eol=lf
*.bat text eol=crlf
*.jar -text
/gradlew text eol=lf
```

`bat`, `cmd`, `ps` will not work with `lf` line endings, any variant of an `sh` will not work with `crlf`, even on a windows bash (last time I tried) that's why this should be done.

**Comment by mhalbritter** [comment]
For reference, this is what `gradle init` creates:

```
#
# https://help.github.com/articles/dealing-with-line-endings/
#
# Linux start script should use lf
/gradlew        text eol=lf

# These are Windows script files and should use crlf
*.bat           text eol=crlf

# Binary files should be left untouched
*.jar           binary
```

**Comment by xenoterracide** [comment]
I think in the .gitattributes documentation I saw that it says that it now recommends -text instead of binary. You might want to check that because I believe gits documentation about git before gradles 😉.  They achieve the same thing, binary is still safe.

 Either way I'd be happy, as this is really only a problem for me when I'm trying to throw something quick together to give people as an example.

**Comment by mhalbritter** [comment]
Hey,

we talked about that in our meeting and we agreed that we should add a `.gitattributes` file.
