### ISSUE TITLE
Add '-parameters' javac argument for Java 8 applications

### ISSUE THREAD

**Issue by wjam** [spring-io/initializr#157]
As more libraries become Java 8 aware and take advantage of such functionality, such as Spring Data or Jackson, it makes sense to allow use of this functionality out of the box rather than having to remember to add the specific configuration.

I think that for Java 8 projects, the -parameters argument should be added by default.

**Comment by dsyer** [comment]
What functionality are you talking about specifically? I didn't see any "-parameters" in the standard JDK 1.8.

**Comment by snicoll** [comment]
There is one (`javac`)
```
 -parameters                Generate metadata for reflection on method parameters
```

**Comment by snicoll** [comment]
I am more leaning towards not doing this. I am afraid you'd get a certain experience with the build and something else in your IDE. Netbeans would work as it uses the build consistently. 

If @kdvolder and @yanncebron both confirms that value will be automatically and consistently applied, I am more than happy to reconsider this.

**Comment by olivergierke** [comment]
It's working fine in Eclipse. m2e sets everything up as expected. Strong vote to introduce this, as it's kind of a black spot on our Java 8 story (with Boot in general), having to still annotate interface parameters with `@Param` or let users declare that very plugin themselves (which they usually don't do, see @joshlong in his demos :smiley:).

**Comment by kdvolder** [comment]
I bet that it won't work for gradle though. Then again there are lots of things that don't work or don't work as well for gradle as they do from m2e. So that's probably not a good enough reason to deny this feature to maven users.
