### ISSUE TITLE
Configure Kotlin's all-open plugin for JPA entities

### ISSUE THREAD

**Issue by YangSiJun528** [spring-io/initializr#1572]
When creating a project with Kotlin and Spring Data JPA via Spring Initializr, the plugin.spring and plugin.jpa plugins are provided in `build.gradle.kts` or `build.gradle`. 
However, despite these plugins, the all-open configuration for JPA entities is not included by default. (The same goes for using Maven. There are differences in plugins, but all-open for JPA Entites is not supported.)

Since Kotlin classes are final by default, developers must manually add the all-open configuration for JPA entities on top of the settings provided by Spring Initializr. 
Otherwise, eager loading occurs, even when relationships between entities are explicitly marked as lazy. This behavior can be confusing to developers.

This concern was raised earlier in [this issue](https://github.com/spring-io/initializr/issues/1130), but it was closed with the suggestion to raise it with the Kotlin team. Unfortunately, the issue ([KT-28594](https://youtrack.jetbrains.com/issue/KT-28594)) has remained unresolved for nearly six years. As discussed in [this pull request](https://github.com/JetBrains/kotlin/pull/2421#issuecomment-542559532), the Kotlin team no longer provides framework-specific solutions for this.

To improve the developer experience, it would be beneficial to include a plugin that provides all-open configuration for JPA entities or automatically adds this configuration. 

I’m interested in contributing to this feature and would appreciate any guidance on how to proceed with the implementation.

**Comment by mhalbritter** [comment]
Hello,

if I understand this correctly, it's about adding

```gradle
allOpen {
    annotation("jakarta.persistence.Entity")
    annotation("jakarta.persistence.MappedSuperclass")
    annotation("jakarta.persistence.Embeddable")
}
```

to `build.gradle` and

```xml
<configuration>
// ...
        <pluginOptions>
            <option>all-open:jakarta.persistence.Entity</option>
            <option>all-open:jakarta.persistence.MappedSuperclass</option>
            <option>all-open:jakarta.persistence.Embeddable</option>
        </pluginOptions>
</configuration>
```

to `pom.xml`.

Correct?

**Comment by YangSiJun528** [comment]
Yes, that's correct. In Kotlin + Spring Data JPA, the option must be written for Lazy Loading to work.

**Comment by YangSiJun528** [comment]
I have provided a simple example project.

Project Link: https://github.com/YangSiJun528/example-kotlin-jpa

The project contains two branches:  
- `success`: where lazy loading works as expected with the addition of all-open configuration.
- `failure`: where lazy loading does not work.

You can open the project and run `./gradlew test` to execute the tests.

**Comment by bondit-sijunyang** [comment]
I'm interested in contributing to this feature and would like to know if it's possible for me to work on implementing it.

**Comment by YangSiJun528** [comment]
I'm interested in contributing to this feature and would like to know if it's possible for me to work on implementing it.

**Comment by mhalbritter** [comment]
Superseded by #1576.
