### ISSUE TITLE
support for version catalog (libs.version.toml)

### ISSUE THREAD

**Issue by bgalek** [spring-io/initializr#1574]
Hi!
I think adding versions into global properties like `extra["library"] = "8.3.0"`
should be replaced with gradle's version catalog feature (libs.versions.toml) support
https://docs.gradle.org/current/userguide/platforms.html#sub:conventional-dependencies-toml

WDYT? :)

**Comment by mhalbritter** [comment]
This has been discussed in the start.spring.io project already: https://github.com/spring-io/start.spring.io/issues/1600

**Comment by bgalek** [comment]
@mhalbritter 
Everything is better than a global `extra` map, so maybe at least inline this `extra["library"]` to regular dependency declaration?

**Comment by mhalbritter** [comment]
Where do you see this `extra` map? When generating a project on start.spring.io, there's usually no `extra` map. Most of the dependencies are managed by Spring Boot, and if there's an explicit version number, it's either a BOM or inlined in the dependency declaration:

```gradle
ext {
  set('springCloudAzureVersion', "5.16.0")
}
```

or

```gradle
dependencies {
  implementation 'gg.jte:jte:3.1.12'
  implementation 'gg.jte:jte-spring-boot-starter-3:3.1.12'
}
```

**Comment by bgalek** [comment]
yes sorry, that was typo :) I've meant `ext` of course.
 
`platform()` is more natural to gradle dependency declaration syntax (https://docs.gradle.org/current/userguide/platforms.html#sub:bom_import), 

```
dependencies {
    // import a BOM
    implementation(platform("org.springframework.boot:spring-boot-dependencies:1.5.8.RELEASE"))
    // define dependencies without versions
    implementation("com.google.code.gson:gson")
}
```
I don't see any value for having a BOM version in `ext` DSL, since I won't ever be referencing this variable.
It's additional cognitive load, that I need to unpack - my version is "away" from my declaration.
`platform()` syntax has better support by static analysis tools for gradle (don't need code evaluation of variable from `ext` DSL) - i.e. dependabot, FOSSA.

Having `ext{}` can also lead to unusual ideas, like combining/calculating multiple `ext` values.

**Comment by mhalbritter** [comment]
This has been discussed in https://github.com/spring-io/initializr/issues/1414.
