### ISSUE TITLE
Create `src/main/resources/processes` when activiti starter is selected

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#158]

**Comment by snicoll** [comment]
I am torn about that one. This sounds like a good thing to do (we do similar thing for web related stuff, creating the templates/static packages when we detect that a web "facet" is present). We can't really put an activiti specific logic in the library.

I've hacked something with a basic interface `ProjectStructureGenerator` (that requires a better name), moving the web specific logic in an implementation (and potentially more). Then all we need is an implementation that checks if activiti is present and create the necessary extra package.

I can't put the implementation in the library which means that it needs to be in the startup script somewhere. Which means it's not tested.

WDYT @dsyer ?

**Comment by dsyer** [comment]
I think we need to do something more extensive if we do this (the same argument applies to a load of other template features with use cases that depend on the classpath).

**Comment by snicoll** [comment]
Duplicate of #340
