### ISSUE TITLE
Spring Boot version 3.4.0, Spring Cloud Version 2024.0.0, Spring Cloud Stream not compiling

### ISSUE THREAD

**Issue by Snurfleberry** [spring-io/initializr#1593]
When I create a project using Spring Initializr (https://start.spring.io/) and I add the Cloud Stream dependency I get a compilation error:

./gradlew clean build

/.gradle/caches/modules-2/files-2.1/org.springframework.cloud/spring-cloud-function-context/4.2.0/a66616bdd545b5375f0c312f253301021388e461/spring-cloud-function-context-4.2.0.jar!/META-INF/spring-cloud-function-context.kotlin_moduleModule was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.1.0, expected version is 1.9.0.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 4s
4 actionable tasks: 3 executed, 1 up-to-date

Spring Initializr configuration
Project: Gradle - Kotlin
Language: Kotlin
Spring Boot: 3.4.0
Dependencies: Cloud Stream

**Comment by wilkinsona** [comment]
Duplicates https://github.com/spring-cloud/spring-cloud-function/issues/1212.
