### ISSUE TITLE
IDEA plugin

### ISSUE THREAD

**Issue by abelardogit** [spring-io/initializr#1610]
The plugin for Intellj IDEA doesn't show all options when its window is completely maximized.

At the below video, you can watch how I try to maximize to show the whole options but I don't get it.
[Video](https://www.abelardolg.com/intelljidea_springboot_plugin.mp4)

Please, provide a way to access to the dependencies options when  we can't reach them by a mouse.

Even with a font of 10 points of size, I was unable to click on Dependencies options.

Thanks.

**Comment by snicoll** [comment]
@abelardogit you're asking in the wrong place on several counts. The IntelliJ IDEA plugin is developed by Jetbrains, please report that there.
