### ISSUE TITLE
Add a link to corresponding guide or documentation

### ISSUE THREAD

**Issue by grebesche** [spring-io/initializr#163]
Just throwing an idea out there. It may be nice to have a link for each modules for the corresponding guide or documentation. If interested, I may submit a pull request.

**Comment by snicoll** [comment]
Thanks for sharing the idea. I thought of that as well but I am not sure how the tools may use that. I think we would need to answer that first.

**Comment by snicoll** [comment]
@bclozel @kdvolder @yanncebron

If we want to pursue this one, I think that adding a `links` section to each dependency might be useful. Each entry would have an identifier + a `url` attribute. We could provide a list of well-known attribute such as `home` and `doc` for the home page and documentation of the "starter" respectively. UI-wise we may associate an icon per link id to make things consistent.

My problem is that I don't see how we could arrange those links. I don't think that having a single link is a good idea and turning the dependency name into a link would be weird as well. 

What do you guys think? Thanks!

**Comment by YannCebron** [comment]
Experienced users will probably not want to see all those links at all.

**Comment by snicoll** [comment]
On a related note, we already have poor description for each dependency so I also question the actual use of those links.

**Comment by YannCebron** [comment]
Maybe a more flexible approach is an HTML-enabled "description" attribute allowing to embed (basic) HTML and links.

**Comment by kdvolder** [comment]
I'm not quite sure how we can show/use links or html in the current STS wizard. However I definitely feel that the big wall of options is quite daunting and checking a box... a user probably doesn't know what they are getting for that and how to actually use it. So, some kind of pointer to more info would be useful.

However... it all depends on the quality of the information... its maybe less about whether that information is nicely formatted as html or whatnot.

We already have simple descriptions and the UI shows them, but they aren't typically very useful...

I mean I see box called 'foo' and its description says 'Adds foo to project' or something like that, but I still have no clue what a 'foo' is or how I use it in my project.

So... unless we can really good quality content descriptions... I don't feel like investing much time in figuring out how we can make the STS wizard show fancy tooltips with html and links in them.

**Comment by snicoll** [comment]
Closing in favour of PR #279
