### ISSUE TITLE
Automatically configure the build script compilation settings to use -parameters on Java 8

### ISSUE THREAD

**Issue by olivergierke** [spring-io/initializr#170]
To enable Java 8 advanced parameter name detection, the compiler needs to get the `-parameters` flag set. Unfortunately it can't always just be set (i.e. could be set in Boots parent pom already) as it's rejected by Java compilers < 8.

It would be cool if we could tweak the build scripts to automatically do so (i.e. redeclare the compiler plugin in Maven and set the config options, don't know about the Gradle details) in case Java 8 is selected.

**Comment by snicoll** [comment]
Duplicates #157 - Feel free to reopen if you have a concrete idea to address the IDE-build inconsistency.
