### ISSUE TITLE
Lombok is not defined properly with a Gradle build

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#171]
See https://github.com/spring-projects/spring-boot/issues/4842

We should flip that to optional (but the service does not support it yet (#128). Or a different scope that Gradle supports

**Comment by snicoll** [comment]
I am afraid the best I can do at this point is restore the previous configuration (i.e. default scope). This definitely raises the need to fix #128

**Comment by dsyer** [comment]
I guess that means we have to have an answer to the question "what does 'optional' mean for a gradle dependency?". Refs: https://issues.gradle.org/browse/GRADLE-1749, https://github.com/nebula-plugins/gradle-extra-configurations-plugin.
