### ISSUE TITLE
Choosing spring-security and thymeleaf together should add the dependency thymeleaf-extras-springsecurityX

### ISSUE THREAD

**Issue by Traubenfuchs** [spring-io/initializr#172]
Adding that dependency enables template attributes that let you check spring security authentication requirements.
https://github.com/thymeleaf/thymeleaf-extras-springsecurity
There are thymeleaf-extras-springsecurity3 and thymeleaf-extras-springsecurity4.

**Comment by snicoll** [comment]
Spring Initalizr shouldn't decide or build any link between dependencies IMO. Most of the entries in the service are backed by a "starter" of some kind that allows you to bootstrap things. When you need to go in more details you may want to add a set of optional dependencies yourself (read: opt-in). 

But I don't think we should. And certainly not by default. 

Is thymeleaf + spring-security broken (does not start?)

**Comment by Traubenfuchs** [comment]
I get your point -although I don't see myself ever using thymeleaf together with spring security without the extra tags.
The extra attributes are functionally ignored rendered to the output html.
