### ISSUE TITLE
Please add Customization Guide to Wiki

### ISSUE THREAD

**Issue by dmfrey** [spring-io/initializr#183]
It would be helpful to have a customization guide in the wiki for extending this application to be able to add custom nexus or artifactory repositories as well as adding custom dependencies for selection in the final generated projects.

**Comment by snicoll** [comment]
sorry, I didn't get that. What do you want to do exactly?

**Comment by dmfrey** [comment]
It would be helpful in the wiki documention to point users where they should go to extend the application to include their own artificts.

For instance in the initializr-service -> application.yml, it looks like I can define my own groups and artifacts.  Also, in the InitializrConfiguration, it looks like this is the place to add custom, local nexus or artifactory repositories. Actually, this is a good candidate for externalizing the repository configuration so that it can all be handled in the yml file.

It would be worth mentioning this in the documentation.

**Comment by snicoll** [comment]
I am still not sure I understand what you're trying to do. Are you trying to build your own instance of the service? 

I can document a feature but that nexus thing is a guess of yours. Is it an actual feature? If you're not sure maybe we should confirm that first.

**Comment by dmfrey** [comment]
I would like to run the application, locally, behind our firewall, and have
the repositories setup to be our local Nexus repository. This is where we
deploy our own artifacts, as well as cache remove repos like maven central,
the spring repos, etc.

It is not an actual feature, but from what I can tell, that groovy file is
where it is setting up the list of repositories that are populated in the
resulting maven pom and build.gradle files.  These repositories should be
able to be customized, easily, in the application.yml.

**Comment by snicoll** [comment]
I've just [updated the documentation](https://github.com/spring-io/initializr/wiki/Configuration-format). Hopefully this should make things more clear.

Having said that, I am trying to explain you for the third time now that the service does not allow you to add a repository by default. I can't document a feature that does not exist!

Feel free to raise an issue (with a precise description of what you're looking for). If I understand, you'd like all projects generated to have some kind of corporate repo. The only way now would be to add a `repository` section for _all_ dependency group.
