### ISSUE TITLE
Make sure project descriptions line-wrap at a decent length

### ISSUE THREAD

**Issue by odrotbohm** [spring-io/initializr#192]
If you `curl http://start.spring.io`, the description of the individual available dependencies running very long make it kind of hard to digest as terminals might start to line wrap the output.

It would be cool if the descriptions were line-wrapped a decent column to improve legibility.

**Comment by snicoll** [comment]
Consider investigating [`jopt-simple`](https://pholser.github.io/jopt-simple/apidocs/index.html)

**Comment by snicoll** [comment]
Closing in favour of PR #966
