### ISSUE TITLE
Add configuration processor to all new projects

### ISSUE THREAD

**Issue by dsyer** [spring-io/initializr#196]
It seems like we ought to encourage people to use `@ConfigurationProperties` and it works best if the processor is on the classpath.

**Comment by snicoll** [comment]
Meh? I am not a huge fan of adding a non test dependency by default. Adding custom configuration is something you don't do every day (and surely all the users that use the service to quickly bootstrap an application for prototyping won't need that).

**Comment by dsyer** [comment]
That's certainly the other side of the argument. I'm not sure which side I am on (despite this being my request). Anyone else have an opinion?

**Comment by snicoll** [comment]
Doesn't look like it.
