### ISSUE TITLE
Can't create a 'eureka-server' with current production instance of intializr and spring-boot 1.3.2

### ISSUE THREAD

**Issue by kdvolder** [spring-io/initializr#197]
I am trying to create a "Eureka Server" spring boot application using intializer app (as i've done a few times in the past with older version of Boot / initializer)

I'm not sure this is a problem with intializer (does it generates a 'bad' pom? Or is it a problem with Brixton.BUILDSNAPSHOT dependency itself? Or is it that the spring-cloud-netflix docs are outdated and its should be done differently now). I'll let someone else figure that out.

Here's the problem.

I am creating a new app and select "Spring Boot version 1.3.2" and "Eureka Server" dependency. It generates something alright, but... the "@EnableEurekaServer" annotation doesn't appear to be anywhere on the project's classpath.

This means that following these instructions:
http://cloud.spring.io/spring-cloud-static/spring-cloud.html#spring-cloud-eureka-server

Has some code I can't get to compile:

     @SpringBootApplication
     @EnableEurekaServer
     public class Application {
          ...
     }

BTW: I was a bit surprised to find that intializer creates a pom referencing Brixton.BUILDSNAPSHOT. (When I didn't pick a snapshot version of boot). The fact that I'm picking a stable release probably means I want 'stable stuff' not some moving target snapshot versions of some stuff. So maybe that is the problem here?

**Comment by kdvolder** [comment]
> So maybe that is the problem here?

Indeed it was. I refreshed the project forcing an update of maven snapshot dependencies and now all of a sudden the type is there.

So maybe you can close this as 'user error'. Maybe the only valid question that remains is whether there should really be snapshot dependencies added to my pom when I explicitely picked a stable release?

**Comment by snicoll** [comment]
I would defer any of those questions to the Spring Cloud project. There was a problem in the BOM so far and it got fixed and we're waiting for the next milestone to use it.

**Comment by dsyer** [comment]
The milestone is out now isn't it?

**Comment by snicoll** [comment]
Is it? I missed the announcement.
