### ISSUE TITLE
Repositories not added model

### ISSUE THREAD

**Issue by ghillert** [spring-io/initializr#202]
Seems like it is not added right now. Had to add this to `ProjectGenerator.groovy`

```
model['repositories'] = metadata.configuration.env.repositories
```

**Comment by snicoll** [comment]
Sorry, is that a question? What is the problem exactly?

**Comment by ghillert** [comment]
In our use-case we needed to add the `https://repo.spring.io/snapshot` and the `https://repo.spring.io/milestone` repositories to our final pom. It looks like they are by default added to `repositories`:

```
		Env() {
			repositories['spring-snapshots'] = new Repository(name: 'Spring Snapshots',
					url: new URL('https://repo.spring.io/snapshot'), snapshotsEnabled: true)
			repositories['spring-milestones'] = new Repository(name: 'Spring Milestones',
					url: new URL('https://repo.spring.io/milestone'), snapshotsEnabled: false)
		}
```

I also tried adding them manually to the `application.yml` file but no luck. Eventually I ended up adding

```
model['repositories'] = metadata.configuration.env.repositories
``` 
to `ProjectGenerator.groovy` and things worked as expected. Otherwise, it looks like you can also add Maven repositories via the Boms. Need to look at that a bit further but feels like a bit of too much indirection.

**Comment by snicoll** [comment]
I think you are mixing the _available_ repositories and the repositories that must be added for a given `ProjectRequest`.  Spring Initializr will add the repositories that are necessary according to configuration. This is done [here](https://github.com/spring-io/initializr/blob/master/initializr/src/main/groovy/io/spring/initializr/generator/ProjectRequest.groovy#L147-L163). You should override that method or tune whatever creates the request to include the appropriate repositories.
