### ISSUE TITLE
Improve configuration options for non-Java projects

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/initializr#210]
If you select Kotlin or Groovy, you can still configure the Java version. I'm not sure that makes sense. For example, Kotlin always generates Java 6-compatible byte code.

**Comment by snicoll** [comment]
I think it does. Groovy project are configured to support cross compilation. Also please do not restrict the scope in the web ui. If you want to change something you need to impact the meta-data somehow (IDE support)

**Comment by wilkinsona** [comment]
>  please do not restrict the scope in the web ui

Understood. I've updated the title.

> Groovy project are configured to support cross compilation.

What about Kotlin?

**Comment by snicoll** [comment]
I am not educated enough to know but I think it does support cross-compilation. So we should be able to select the java version. 

Truth be told that's the lazy answer. I also find the current arrangement weird but changing that (in the meta-data) would be super hard (constraint, etc)

**Comment by snicoll** [comment]
Kotlin is also using cross-compilation so I am going to close this one for now.
