### ISSUE TITLE
Remove Java-related configuration from build.gradle for Kotlin projects

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/initializr#211]
I don't think target and source compatibility make sense:

```
sourceCompatibility = 1.8
targetCompatibility = 1.8
```

I'm also not sure about the configuration of Eclipse's classpath, but I'd have to look at Kotlin's Eclipse plugin more closely to be sure.

```
eclipse {
    classpath {
         containers.remove('org.eclipse.jdt.launching.JRE_CONTAINER')
         containers 'org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8'
    }
}
```

If the above isn't needed, then it might also be possible to stop applying the Eclipse plugin too.

**Comment by snicoll** [comment]
@wilkinsona the last bits are removed as part of #275 - As for the rest, isn't that there for cross-compilation? We do support java+groovy for Groovy-based projects. Doesn't it make sense for Kotlin-based projects? ping @sdeleuze

**Comment by sdeleuze** [comment]
While mixed Java + Kotlin project are common on existing Java project, I tend to think most Kotlin newly created projects will just use Kotlin code, so indeed that could make sense to remove `sourceCompatibility` and `targetCompatibility`.

**Comment by mhalbritter** [comment]
With the switch to toolchains in https://github.com/spring-io/initializr/issues/1227 these bits have been removed.
