### ISSUE TITLE
Allow specifying a custom parent pom

### ISSUE THREAD

**Issue by ryangardner** [spring-io/initializr#220]
As mentioned in [the docs](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-maven-without-a-parent) there are times when you don't want to use the spring boot parent pom.

For our internal use, we have a different parent pom we use - it would be very nice if we could pass in the parent pom group / artifact / version as some form of advanced parameter and then get it to generate the pom with the ```<artifactId>spring-boot-dependencies</artifactId>``` in the dependencyManagement section and a ```<spring-boot.version>``` property in the properties section that could be used to override things that were set in the parent pom... 

We are going to do this on our fork of the initializr - would this be something that would be valuable if we did it and submitted a pull request for it?  

I think we'd have to do some additional work to the UI to put a checkbox for the "use custom parent" that would then display the fields for the group / artifact / version for the custom parent pom (and would only show up if they are selecting the "maven" project type)

**Comment by snicoll** [comment]
While I understand why you'd need that kind of thing, I am not keen on adding such level of customization in the UI. Having said that, a PR that allows to configure this on a particular instance would be nice.

**Comment by ryangardner** [comment]
That'd actually be easier - and you're right, we don't really have any need for it in the UI either, just a global level thing that we (or others) could configure in the application.yml for the service should be pretty straightforward.

**Comment by snicoll** [comment]
Waiting for the PR then :)

**Comment by jasonrberk** [comment]
it looks like this was merged last year.  Is this something I can CURL https://start.spring.io/starter.tgz and make use of via a -d arg?  As I understand the gist of it, while the UI doesn't give any options to support it, if you send the correct options, the actual project generator will allow you to specify a custom parent.  If I can get some help to figure this out, I'd be happy to update the [the curl examples](https://github.com/spring-io/initializr/blob/master/initializr-generator/src/main/resources/templates/curl-examples.txt)

**Comment by snicoll** [comment]
> Is this something I can CURL

No. You have the history in this issue

>  I am not keen on adding such level of customization in the UI. Having said that, a PR that allows to configure this on a particular instance would be nice.

So that's what we have. A particular instance can deviate from the parent but you can't customize this on a request basis. If you have more questions, let's chat on Gitter since you're there already.

**Comment by jasonrberk** [comment]
yes, I misunderstood what "instance" referred to.  Thanks for replying
