### ISSUE TITLE
Add Ability to Customize UI Template

### ISSUE THREAD

**Issue by ghillert** [spring-io/initializr#227]
When using Initializr as a library, the UI template is hard-coded and cannot be easily customized. We have the need to customize the placeholder text for the Dependencies.

![image](https://cloud.githubusercontent.com/assets/685363/15055900/10b01246-12dd-11e6-99b4-d9add955af7c.png)

**Comment by snicoll** [comment]
@bclozel and I have been brainstorming this recently as we want to add some links on start.spring.io to the guides and other resources. The outcome of that discussion is that any attempt to customize the design of the template should lead to your own template, overriding the one that's provided by default.

I can imagine plenty of customizations for the title, the head line, the header of this and that. Let's not enter that territory. 

Brian, please correct me if I missed anything.
