### ISSUE TITLE
Consider adding strict dependency validation

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#234]
Currently if one invokes the service asking for dependency `foo` and `foo` does not exist we create automatically a starter for it (`spring-boot-starter-foo`). This mechanism was put in place because we don't know all starters out there and to offer a nice fallback for users who know what they're doing. 

It turns out that we've asked 3rd party starters to not be named `spring-boot-starter-foo` but rather `foo-spring-boot-starter` or something else that doesn't start with `spring-boot`. So that feature isn't really helpful anymore and maybe we should reject such requests in the purpose of warning the user the dependency isn't known (rather than generating something that might break).

See also https://github.com/spring-projects/spring-boot/issues/6061

**Comment by kevinhooke** [comment]
It would be great to have at least a warning message if the passed name for a starter is not valid - without this like I mentioned on my ticket, it's easy to generate a pom.xml for dependencies that don't exist (e.g. with a minor typo in the name) and then waste time trying to work out what's wrong :-)
