### ISSUE TITLE
different results from spring boot CLI vs web app

### ISSUE THREAD

**Issue by mattluce** [spring-io/initializr#237]
Using CLI with a dependency of "hsqldb" returns different results in the web UI vs the CLI

web UI correctly generates:
runtime('org.hsqldb:hsqldb')

While CLI generates:
compile('org.springframework.boot:spring-boot-starter-hsqldb')

using the following command:
./spring init \
      --dependencies="${SPRING_INIT_DEPENDENCIES}" \
      --build=gradle \
      --format=project \
      --packaging=war \
      --groupId="${PROJECT_PACKAGE}" \
      --package-name="${PROJECT_PACKAGE_NAME}" \
      --description="${PROJECT_NAME} project" \
      --version="${PROJECT_VERSION}" \
      --extract "${PROJECT_PATH}"

**Comment by bclozel** [comment]
I think the proper dependency name is `hsql`.

**Comment by snicoll** [comment]
And what difference would that be? The _label_ on the Web UI is not an identifier. 

As Brian said, `hsql` is the id for that dependency. You can `curl start.spring.io` if you want to have the list of supported identifiers.

**Comment by mattluce** [comment]
Thanks. It was not clear where to get the list of supported identifiers.

**Comment by snicoll** [comment]
Also, `spring init --list` since you're using that.
