### ISSUE TITLE
Integration tests won't run unless you have Firefox install

### ISSUE THREAD

**Issue by ohiocowboy** [spring-io/initializr#245]
Test cases in the `ProjectGenerationSmokeTests` fail if Firefox is not installed.

**Comment by snicoll** [comment]
That is a requirement as described in the [readme](https://github.com/spring-io/initializr#building). Not sure what I can do about it. Do you?

**Comment by ohiocowboy** [comment]
Stephane, I was just creating a pull request for this. I do have a work around that tests for the driver to be installed and the using `Assume` it ignores the tests.

**Comment by snicoll** [comment]
cool :) No need to create an issue if you have the code working, the PR is enough. Thanks!

Closing in favour of the PR #245

**Comment by ndrone** [comment]
good to know
