### ISSUE TITLE
WAR packaging doesn't leave application.yml in the classpath

### ISSUE THREAD

**Issue by dogeared** [spring-io/initializr#248]
Steps to reproduce:

1. Build the project as a WAR file

    ```
    cd initializr-service
    spring war start.war app.groovy
    ```

2. Drop the war file into tomcat for deployment

    ```
    cp start.war /opt/tomcat/webapps/ROOT.war # install as the root webapp
    ```

3. Browse to the application

    ```
    http://localhost:8080/
    ```

    You will see that `Generate a` dropdown is empty:

    ![image](https://cloud.githubusercontent.com/assets/364562/16655994/d845b81e-442a-11e6-9e01-d01db87fea08.png)

    This is because `http://localhost:8080/ui/dependencies.json?version=1.3.6.RELEASE` returns an empty list:

    ```
    {"dependencies":[]}
    ```

4. Copy the `application.yml` file into the classpath of the app

    ```
    cp application.yml /opt/tomcat/webapps/ROOT/WEB-INF/classes/
    ```

    restart `tomcat` and then browse to the application once again

    ```
    http://localhost:8080/
    ```

    Now, you will see that the `Generate a` dropdown is populated and the search bar works:

    ![image](https://cloud.githubusercontent.com/assets/364562/16656147/9474b328-442b-11e6-8f79-2c2aa94eee90.png)

    `http://localhost:8080/ui/dependencies.json?version=1.3.6.RELEASE` now returns the full list based on the `application.yml` being in the classpath.

**Comment by snicoll** [comment]
The `spring` command is a feature of Spring Boot so this shouldn't be reported here, really. I've created https://github.com/spring-projects/spring-boot/issues/6351 for you.
