### ISSUE TITLE
Maven/gradle dependencies block view on the initializr home page

### ISSUE THREAD

**Issue by eitansuez** [spring-io/initializr#249]
Spring project landing pages (e.g. http://projects.spring.io/spring-boot/ ) all contain a neat little widget that displays a project's dependencies either in maven or gradle format (controlled by a maven <-> gradle slider widget).  These widgets also sport a "copy to clipboard" button that makes it real easy to grab the dependencies and insert them into one's [existing] project's build file.  For the sake of this conversation, let's call this widget the "dependencies view" widget.

The start.spring.io landing page has a view of selected dependencies that grows/shrinks as one adds/removes dependencies to the project definition they're building.  this view is straightforward:  it displays the name of the dependency ("web").  it'd be nice if a second view of those dependencies were rendered using the dependencies view widget.  that would make it really easy to paste dependencies to an existing project's build file.

use case:
oftentimes i'll generate a project but forget to add another dependency.  ideally my IDE should be really good about autocompletion in my build file and helping me add the dependency, but i often find it easier to go back to start.spring.io and type "web" or "devtools" or whatever in the dependencies input control.  the problem is that, to grab this dependency i now need to "generate project", and uncrack my zip file to get at those deps.  now it's true that i can just use the spring cli or the start.spring.io's rest api to just grab the build file.  but i like the web ui.  anyhow, i think it'd be a nice addition to that landing page.

**Comment by snicoll** [comment]
I know for a fact that STS is planning to have that kind of feature (or maybe that's already available @ kdvolder). I raised that feature with @yanncebron for IntellIJ IDEA as well. 

I am really not keen to complexify the web ui at this point. There are others thing I'd like to do beforehand. Do we agree that IDE support would be better for this?

**Comment by eitansuez** [comment]
my main objective was to communicate this thought.  feel free to close this issue.  thanks!

**Comment by dsyer** [comment]
STS can do it (right click on the pom). But personally I'm fine with leaving the issue open in case anyone wants to do some work to extend the web UI.

**Comment by kdvolder** [comment]
I'm not quite sure I follow all that @eitansuez was trying to explain. It sounds more complicated than what we have. However STS does already offer a way to 'go back' to initializr wizard again and use it to 'edit' project dependencies.

You right-click the project's pom.xml find the menu 'Edit Starters'. This opens a wizard very similar to the wizard used to create the project. The difference being that it has some boxes already checked based on the current dependencies and you can uncheck or check other boxes. Upon closing the wizard the changes are applied to the pom.

See here for a bit more detail on what STS currently provides: 
http://docs.spring.io/sts/nan/v373/NewAndNoteworthy.html#editstarters

**Comment by eitansuez** [comment]
hi kdvolder, i think you understood me right (i tend to be verbose).  distilled version:
web ui: pick some dependencies, copy to clipboard. :-)

**Comment by snicoll** [comment]
@eitansuez can you please answer my question? I don't get why you'd want to a web ui if the IDE supports it. I am not saying it does right now but I think we should implement that feature there. 

Thoughts?

**Comment by eitansuez** [comment]
habit?  for one i don't use sts.  and intellij is awesome in some ways and a pita in others.  perhaps there's no good answer.  i have a rigid mind ;-)

**Comment by snicoll** [comment]
Fair enough. If you want to make this right, it's much harder than what you describe. If the dependency is linked to BOM(s) then you need to provide the definition for that. And if the dependency you've chosen is a SNAPSHOT/milestone (less likely) you need a `repositories` definition. I am sure you'd hate copy/pasting something from the web ui with your build  breaking as a result. I am strongly convinced this is the wrong place to add the feature but I am happy to be proven wrong.

**Comment by dsyer** [comment]
The server can render a pom.xml or build.gradle, so adding this feature in the UI wouldn't be very hard IMO. It's just an XHR request to get the current config and inserting it in a `<pre>` element. I don't think it needs to be much more complicated than that.

**Comment by eitansuez** [comment]
i had a little time on my hands and put together a quick and dirty prototype that i pushed to http://eitan-start.cfapps.io/
the design is a little different.  i grab the /dependencies directly so i can render the dependencies block client-side.  this implementation is does not take into account the bom relationship.  the other (perhaps better) way to go is as dr syer suggests, which is to hit the endpoints that return the pom.xml or build.gradle files where the logic already resides.

**Comment by snicoll** [comment]
@eitansuez cool! Unfortunately, the limitation you exposes is the issue really. Adding a cloud dependency requires the cloud bom so copy-pasting the current bits in an existing project _will_ break. That's the core reason why I am not keen on doing this. 

Also you don't want that out-of-the-box so you need a way to signal you want this to be displayed.

**Comment by eitansuez** [comment]
yeah, i agree, this opens a can of worms.   locating or autocompleting dependency declarations is useful but perhaps it doesn't belong in the initializr.

**Comment by snicoll** [comment]
Let's reopen this if someone comes up with a different approach. Thanks!
