### ISSUE TITLE
Remove hard-coded version for Spring Cloud Task

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#256]
Let's make  sure we remove the hard-coded version of the cloud-task starter once we upgrade to Spring Cloud Brixton SR4 has the bom will contain the starter (see https://github.com/spring-cloud/spring-cloud-task/issues/176)

**Comment by snicoll** [comment]
@dsyer you just upgraded to SR4. Does that release include the fix for https://github.com/spring-cloud/spring-cloud-task/issues/176?

**Comment by dsyer** [comment]
No, we haven't had a new release from spring-cloud-task yet. Ping @mminella on 1.0.2.

**Comment by snicoll** [comment]
1.0.2 is out. When are you going to include that bom in the `spring-cloud-dependencies` bom @dsyer?

**Comment by dsyer** [comment]
The BOM is already included AFAIK. We were just waiting for the task release with the fixed bom.

**Comment by snicoll** [comment]
uh? We have an explicit bom import for spring cloud task. In any case, we need a new service release for Brixton then. SR5 right?

**Comment by dsyer** [comment]
SR5 is already out with spring-cloud-task 1.0.2. We need 1.0.3 (at least) and Brixton.SR6 to fix this.

**Comment by snicoll** [comment]
The version has been removed already. Can't remember when we didi that.
