### ISSUE TITLE
Consider enabling fork by default for the run goals

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#265]
Devtools requires the run process to be forked to work properly so maybe we should do that by default. Any downside?

See https://github.com/spring-projects/spring-boot/issues/3315

**Comment by amingilani** [comment]
+1 I was lost when I started with Spring Boot.

**Comment by snicoll** [comment]
I've decided to do this in the maven plugin directly instead, see https://github.com/spring-projects/spring-boot/issues/5137
