### ISSUE TITLE
Java 1.6 with web starter needs extra configuration

### ISSUE THREAD

**Issue by imgx64** [spring-io/initializr#268]
When selecting Java version 1.6 and web started, the [resulting project](http://start.spring.io/starter.zip?type=maven-project&bootVersion=1.4.0.RELEASE&baseDir=demo&groupId=com.example&artifactId=demo&name=demo&description=Demo+project+for+Spring+Boot&packageName=com.example&packaging=jar&javaVersion=1.6&language=java&autocomplete=&style=web&generate-project=) cannot be run with Java 6 by default and throws `java.lang.UnsupportedClassVersionError: javax/annotation/ManagedBean : Unsupported major.minor version 51.0`.

The following needs to be added to pom.xml to make it run:

```
    <properties>
        ...
        <tomcat.version>7.0.70</tomcat.version>
        <jackson.version>2.6.7</jackson.version>
    </properties>

    <dependencies>
        ...
        <dependency>
            <groupId>org.apache.tomcat</groupId>
            <artifactId>tomcat-juli</artifactId>
            <version>${tomcat.version}</version>
        </dependency>
    </dependencies>
```

Only `tomcat.version` is required for Spring Boot <1.4.0. The rest are required for Spring Boot >=1.4.0.

Note that Jackson 2.7.x does work with Java 6, but the documentation says it requires Java 7, so I think it's safer to stick to 2.6.x.

**Comment by snicoll** [comment]
@imgx64 thanks for the report. I've created #6536 for the Jackson issue. Regarding Java6, I was about to actually drop support. Is there any reason why you need to use Java6 for _new projects_. It's EOL for quite a while now.

I am not super keen to bring that complexity here and it could be an additional reason to remove Java6 support. Thoughts?

**Comment by imgx64** [comment]
I don't really use it for new Java 6 projects, I just use it as a convenience to create a demo project to isolate hard-to-find bugs from existing projects. In fact, the reason I used it this time was that upgrading an older Java 6 application to Spring Boot 1.4.0 broke the application because of the newer Jackson version.

I don't mind removing Java 6 from Initializr, as long as the [How to use Java 6](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-use-java-6) section in the documentation is kept up to date. But the decision to remove Java 6 is up to you.

As an aside, Java 6 is only *publicly* EOL. Oracle, IBM, and Red Hat (and probably others) still support it for existing contracts. The reason we're still using it for not-new-yet-not-legacy applications is that we didn't want to move to Java 7 and then again to Java 8. We use WebSphere and IBM only just recently released support for Java 8.

**Comment by snicoll** [comment]
There hasn't been much traffic on this one and Java6 has been removed from the list in the meantime (see #538)
