### ISSUE TITLE
Typo in deployment instructions

### ISSUE THREAD

**Issue by jasonmai** [spring-io/initializr#272]
The current deployment instructions (August 11th, 2016) states to:

> Make sure first that the jar has been created:
>
> `$ mvn package`
> Once the jar has been created, you can push the application:
>
> `$ cf push your-initializr -p target/initializr-service.jar`

However, judging by the main maven `pom.xml` [modules section](https://github.com/spring-io/initializr/blob/master/pom.xml#L45-L49) and the [profiles section](https://github.com/spring-io/initializr/blob/master/pom.xml#L190), the `initializr-service.jar` will not have been created unless the `full` profile is specified. i.e.:
```
$ mvn clean package -P full
```

**Comment by snicoll** [comment]
That's what that `mvn package` refers to. "Make sure first that the jar has been created" is what I intended. I guess not saying you should run that from `initializr-service` can be confusing. I'll fix that, thanks.
