### ISSUE TITLE
build.gradle workaround for eclipse JRE container is obsolete and breaks project

### ISSUE THREAD

**Issue by kdvolder** [spring-io/initializr#275]
The generated build.gradle has this crufty bit of code in it:

```
eclipse {
	classpath {
		 containers.remove('org.eclipse.jdt.launching.JRE_CONTAINER')
		 containers 'org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8'
	}
}
```

I think this was added as a workaround for gradle not properly configuring the container itself (i.e. it just used the default container rather than the one that properly reflects the source/target compiler level).

It looks like that even if we remove this bit of cruft now, the project still imports correctly. So this workaorund is not needed anymore. Even worse, it actually breaks the import for STS Gradle tooling. Somehow it results in a duplicate entry in the classpath. Two Java 1.8 containers end up being added. Eclipse doesn't like this and flags it as an error and refuses to build the project.

**Comment by snicoll** [comment]
Given how many projects are generated daily, I am surprised that it breaks projects and nobody complained about it. I have no opinion and I am happy to remove it.

**Comment by kdvolder** [comment]
It breaks only for import into Eclipse projects still works fine on CLI. And it only breaks import using STS gradle tooling, not BuildShip. I don't know why, probably because BuildShip doesn't execute the tasks like 'cleanEclipse eclipse' during project import.

Anyhow... please remove the workaround. It does only harm right now and isn't needed anymore.
