### ISSUE TITLE
Set project name and version globally, rather than just for the artifact

### ISSUE THREAD

**Issue by tomwhoiscontrary** [spring-io/initializr#280]
If i initializ a Gradle project, then the project's name and version are set up [on the jar or war task](https://github.com/spring-io/initializr/blob/fb7b8eb5cb8cf4816ead7b570f6c634c9d0a7ead/initializr-generator/src/main/resources/templates/starter-build.gradle#L26):

```
<% if (packaging=='war') {  %>war<% } else { %>jar<% } %> {
    baseName = '${artifactId}'
    version = '${version}'
}
```

I would say that the proper way to set these is globally. You can set the version in the build.gradle:

```
version = '${version}'
```

But for the name, you need to generate a settings.gradle:

```
rootProject.name = '${version}'
```

If you use the [`gradle init`](https://docs.gradle.org/current/userguide/build_init_plugin.html) command, that's how it's done there.

I think Initializr should do this too. It's something i always have to tweak manually after initializng. Is there a reason to do it the way it is currently done that i don't know about?

If not, i am happy to try to submit a PR to change this.

**Comment by snicoll** [comment]
I didn't get the `rootProject.name = '${version}'` and I'd prefer not generate an extra file unless I really have to. What concrete problem does this cause?

**Comment by snicoll** [comment]
Closing due to lack of feedback
