### ISSUE TITLE
Unable to override template files.

### ISSUE THREAD

**Issue by ndrone** [spring-io/initializr#281]
When trying to override the `home.html` template within the `initializr-web` project by using my own `home.html` within my `initalizr-service` module. The application still displays the original one.

**Comment by snicoll** [comment]
On gitter, @shakuzen mentioned he had the same need and it's working for him. Looks like it should work but maybe your setup is different? @ndrone can you look at that conversation and let us know a bit more about your project?

**Comment by ndrone** [comment]
Not a bug. I had a typo in the templates directory.
