### ISSUE TITLE
Adding Narayana dependency

### ISSUE THREAD

**Issue by gytis** [spring-io/initializr#282]
Would it be possible to add Narayana dependency to start.spring.io? It's documented here: http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-jta.html#boot-features-jta-narayana.

Thanks,
Gytis

**Comment by gytis** [comment]
I've raised a pull request just in case: https://github.com/spring-io/initializr/pull/283. Hope it has all the required fields.

**Comment by snicoll** [comment]
Duplicate #283 - @gytis if you intend to submit a PR, the PR is sufficient, no need for a separate issue.
