### ISSUE TITLE
Register stats for Netbeans

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#290]
Netbeans has a [nice integration with Spring Boot](https://github.com/AlexFalappa/nb-springboot) that includes a wizard to generate project using Spring Initializr. We should find a way to detect requests coming from Netbeans to reflect the stats accordingly.

**Comment by dsyer** [comment]
Looks like they have a User-Agent header "nb-springboot-plugin/${version}" (https://github.com/AlexFalappa/nb-springboot/blob/06eebedb4fa5b18507b419c6e287d00ce57da436/src/main/resources/com/github/alexfalappa/nbspringboot/projects/initializr/Bundle.properties#L24).

**Comment by snicoll** [comment]
I know, I've installed netbeans to confirm this (Netbeans on MacOS is no fun at all).

**Comment by AlexFalappa** [comment]
@dsyer, @snicoll Ihave followed the recommendations on the wiki (https://github.com/spring-io/initializr/wiki/Metadata-format).

Out of curiosity, why is NetBeans so terrible on Mac ?  I'm using it on Linux and on Windows and it's not that bad).

**Comment by AlexFalappa** [comment]
Another question, are the initializer statistics publicly available?

I'd love to see the "Market share" of my plugin.

**Comment by snicoll** [comment]
@AlexFalappa thanks for this plugin by the way. The fact you use a proper user agent is the reason we can add explicit support for it here!

> Another question, are the initializer statistics publicly available?

They are not at the moment.
