### ISSUE TITLE
Communicate why an entry is disabled

### ISSUE THREAD

**Issue by kjarnet** [spring-io/initializr#293]
On start.spring.io, the Velocity templating engine is disabled without any explenation. If it's not supported in Spring Boot 1.4.1 wouldn't it be less confusing just to remove it totally? The best, though, would probably be to show a textual explanation of why it's disabled, if possible.

**Comment by bclozel** [comment]
Velocity has been deprecated in Spring Framework, [see the migration wiki](https://github.com/spring-projects/spring-framework/wiki/Migrating-to-Spring-Framework-4.x#third-party-dependencies).

**Comment by snicoll** [comment]
and the [Spring Boot release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes#deprecations-in-spring-boot-14)

**Comment by kjarnet** [comment]
ok, thanks :) I still think it would be a big improvement to ux of the start.spring.io to somehow communicate why that option is disabled though... Just wanted to share my experience with the site... Feel free to close the issue if you disagree or won't prioritize (which I fully understand).

**Comment by snicoll** [comment]
I think it's a nice idea to add some more information as why it is disabled. Right now we use version range (and there's no information about it in the site either). We could add some deprecation information as well.

So going to advanced and hovering on the disabled velocity would be enough for you or do you have something else in mind?

**Comment by kjarnet** [comment]
Hover info was my first thought as well, only drawback is that it's probably not very mobile-friendly.. But this is probably not a site heavily used from mobile :p

**Comment by snicoll** [comment]
@bclozel is the mastermind of the UI so we'll do what he says 😄

**Comment by bclozel** [comment]
I'm not against displaying that deprecation/compatibility information in a tooltip.
Right now, we're now displaying incompatible starters in the auto-complete field, but that could change if we think this is a mistake.

Let's add those information fields in the metadata and that tooltip, then!
