### ISSUE TITLE
spring cloud contract is outdated and without gradle plugin

### ISSUE THREAD

**Issue by me3x** [spring-io/initializr#294]
Spring cloud contract is now GA with 1.0.0.RELEASE, but initializr generates dependency on old milestone version.

mavenBom "org.springframework.cloud:spring-cloud-contract-dependencies:1.0.0.M1"

I expected it to add gradle plugin as well, because it's pretty much useless without it.

classpath("org.springframework.cloud:spring-cloud-contract-gradle-plugin:1.0.0.RELEASE")

**Comment by dsyer** [comment]
I fixed the BOM there, but adding the plugin is out of scope for now (there are features in Spring Cloud Contract that don't require it anyway, so it's not completely useless).

**Comment by snicoll** [comment]
We're still considering how we can tune the build according to the chosen dependencies. #194 is an attempt to do this for restdocs. Once we have that infra, we can easily add it for this plugin as well.
