### ISSUE TITLE
Add dependency entry for the configuration processor

### ISSUE THREAD

**Issue by tokuhirom** [spring-io/initializr#301]
When I'm writing an application on spring-boot, I'm writing my configuration class,  annotated by `@ConfigurationProperties`.

Enabling `spring-boot-configuration-processor` is bothersome.

I recommend enabling `spring-boot-configuration-processor` by default.

http://docs.spring.io/spring-boot/docs/1.4.1.RELEASE/reference/html/configuration-metadata.html#configuration-metadata-annotation-processor

```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-configuration-processor</artifactId>
    <optional>true</optional>
</dependency>
```

**Comment by snicoll** [comment]
Need #128

**Comment by snicoll** [comment]
@tokuhirom this was already declined in #196 but adding an option at least is a great idea.
