### ISSUE TITLE
Add support for Flowable starter

### ISSUE THREAD

**Issue by vpavic** [spring-io/initializr#302]
With Activiti now being [forked to Flowable](http://www.flowable.org/blog/2016/10/12/flowable-and-activiti.html), and 5.22.0 being [released as drop-in replacement](http://www.flowable.org/blog/2016/10/13/flowable-5.22.0-release.html) for Activiti 5.21.0, Initializr should add support for new coordinates.

**Comment by snicoll** [comment]
>  Initializr should add support for new coordinates.

No it shouldn't: this is rather new and we shouldn't add it until all the dust settles. Thanks for raising it though. I am still unsure what to do about the activiti one.

**Comment by vpavic** [comment]
To provide some updates on the subject since this issue was opened:

- Activiti had [a single stable release](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.activiti%22%20AND%20a%3A%22activiti-engine%22) (5.22.0 on Nov 4th)
- Flowable had [two stable releases](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.flowable%22%20AND%20a%3A%22flowable-engine%22) (5.22.0 on Oct 13th and 6.0.0 on Feb 15th)
- Flowable repo is much more active since the split (note that the activity comparison isn't straightforward, since Activiti's `master` is 5.x and 6.x development is in separate branch while the situation with Flowable is the opposite)

**Comment by snicoll** [comment]
Thanks for the proposal. 

Activiti is not used very much so we've decided to remove it. As a consequence, we won't add the Flowable starter either.

**Comment by ahmedsafwat** [comment]
Is this issue opened to add Flowable or to remove Activiti?

**Comment by ahmedsafwat** [comment]
I don't think the outcome was just declined you missed the last part another issue created to remove Activiti
