### ISSUE TITLE
Resources are cached by browsers even when changed

### ISSUE THREAD

**Issue by shakuzen** [spring-io/initializr#321]
Initially [reported on Gitter](https://gitter.im/spring-io/initializr?at=583f78c616207f7b0ec8e1ae):

When I deployed the latest changes of the library on our internal Initializr, I realized the [CSS (spring.css)](https://github.com/spring-io/initializr/blob/master/initializr-web/src/main/resources/static/css/spring.css) and [JS (start.js)](https://github.com/spring-io/initializr/blob/master/initializr-web/src/main/resources/static/js/start.js) loaded was still the old version (cached by my browser - Chrome).

I noticed the same thing happening on http://start.spring.io/ with the last release (yesterday?) until I used Chrome's developer tools to disable the browser cache.

**Comment by bclozel** [comment]
We can fix that by configuring [a resource chain](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-web-applications.html#boot-features-spring-mvc-static-content). But we also need something to write the appropriate links in the rendered HTML: a `ResourceUrlEncodingFilter` for Servlet-based template engines or a custom template helper for others.

I don't know if the current template engine allows this, I'll git it a try.
