### ISSUE TITLE
Add support for Spring Cloud Dalston

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#324]
While working on #318, I realized that we don't have a way to generate a project with `Dalston`. Is that too soon? If not, should we make that available as of Spring Boot `1.5.x`? And perhaps the next generation of data flow should be aligned with that as well?

ping @dsyer @sabbyanandan

**Comment by dsyer** [comment]
Dalston M1 is coming soon , so snapshots should be available to 1.5.0.BUILD-SNAPSHOT projects.
