### ISSUE TITLE
eclipse errors | in pom.xml

### ISSUE THREAD

**Issue by gangakrishh** [spring-io/initializr#332]
error if import this project into eclipse

```
Description	Resource	Path	Location	Type
Plugin execution not covered by lifecycle configuration: org.codehaus.gmavenplus:gmavenplus-plugin:1.5:testCompile (execution: default, phase: test-compile)	pom.xml	/initializr-generator	line 5	Maven Project Build Lifecycle Mapping Problem
```

I've fix  for this need to add `<pluginManagement>` in build like below

 
```
<pluginManagement>
    <plugins>
	<plugin>
	    <groupId>org.codehaus.gmavenplus</groupId>
	    <artifactId>gmavenplus-plugin</artifactId>
        </plugin>
    </plugins>
</pluginManagement>
```

**Comment by gangakrishh** [comment]
![eclipse_errors_spring_initializr](https://cloud.githubusercontent.com/assets/884130/21289715/07fd9744-c472-11e6-8631-45fbf249a622.png)

**Comment by dsyer** [comment]
I don't think that would actually fix anything. There's is a quick fix in the Pom editor though, and I think it gives you 3 choices. It's up to you to choose one. The project probably works fine, both on the command line and in Eclipse.

Can you paste in the exact request you used to generate the project if you if you need someone to check that it works, please?

**Comment by gangakrishh** [comment]
I use eclipse Mar2 Release (4.5.2) Build id: 20160218-0600, when i download spring initializr code and import as mvn project into eclipse i get 16 errors in problems tab
```
Description	Resource	Path	Location	Type
Plugin execution not covered by lifecycle configuration: org.codehaus.gmavenplus:gmavenplus-plugin:1.5:testCompile (execution: default, phase: test-compile)	pom.xml	/initializr-generator	line 5	Maven Project Build Lifecycle Mapping Problem
```

if add <pluginManagement> tag before <plugins> in each pom file. errors are fixed

attaching diff for same
[pom_diff.txt](https://github.com/spring-io/initializr/files/664368/pom_diff.txt)

**Comment by dsyer** [comment]
Not sure how that would help (you switched off all the plugins and moved them to plugin management). You need to get the groovy extensions to m2e to make it work (STS comes with an option to install them I think). And you might also need a quick fix to make the error markers go away.

**Comment by gangakrishh** [comment]
if i move plugins to plugin management errors in eclipse are cleared.. 

i got recommendation from here

http://stackoverflow.com/questions/6352208/how-to-solve-plugin-execution-not-covered-by-lifecycle-configuration-for-sprin

**Comment by snicoll** [comment]
Let's continue this discussion on stackoverflow please. This tracker is not meant to address IDE configuration issues. 

@gangakrishh can you please create a thread on StackOverflow with the problem you're facing in STS. As Dave said, you need to install the groovy extensions to m2e.
