### ISSUE TITLE
Would it be possible to expose PostProcessors after project generation?

### ISSUE THREAD

**Issue by zhuchenwang** [spring-io/initializr#339]
I am running my own initializr instance. I want to add more files to the project after generation. My current way is extend the ProjectGenerator. However, is it possible to expose some post-processor hook after the project generation something similar to `ProjectRequestPostProcessor`

**Comment by snicoll** [comment]
Not at the moment. Our plan is to release 0.2 and then move on with a major overhaul of the project generation process, including ways to fine-tune how the project is generated. I've created #340 to materialize this.
