### ISSUE TITLE
Add checkbox for Spring Cloud Deployer Cloud Foundry

### ISSUE THREAD

**Issue by dsyer** [spring-io/initializr#345]
To run Spring Cloud Data Flow in Cloud Foundry (which we'd like to promote), we need the deployer, which in turn requires reactor 3.0.x. I know a better solution might be to persuade one of the reactor consumers to re-jar their dependencies, but for now we can fix it by overriding the `reactor.version` in the build config.

There is currently only one released version of spring-cloud-deployer-cloudfoundry (1.0.0.RELEASE) and AFAIK it is not in any BOM. It can be paired with Spring Boot the same way that Dataflow is (i.e. 1.3.2 or above).

**Comment by snicoll** [comment]
We're currently discussing a dedicated workflow for data flow which will include the deployer. We can reopen if we change our mind.
