### ISSUE TITLE
Specify default tasks for Maven and Gradle

### ISSUE THREAD

**Issue by mraible** [spring-io/initializr#346]
For Maven, I'd suggest `spring-boot:run` and for Gradle, `bootRun`. This would make it easier to demo apps created from start.spring.io.

**Comment by snicoll** [comment]
It is an interesting idea for a demo but I wonder if that wouldn't have an impact for those creating projects for other means. Perhaps others can comment?

**Comment by mraible** [comment]
I don't think this changes anything because users have to type full commands now or they get an error. We do this in JHipster.

**Comment by wilkinsona** [comment]
I suspect if you ask 10 different people what the default tasks would be, you'll get 10 different answers. Personally, I would never want `bootRun` or `spring-boot:run` to be the defaults. If I configure them, I prefer them to be what's run on CI so that it's trivial for developers to run the same build locally.

**Comment by mraible** [comment]
Maybe we should do a Twitter poll (or some kind of survey) with some options?

**Comment by snicoll** [comment]
This changes something. We would advertize and provide what a good default goal should be for projects generated on the site. I am with Andy on this one, if there isn't a clear consensus as what the default goal must be, then we shouldn't provide one in the first place.

I've done a Twitter poll recently and I am not keen to decide anything based on the outcome of it. I also think `spring-boot:run` is quite narrowed to the "demo" use case. We, in Spring Boot land, prefer users to start the app from their IDE.

**Comment by dsyer** [comment]
+1 for the status quo (and agree with andy that if there is a default it should be oriented to CI, not demos)

**Comment by mraible** [comment]
Isn't the whole point of start.spring.io to provide the least friction possible to get started with Spring Boot (and related starters)? I'm just suggesting we reduce the friction of getting started. People can easily change the default goal/task - or remove it altogether. We've had my suggestions as the default in JHipster for at least a year with no complaints.

**Comment by wilkinsona** [comment]
> I'm just suggesting we reduce the friction of getting started. People can easily change the default goal/task - or remove it altogether.

Adding something that we believe many people may want to change or remove altogether sounds like an increase in friction to me.

**Comment by snicoll** [comment]
Thanks for the suggestion but I am not keen to add a default goal/task at this time.
