### ISSUE TITLE
Provide multi-project Gradle project when choosing Gradle

### ISSUE THREAD

**Issue by berlin-ab** [spring-io/initializr#351]
Each time I download a Gradle project from start.spring.io I go through some steps to transform it into a multi-project gradle build (https://docs.gradle.org/current/userguide/multi_project_builds.html). It would be nice if the downloaded zip file did this setup by default.

**Comment by wilkinsona** [comment]
I'm not sure that's generally applicable is it? What about small apps where you only want a single module? I suspect it'll be impossible to please everyone here.

**Comment by dsyer** [comment]
I suppose it could be a checkbox: download a project as a subdirectory with a build configuration at the top level. E.g. with maven there could be a parent pom. BTW check out this new guide https://spring.io/guides/gs/multi-module/ (feedback welcome).

**Comment by snicoll** [comment]
It's a though call to make but I am with Andy on that one.

**Comment by berlin-ab** [comment]
@snicoll @wilkinsona @dsyer I was thinking along these lines:

Keep the initial project simple, but make more complex projects easier by default. Also, we have an opportunity to display a powerful/useful tool and encourage its use.

**Comment by wilkinsona** [comment]
@berlin-ab How can we keep the initial project simple and make it a multi-project build? They're competing goals, aren't they?

**Comment by berlin-ab** [comment]
By adding a settings.gradle file that includes a directory (what is now the root directory). I think that is still a simple and understandable default, but is easier to extend into multiple modules quickly.

**Comment by berlin-ab** [comment]
I think multi-module projects are an important way to control complexity of a codebase as it grows, as part of the evolution of a project is the creation of boundaries and the extraction of reusable libraries. Take initializr itself for example, which is a multi-module maven project.

**Comment by wilkinsona** [comment]
> By adding a settings.gradle file that includes a directory (what is now the root directory). I think that is still a simple and understandable default

I don't think it's simple or understandable, not for beginners at least. Gradle's own documentation describes as the "most intellectually challenging" topic in its user guide.

Including the root directory doesn't work as you end up with two projects with the same directory:

```
Multiple projects in this build have project directory '/Users/awilkinson/gradle-test': [:., :]
```

Creating a sub-directory means that users now need to understand the root project and a subproject and the affect that can have on their build configuration. I think it would be a mistake to inflict that on everyone.

> I think multi-module projects are an important way to control complexity of a codebase as it grows, as part of the evolution of a project is the creation of boundaries and the extraction of reusable libraries. Take initializr itself for example, which is a multi-module maven project.

I agree with all of that. I think the key part of what you've said is "as it grows". A small project straight from start.spring.io doesn't warrant the added complexity. Some projects will get there and, at that point, they can move to a multi-project build. However, some will never get there so there's no point in inflicting the complexity of a multi-module build on them.

**Comment by berlin-ab** [comment]
@dsyer Your guide is really useful. I find myself referring back to the Gradle docs often when explaining this technique to people. Now I can just point them to the guide.
