### ISSUE TITLE
kotlin reflection library is missing in dependencies.

### ISSUE THREAD

**Issue by nimtiazm** [spring-io/initializr#355]
I tried creating springboot 2 SNAPSHOT from initializr with Kotlin support. The generated project had a missing dependency on kotlin-reflect library due to which spring boot won't run and throw the following exception (root cause): 
Caused by: java.lang.ClassNotFoundException: kotlin.reflect.jvm.ReflectJvmMapping
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_65]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_65]
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_65]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_65]
    ... 23 common frames omitted

Adding the kotlin-reflect dependency manually solves the problem. It should be added by default.

**Comment by snicoll** [comment]
Are you saying any project will break? That sounds suspicious. 

Ping @sdeleuze

**Comment by nimtiazm** [comment]
Actually @sdeleuze helped me fix this on twitter : )
To me it just doesn't build the scratch spring boot 2 project generated from initialzr.

**Comment by sdeleuze** [comment]
@nimtiazm By default based on my tests on projects with Kotlin + Spring Boot 2.0 snapshots, applications start correctly with both and Web and Web Reactive dependency. I guess the error you reported is based on [nullable checks](https://spring.io/blog/2017/01/04/introducing-kotlin-support-in-spring-framework-5-0#leveraging-kotlin-nullable-information) we do in Spring Framework 5.

That said, I could maybe improve Kotlin detection on Spring Framework side to activate nullable checks only if kotlin-reflect in in the classpath (currently [we do the test on `Unit`](https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/MethodParameter.java#L62)).

Could you pkease describe what you did to get this error (what dependency you added) or share your project on GitHub and post the full stacktrace?

**Comment by nimtiazm** [comment]
I re-tried it. A stock project structure with dependencies downloaded from initializr works but if I add @Component or any other spring artifact which contains nullable references, the run-time complains for missing reflection library. In that case I think maybe it should be manually added rather than initializr giving it up-front. Please go ahead and close this issue.

**Comment by sdeleuze** [comment]
I think that's ok to add that dependency by default since it is used by various part of Spring Framework 5 (`@Autowired`, `@Inject`, `@RequestParam`, etc...) which is the first version to officially support Kotlin + it does not hurt to have it with previous versions.

**Comment by nimtiazm** [comment]
+1

**Comment by snicoll** [comment]
Closing in favour of PR #361
