### ISSUE TITLE
Rename "Spring Reactive" to "Spring WebFlux" in artifact description

### ISSUE THREAD

**Issue by sdeleuze** [spring-io/initializr#367]
When the migration for https://github.com/bclozel/spring-boot-web-reactive to Spring Boot master will be completed, it would be nice to rename the dependency name from `Reactive Web` to `WebFlux` (while still mentioning Reactive in the description) to be consistent with the latest Spring Framework `spring-webflux` module name.

**Comment by sdeleuze** [comment]
After more thought, it is maybe better to keep Reactive Web (consistent with Spring MVC behavior) and just replace in the description "Spring Reactive" by "Spring WebFlux"

**Comment by snicoll** [comment]
Fixed by	fa485e3
