### ISSUE TITLE
Initialization failed for "http://start.spring.io" Please check URL,network and proxy settings. Error message: cannot download "htpp://start.spring.io":connect timed out

### ISSUE THREAD

**Issue by Mic-JasonTang** [spring-io/initializr#369]
![qq 20170207110242](https://cloud.githubusercontent.com/assets/19240702/22676188/00ce32cc-ed25-11e6-8d71-5afbcd74d116.png)
![qq 20170207110606](https://cloud.githubusercontent.com/assets/19240702/22676281/7197a8b2-ed25-11e6-87b3-8761fa2b0553.png)
![qq 20170207110814](https://cloud.githubusercontent.com/assets/19240702/22676325/bce3dc82-ed25-11e6-826a-181f1770f827.png)
![qq 20170207110849](https://cloud.githubusercontent.com/assets/19240702/22676345/d54a7aec-ed25-11e6-9d04-44b88efd3d79.png)

My IDEA version is 2016.3.4
Please help me , thanks!

**Comment by snicoll** [comment]
Must have been a temporary network glitch. The easiest is to try "https://start.spring.io" in your browser.

**Comment by Mic-JasonTang** [comment]
In my browser, it works.
But In the IDEA, it doesn`t work.
It confused me for a long time.

**Comment by snicoll** [comment]
@Mic-JasonTang ah I see, would have been interesting to mention that in your report. This is a network setting issue on your side then and nothing I can help you with. Perhaps you have a corporate proxy of some sort that IntelliJ IDEA doesn't know about?

**Comment by jianyuanzh** [comment]
@Mic-JasonTang  I have the same issue as you. 
How did you resolve your problem?

**Comment by snicoll** [comment]
@jianyuanzh please report IntelliJ IDEA specific issue in [their issue tracker](https://youtrack.jetbrains.com/issues).
