### ISSUE TITLE
Wizard should make it more obvious how to create "plain" spring boot apps.

### ISSUE THREAD

**Issue by thomasdarimont** [spring-io/initializr#37]
If one uses the initializr via http://start.spring.io/ and leave all options unchecked,
one gets a `plain` Spring Boot Application which is a good start if users just want to 
create a simple CLI app to play with DI and configuration.

Right now it its (IMHO) not obvious to users that they can get such a plain configuration when they don't check anything at all.

I'd suggest to make this more obvious either with an (always on default selection like "basic" or "basic configuration") or a little help text, or even show the generated pom directly in a window nearby...

**Comment by bclozel** [comment]
IMO, this backs the idea that people would be interested in a separate, dedicated wizard app that helps developers bootstrap their projects: types of applications, multi-step form with questions asked to developers... This is a different angle and requires a totally different approach.

I'd be in favor of closing this issue for now and count it as a +1 for another application.

**Comment by snicoll** [comment]
See #104
