### ISSUE TITLE
Upgrade to Gradle 3.4.1

### ISSUE THREAD

**Issue by berlin-ab** [spring-io/initializr#380]
The most recent version of Gradle is 3.4.1 and the default version provided by start.spring.io is 2.13. It would be nice if the default gradle version downloaded would be up-to-date.

**Comment by snicoll** [comment]
We are using Gradle 3 if you chose Spring Boot 2. Discussing with @wilkinsona we could be a bit more agressive here and apply that for 1.5 as well.

**Comment by snicoll** [comment]
Gradle 3.4+ is breaking IJ users so let's stick with 3.3 for the time being.

**Comment by gandrade** [comment]
Using Gradle 3.4+ and the latest IJ version I was unable to run any application generated by Spring Initializr using Spring Boot `1.5.2-RELEASE`. To workaround it, I've changed it to **Gradle 3.3** or **prior**.

**Comment by sdeleuze** [comment]
Another workaround is to uncheck "Create Module for each SourceSet" during Gradle import. This bug should be fixed in the upcoming IDEA 2016.3.6.

**Comment by snicoll** [comment]
thanks @gandrade and @sdeleuze 

We've discussed this issue internally as @wilkinsona is currently rewriting the Spring Boot gradle plugin and we'll soon require Gradle 3.4 on `master`. There is no fix currently so I've reverted to 3.3. As soon as `2016.3.6` goes mainstream, I'll upgrade to Gradle 3.4 again.

**Comment by berlin-ab** [comment]
We're using IntelliJ and Gradle 3.4. What problems are users experiencing? We're probably having the same problems but are not aware.

**Comment by snicoll** [comment]
https://youtrack.jetbrains.com/issue/IDEA-167412
