### ISSUE TITLE
Correct Spring Cloud Task versions

### ISSUE THREAD

**Issue by mminella** [spring-io/initializr#382]
Currently, the version mapping for Spring Cloud Task is as follows:
```
"cloud-task-bom": {
"1.0.3.RELEASE": "Spring Boot >=1.3.0.RELEASE and <=1.4.0.RELEASE",
"1.1.2.RELEASE": "Spring Boot >=1.4.0.RELEASE and <1.4.6.BUILD-SNAPSHOT",
"1.1.3.BUILD-SNAPSHOT": "Spring Boot >=1.4.6.BUILD-SNAPSHOT and <1.5.0.RC1",
"1.2.0.BUILD-SNAPSHOT": "Spring Boot >=1.5.0.RC1"
},
```
There is no Spring Boot compatibility difference between 1.1.2 and 1.1.3 so we should remove that line completely.  Also, there is a Spring Cloud Task M1 out that should work with SCDF so there isn't a pressing reason to pull the 1.2.0 SNAPSHOTS anymore.  This results in the matrix looking more like:
```
"cloud-task-bom": {
"1.0.3.RELEASE": "Spring Boot >=1.3.0.RELEASE and <=1.4.0.RELEASE",
"1.1.2.RELEASE": "Spring Boot >=1.4.0.RELEASE and <1.5.0.RC1",
"1.2.0.M1": "Spring Boot >=1.5.0.RC1"
},
```

**Comment by snicoll** [comment]
thanks @mminella, reusing the bom mapping was quite helpful to make sure I understood the intend!
