### ISSUE TITLE
Add Apache CXF - RESTfull to the list

### ISSUE THREAD

**Issue by cmoulliard** [spring-io/initializr#394]
Apache CXF (>= 3.1.9) ships Spring-boot which supports to develop Web Services - JAX-WS or RESTfull - JAX-RS projects

The apache cxf documentation page is available here : https://cxf.apache.org/docs/springboot.html

while the starter is referred here : https://github.com/spring-projects/spring-boot/tree/master/spring-boot-starters

A project can be developed using the Spring or JAX-RS annotations

```
@RestController
public class GreetingController {

	@Autowired
	private GreetingProperties properties;

	private final AtomicLong counter = new AtomicLong();

	@RequestMapping("/greeting")
	public Greeting greeting(@RequestParam(value = "name", defaultValue = "World") String name) {
		return new Greeting(this.counter.incrementAndGet(), String.format(this.properties.getMessage(), name));
	}
}

@SpringBootApplication
public class RestApplication {

	public static void main(String[] args) {
		SpringApplication.run(RestApplication.class, args);
	}

}

&

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-tomcat</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.cxf</groupId>
      <artifactId>cxf-spring-boot-starter-jaxrs</artifactId>
    </dependency>
    <dependency>
...
</dependencies>
```

**Comment by sberyozkin** [comment]
Please note that the CXF JAX-RS starter only indirectly supports Spring annotations due its dependency on spring-boot-starter. 
It would probably make sense to introduce 'cxfws' and "cxfrs" qualifiers for selecting either CXF JAXWS or CXF JAXRS starter.

**Comment by snicoll** [comment]
We won't add two starters for CXF.

We are now considering adding the jax-rs starter and before we do I'd like to know if there are multiple versions of the starter supported and which spring boot generations are supported. As @vpavic actively implemented this, he may be aware.

**Comment by deki** [comment]
And what about jax-ws?

CXF 3.1.11 which was released yesterday supports Spring 1.5.x.

**Comment by vpavic** [comment]
The original Spring Boot integration in CXF was introduced in `3.1.7` and was based on Boot `1.3.x`.
CXF `3.1.11` and `3.2.0` support Boot `1.5.x` - see [CXF-7198](https://issues.apache.org/jira/browse/CXF-7198).

**Comment by snicoll** [comment]
We won't add jax-ws.

**Comment by snicoll** [comment]
@vpavic I am confused. A bug fix release of the starter changed the supported Spring Boot version?

**Comment by cmoulliard** [comment]
@snicoll When you say that you wan't add jax-ws, I suppose that you would like to say that the CXF Starter will be either jax-rs or jax-ws and not both ?

**Comment by snicoll** [comment]
@cmoulliard Yes

**Comment by vpavic** [comment]
> I am confused. A bug fix release of the starter changed the supported Spring Boot version? What should I take then? 3.2.0 for 1.5?

Well, `3.2.0` isn't out yet.

The cause for that change was removal of `org.springframework.boot.context.embedded.ServletRegistrationBean` in Spring Boot `1.5.0` which prevented CXF's Boot integration users from upgrading Boot.

BTW I have to correct myself, `3.1.11` upgraded to Boot `1.4.x`, but it works with `1.5.x` as well. IMO you should go with `3.1.11` for both `1.4.x` and `1.5.x` ATM.

**Comment by cmoulliard** [comment]
@snicoll Is the CXF Starter project ready to become part of the initialzr ? Do we miss something ?

**Comment by snicoll** [comment]
Thanks @vpavic ! I guess we have most of the interested parties in this issue so if a new release of CXF is out, I'd appreciate a request for upgrade (or a PR but we can do that ourselves, it's usually a one line change).

I'll get going with `3.1.11` then.

**Comment by snicoll** [comment]
I've created https://issues.apache.org/jira/browse/CXF-7328

**Comment by sberyozkin** [comment]
Hi, I did update CXF 3.1.11 SpringBoot starters to depend on SpringBoot 4 line after CXF 3.1.x users started reporting they could not run the starters on Spring Boot 5 due to CXF starters depending on the deprecated code removed from SB 5. I also asked experts on the CXF Jira if it was reasonable to assume most users would've migrated to SB 4. SB is fairly new fenomen for CXF and given the above and also the fact that CXf 3.1.x users are starting actively working with SB and CXF 3.1.x is virtually the major line I thought it was reasonably safe to update the starters to the newer SB 4 code.
We do not plan to update CXF 3.1.12 starters to SB 5 ☺
Hope it addresses your concern, cheers, Sergey
________________________________

**Comment by snicoll** [comment]
@sberyozkin I am not following. This isuse is closed and I am not keen to do code generation atm (if that's what you're asking)

**Comment by cmoulliard** [comment]
> generated Demo

We have started to develop a JBoss Forge Spring Boot addon to include such code generation. Here is the [project](https://github.com/forge/springboot-addon). See add a Rest Controller

**Comment by sberyozkin** [comment]
@snicoll What I was thinking about was this - a CXF user goes to https://start.spring.io/, types 'CXF', clicks  Generate Project, downloads the generated Demo which already does something OOB, at the moment it is empty and the only CXF specific thing in it is a CXF JAXRS starter dependency. Do you think it would be reasonable - if yes then I can open a new issue and provide the necessary code, let me know please

@cmoulliard thanks for the link, the project looks very interesting

**Comment by sberyozkin** [comment]
@cmoulliard sorry, so basically, once this JBoss SpringBoot AddOn is finalized then this is exactly what the CXF users will be able to do when they go to  https://start.spring.io/ and type 'CXF', be able to add some custom resources/controllers, etc ? if so then it is exactly what I'm after :-), sorry for the noise then
