### ISSUE TITLE
Executable permissions gone missing on mvnw on start-development.cfapps.io

### ISSUE THREAD

**Issue by kdvolder** [spring-io/initializr#395]
Hey, I've been noticing some of STS CI builds have test failures. Apparantly start-development.cfapps.io zips no longer set execute permissions on the mvnw file.

https://build.spring.io/browse/IDE-CONTINUOUSTESTING-JOB1-1994/test/case/187118935

At first I thought the STS code for unpacking the zip was broken again as it once was before:
https://issuetracker.springsource.com/browse/STS-4260

But it looks this time the zip itself seems to be the culprit. I have unpacked a zip from start.spring.io and one from start-development.cfapps.io and only the 'development' zip is missing the exe permission on the mvnw.

**Comment by kdvolder** [comment]
Dir contents of 'start.spring.io' zip:

```
drwxr-xr-x 4 kdvolder kdvolder 4096 Mar 22 08:34 .
drwxr-xr-x 4 kdvolder kdvolder 4096 Mar 22 08:34 ..
-rw-r--r-- 1 kdvolder kdvolder  249 Mar 22  2017 .gitignore
drwxr-xr-x 3 kdvolder kdvolder 4096 Mar 22 08:34 .mvn
-rwxr-xr-x 1 kdvolder kdvolder 7058 Mar 22  2017 mvnw
-rw-r--r-- 1 kdvolder kdvolder 5006 Mar 22  2017 mvnw.cmd
-rw-r--r-- 1 kdvolder kdvolder 1549 Mar 22  2017 pom.xml
drwxr-xr-x 4 kdvolder kdvolder 4096 Mar 22 08:34 src
```

Dir contents of a 'development' zip:

```
drwx------ 4 kdvolder kdvolder 4096 Mar 22 08:32 .
drwxr-xr-x 4 kdvolder kdvolder 4096 Mar 22 08:34 ..
-rw-rw-r-- 1 kdvolder kdvolder  249 Mar 22  2017 .gitignore
drwx------ 3 kdvolder kdvolder 4096 Mar 22 08:32 .mvn
-rw-rw-r-- 1 kdvolder kdvolder 7058 Mar 22  2017 mvnw
-rw-rw-r-- 1 kdvolder kdvolder 5006 Mar 22  2017 mvnw.cmd
-rw-rw-r-- 1 kdvolder kdvolder 1549 Mar 22  2017 pom.xml
drwx------ 4 kdvolder kdvolder 4096 Mar 22 08:32 src
```

**Comment by snicoll** [comment]
We need to refresh the dev instance with that fix. I'll do that later today.

**Comment by snicoll** [comment]
The dev instance has been updated, thanks for reporting it.
