### ISSUE TITLE
RFE: Release Project to Maven Central

### ISSUE THREAD

**Issue by mmoayyed** [spring-io/initializr#405]
Thank you for this great tool!

The docs note the following on README:

> Spring Initializr is not available on Maven central yet so you will have to build it from source in order to use it in your own environment.

Could you reconsider making the project available on Maven Central? That would make customizations and running instances much easier.

**Comment by snicoll** [comment]
Not at this stage, no. We have plans to exit the `0.x` line and we'll probably release it on Maven central at this point but I don't feel it is warranted at the moment. You can find the `0.x` releases on [repo.spring.io](http://repo.spring.io/release/io/spring/initializr/)
