### ISSUE TITLE
Restrict 3rd party starters to 1.5

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#411]
Some 3rd party starters haven't changed recently so they're is a chance some features are broken with Spring 5 and Spring Boot 2.0

Let's restrict them (if necessary) until we get an update from the development team about Spring Boot 2.0 compliance.

**Comment by kazuki43zoo** [comment]
Hi @snicoll, The `mybatis-spring-boot-starter` 1.3.0 work fine on Spring Boot 2.0.0.BUILD-SNAPSHOT.

I've tried to updating Spring Boot 2.0.0.BUILD-SNAPSHOT using my sample application as follow:

* https://github.com/kazuki43zoo/mybatis-spring-boot-jpetstore/tree/try-spring-boot-2.

Changes for updating:

* https://github.com/kazuki43zoo/mybatis-spring-boot-jpetstore/compare/try-spring-boot-2

Build result:

* https://travis-ci.org/kazuki43zoo/mybatis-spring-boot-jpetstore/builds/222512988

I think the `mybatis-spring-boot-starter` 1.3.0 has compatibility with Spring Boot 2.0.0.BUILD-SNAPSHOT at the moment.

**Comment by snicoll** [comment]
Thanks for the quick feedback. Can you please create a ci job for that and create a separate issue once you're done and I am happy to change the range.

**Comment by kazuki43zoo** [comment]
@snicoll Thanks for reply!! I've created gh-412. Please check it.
