### ISSUE TITLE
Add Spring Cloud Vault to Initializr

### ISSUE THREAD

**Issue by mp911de** [spring-io/initializr#414]
Category: Cloud Config
Name: Vault Configuration
Description: Configuration management with HashiCorp Vault

Minimal Boot version: 1.5.x

Dependency:
GroupId: org.springframework.cloud
ArtifactId: spring-cloud-starter-vault-config

Spring Cloud Vault is part of the Spring Cloud Dalston Release train.

**Comment by snicoll** [comment]
@mp911de this starter does not bring the base bits for a spring boot app (read, it does not provide `spring-boot-starter`). I've fixed that in the metadata definition but it feels weird to me that a starter does not bring the basic bits to start a spring boot app. Thoughts?

**Comment by mp911de** [comment]
I think it's a bug. I'll fix it with the next service release.
