### ISSUE TITLE
Spring Cloud Data Flow needs Boot 1.5.2

### ISSUE THREAD

**Issue by trisberg** [spring-io/initializr#417]
There are some breaking changes in the spring-data-commons library that Boot 1.5.3 brings in, so the 1.2.0 version of SCDF needs Boot 1.5.2

**Comment by trisberg** [comment]
More info here: https://github.com/spring-cloud/spring-cloud-dataflow/issues/1382

We are planning to update SCDF with a fix for an upcoming 1.2.1 release

**Comment by snicoll** [comment]
Spring Cloud Dataflow 1.2.0 isn't even registered at the moment, see http://start.spring.io/info

Let me know what versions should be defined there. As for that breaking change, I won't downgrade the Spring Boot version so the only thing I can do is disable SCDF in the 1.5.x line for the time being.

Let me know what you'd like to do.

**Comment by trisberg** [comment]
I guess the 1.2.0.BUILD-SNAPSHOT should now have:

`"1.2.0.BUILD-SNAPSHOT": "Spring Boot >=1.5.0.RC1 and <1.5.3.RELEASE"`

We are releasing 1.2.0.RELEASE very soon, but looks like we need to wait for 1.2.1 with the Boot 1.5.3 fix before re-enabling it

**Comment by snicoll** [comment]
Ah sorry I misunderstood as you were referring to `1.2.1.RELEASE` so I thought `1.2.0.RELEASE` was out. I am updating the range then. Thanks.

**Comment by snicoll** [comment]
SCDF is now disabled in the 1.5.x line effectively. Let me know when `1.2.1` is out and we can enable it again.

**Comment by trisberg** [comment]
One more fix (1.1.4 only works up to Boot 1.4.5):

```
"1.1.4.RELEASE": "Spring Boot >=1.4.0.RELEASE and <1.4.6.RELEASE",
```

**Comment by snicoll** [comment]
You are aware that doing this effectively disable SCDF from start.spring.io right?

**Comment by trisberg** [comment]
What's our choice - newer Boot versions break Data Flow server

**Comment by snicoll** [comment]
How about reporting the issue so that we can have a look to it?

**Comment by markpollack** [comment]
https://github.com/spring-projects/spring-data-commons/commit/a8ff4ea1429f8a4c42df2030d7ab9ccc0d742b12 is what changed.  

We are looking to change SCDF 1.2 GA release to adopt, but not thinking about releasing a SCDF 1.1.5 since this was also backported into the data commons 1.12.x line

https://github.com/spring-projects/spring-data-commons/commit/6c1a379442b8584c533f07ecd3ba7b49b1ba4fc1

**Comment by snicoll** [comment]
OK so the issue isn't in Spring Boot but is the same issue as in Spring Data. If you don't intend releasing a 1.1.5 then disabling the 1.4.x line is our only slot. As I've explained on #420 the only way to do that is to disable the 1.3.x line as well (we don't support "holes" in ranges).

Let's continue this discussion on #420 please and let me know what you prefer.
