### ISSUE TITLE
Derive package name from groupId and artifactId

### ISSUE THREAD

**Issue by bclozel** [spring-io/initializr#421]
Currently, creating a project with groupId `com.example` and artifactId `demo` will locate all sources under the `com.example` package by default. This can be customized by clicking on the "switch to the full version" link and editing the "package name" field.

Those defaults could be improved, since multiple apps sharing the same groupId locate all their sources under the same package:
* groupId `com.example`, artifactId `bookmarks` -> package `com.example`
* groupId `com.example`, artifactId `user-management` -> package `com.example`

We should (in my opinion) derive the package from groupId and artifactId to have better defaults:
* groupId `com.example`, artifactId `bookmarks` -> package `com.example.bookmarks`
* groupId `com.example`, artifactId `user-management` -> package `com.example.usermanagement`, `com.example.user`?

This is a change on the client side, so this behavior should be replicated as well to other clients if they want to keep a consistent behavior with the web app.

**Comment by snicoll** [comment]
Spring Boot promotes the idea of a unique package per application and this would enforce that. This is a great idea!

**Comment by snicoll** [comment]
Closing in favour of PR #423
