### ISSUE TITLE
Let the Maven parent block be optional?

### ISSUE THREAD

**Issue by mmoayyed** [spring-io/initializr#428]
Would you be willing to accept a pull request that makes the following block optional?

```
<parent>
		<groupId>{{mavenParentGroupId}}</groupId>
		<artifactId>{{mavenParentArtifactId}}</artifactId>
		<version>{{mavenParentVersion}}</version>
		<relativePath/> <!-- lookup parent from repository -->
</parent>
```

Something like `hasParent` might do nicely. I don't know the magic ways of Mustache all that well, but something like `mavenParentGroupId != null` might also be good.

**Comment by snicoll** [comment]
Rather than asking if we would accept a pr, can you explain what the use case is please?

**Comment by mmoayyed** [comment]
Sure. I would like to use the initializr more as a library to generate my own project set up with my own set of dependencies, etc. Ideally, I would want to skip the parent block that is provided by the starter pom by default, as I have no need for it. That's essentially all there is to it, thus the title.

**Comment by snicoll** [comment]
I am not sure I like the idea of not having a parent and not having the BOM included automatically, i.e. if the parent is disabled, there must be a configuration BOM of some kind added automatically. If you come up with a PR, I am happy to review it.

Next time, please use Gitter if you want to reach out and chat about a feature, thanks!
