### ISSUE TITLE
Improvements to ProjectGenerator for easier extensibility 

### ISSUE THREAD

**Issue by mmoayyed** [spring-io/initializr#430]
I'd like to propose the following changes to the `ProjectGenerator` class for easier extensions. I need to customize this class to some degree and open it up, because I am working on a custom implementation of the initializr that bootstraps an entirely different project with its own set of dependencies, modules and structure. 

If you'd like me to create a separate issue for each of these so you can review individually, please let me know. I figured grouping them in one issue, as they all deal with one component, is less ceremonial. 

- It would be great if `writeTextResource` and `writeBinaryResource` were marked as `protected`
- `resolveModel` could likely be broken down to smaller chunks for easier extensions, specially the bit that deals with filtering dependencies
- `doGenerateProjectStructure` could likely be broken down to smaller chunks for easier extensions, specially to define pluggable points for generating and writing arbitrary resources that have access to the entire model, the root directory, etc.
- `isMavenBuild` and `isGradleBuild` marked as `protected`

Happy to submit a PR, if/when needed.

**Comment by snicoll** [comment]
Duplicates #340 

Sorry but I am not keen to open the current contract more as we're likely to break it in a future release before we reach 1.0. I'd really would like to introduce a model and a code builder abstraction to let you plug in whatever strategy you'd like. We don't have the resources to execute this unfortunately but your request is now linked so we'll keep that in mind. Thanks for the suggestion.

**Comment by mmoayyed** [comment]
Understood. Thank you for reviewing this.
