### ISSUE TITLE
Add links to each project / library

### ISSUE THREAD

**Issue by berlin-ab** [spring-io/initializr#441]
As a developer creating a new project, I am curious what some of these libraries are and if they might be useful to me. It would be nice if I could follow a link to the library's documentation page or Github readme to give me more information easily.

**Comment by snicoll** [comment]
We already have that for most projects and if you use the IDE integration this should show up. This is implemented for STS but I don't think it's released yet. We intend to offer a list of links based on your dependencies in the generated project (see #353).

We thought (quite hard I must say) of showing that in the web interface itself but we're not convinced it's the right call.
