### ISSUE TITLE
Allow ability to specify jar baseName for gradle projects

### ISSUE THREAD

**Issue by jtaylormayfield** [spring-io/initializr#443]
The Gradle project initializr does not provide the ability to specify the JAR name, so application builds generate a JAR with a default name (i.e. app-x-x-x.jar). Obviously, after generating the project, developers can tweak the build.gradle using this code:

`jar {
	baseName = 'my-app-name'
}`

This directs Gradle to generate a JAR "my-app-name" prepended to the file name. However, it would save a little time if the initializr had an optional form field that allowed you to set the JAR base name. The initializr could then generate this configuration section for you in the build.gradle.

**Comment by snicoll** [comment]
@jtaylormayfield I was waiting for you updating the description to actually provide one but it looks like you think the title is enough. It isn't. Can you please clarify what you mean and what use case you're trying to achieve?

**Comment by jtaylormayfield** [comment]
I have updated the issue description. Please let me know if you have any further questions.

**Comment by snicoll** [comment]
I am not keen to add a gradle specific option to the build. Perhaps we could use the artifactId? That conversation looks very similar to another request though. 

Thoughts @wilkinsona @dsyer?

**Comment by dsyer** [comment]
-1 to anything new in the UI. +1 to default the jar name to the artifactid (which we do collect in the UI already).

**Comment by wilkinsona** [comment]
This is basically asking to revert #381, isn't it? Probably unsurprisingly (given that I raised #381) I am -1 on making a change here for the reasons outlined in #381.

**Comment by snicoll** [comment]
There you go, I knew we already discussed this. Let's keep what we have with #381. Thanks for the suggestion @jtaylormayfield.

**Comment by jtaylormayfield** [comment]
This makes sense. Thanks for the update guys!
