### ISSUE TITLE
Add spring-boot-starter-test to dependencies

### ISSUE THREAD

**Issue by PeterWippermann** [spring-io/initializr#448]
Hi,
first of all: What a great project! Thanks for maintaining it👍
Of course one doesn't have to start a new project that often, but at Senacor we'd like to use http://start.spring.io for an internal training, so the participant get a basic app with a few clicks and start coding right away. 

Having that said, I was wondering **why `spring-boot-starter-test` isn't available** in the list of dependencies? For my purpose, the students would have to add the dependency manually after having generated the project.

If you agree that it could be added, I'd be happy to **set up a PR** _- if I finally understand the configuration syntax :-D_

**Comment by snicoll** [comment]
Thanks for the kind words but have you tried? The test starter is always added.

**Comment by PeterWippermann** [comment]
How could I miss the obvious! Thanks for pointing me on that, @snicoll!
I tried to double check in the initializr's config, but didn't check the generated POM...

So sorry for disturbing you! Issue can be closed of course :-D
