### ISSUE TITLE
Security should also add spring-security-test

### ISSUE THREAD

**Issue by rwinch** [spring-io/initializr#461]
Selecting Security should automatically add spring-security-test as a test dependency.

NOTE:  This was discussed in #152 but I thought it was blocked (perhaps it just is no longer blocked?). It  appears this is possible since adding Reactive Web adds `spring-boot-starter-webflux` and `reactor-test`

**Comment by rwinch** [comment]
Thanks for the super fast turnaround on this @snicoll!

**Comment by snicoll** [comment]
No need to, that was an oversight on my end. Thanks for the reminder!
