### ISSUE TITLE
Guide users to HTTPS

### ISSUE THREAD

**Issue by rwinch** [spring-io/initializr#473]
Given initializr produces a project that contains code, links to external jars, etc, it would be nice if we made stronger attempts to send users to HTTPS so that we can ensure the integrity of the project that is produced. I see two areas this could be improved:

* Redirect HTTP requests to HTTPS
* Add an HSTS header to the HTTPS requests to ensure that future requests go over HTTPS

**Comment by snicoll** [comment]
This https://github.com/spring-io/initializr/issues/78#issuecomment-75379780 is a bit embarrassing :(

Thanks for reporting the issue!

**Comment by snicoll** [comment]
Closing in favour of PR #625
