### ISSUE TITLE
'Group' is not generated for gradle project

### ISSUE THREAD

**Issue by IrishkA13** [spring-io/initializr#478]
Why is group generated only for maven project?
Can't it be genrated for gradle projects too?
Such systems as sonarqube, nexus and others use group by default if finds it for both maven and gradle projects.

**Comment by snicoll** [comment]
@IrishkA13 sorry for the long way. Can you please share a `build.gradle` where that information would be used?

**Comment by wilkinsona** [comment]
@snicoll Here's an example of REST Docs' build: https://github.com/spring-projects/spring-restdocs/blob/master/build.gradle#L21. It's basically analogous to the `groupId` in a pom, indeed it ends up being just that if you do a Maven-based publish.
