### ISSUE TITLE
Use RestTemplateBuilder instead of instantiating own RestTemplate

### ISSUE THREAD

**Issue by ArloL** [spring-io/initializr#481]
First of all thanks for this cool project. Makes it really easy to roll your own initializr. There is one minor thing that can be improved: We are using a local installation of the initializr behind a proxy. Sadly the RestTemplate can't be easily replaced since it is instantiated instead of being injected:

https://github.com/spring-io/initializr/blob/master/initializr-web/src/main/java/io/spring/initializr/web/autoconfigure/InitializrAutoConfiguration.java#L132

This forces us to instantiate our own `InitializrMetadataProvider`. This can be made a bit easier. I would recommend something like this:

~~~
@Bean
@ConditionalOnMissingBean(InitializrMetadataProvider.class)
public InitializrMetadataProvider initializrMetadataProvider(
        InitializrProperties properties,
        RestTemplateBuilder restTemplateBuilder) {
	InitializrMetadata metadata = InitializrMetadataBuilder
	    .fromInitializrProperties(properties).build();
	return new DefaultInitializrMetadataProvider(metadata,
	    restTemplateBuilder.build());
}
~~~

This allows for [RestTemplate customization](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-restclient-customization).

**Comment by snicoll** [comment]
Good catch, thanks!
