### ISSUE TITLE
Add spring-batch-test when Spring Batch is selected

### ISSUE THREAD

**Issue by mdeinum** [spring-io/initializr#491]
Currently when using Spring Batch (amongst others) one needs to manually add the `spring-batch-test` dependency. 

It would be nice that when once adds a dependency for a project that has a `spring-*-test` dependency this would be automatically added. Projects that include those, amongst others are:
* Spring Batch
* Spring Integration
* Spring Web Services
* Spring Kafka

Probably some other projects that I'm currently not aware of.

Maybe there is a way of detecting `spring-*-test.jar` dependencies of a project and if available add them instead of hardcoding the list?

See also [gh-10062](https://github.com/spring-projects/spring-boot/issues/10062) which was the initial issue, and in which @snicoll correctly reminded me to the fact that `test` dependencies aren't transitive (how could I forget).

**Comment by snicoll** [comment]
Let's focus on spring batch for now. I am not keen to apply this rule wider than that.

**Comment by snicoll** [comment]
Closing in favour of PR #516
