### ISSUE TITLE
War packaging broken as of Spring Boot 2.0.0 M1

### ISSUE THREAD

**Issue by wyaeld** [spring-io/initializr#502]
Trying to create spring boot 2.0 m3 projects fail to compile.

Root cause is that `SpringBootServletInitializer ` has moved in this commit
https://github.com/spring-projects/spring-boot/commit/33e54ed7238c515531e93cbd2e159664a4b5dc62#diff-ee193e658dcbb05ace5349497a87db8e

This affects the templates for `ServletInitializer` eg https://github.com/spring-io/initializr/blob/master/initializr-generator/src/main/resources/templates/ServletInitializer.java#L5

This may require splitting Boot v1 vs v2 templates.  I'm not experienced enough how the tool works.

**Comment by snicoll** [comment]
Thanks for reporting the issue!
