### ISSUE TITLE
Add a blurb about version artifacts

### ISSUE THREAD

**Issue by Buzzardo** [spring-io/initializr#504]
Not all of the people who visit the page know the details of the various kinds of releases. I'd like to add a short sentence with a link to an explanatory document, so that people can understand what "M" and "RC" and "GA" mean. Knowing that may help them choose the right item.

**Comment by snicoll** [comment]
I am not sure I like the idea of adding anything that's client specific. There are various clients, including command line that would not benefit from this. 

Perhaps you could share a bit more details? Generating a project is a second step so I expect that information to be available upfront.

**Comment by Buzzardo** [comment]
If start.spring.io is the second step, what is the first step? Maybe we could put this information there.

**Comment by snicoll** [comment]
The documentation of each project. The project's page is probably a better place for this, though I don't know how we could lay out that.

**Comment by Buzzardo** [comment]
Do people sometimes come directly to start.spring.io? I suspect some do, either because they know about it already (probably not the audience with the problem) or because they found a link on some external site, over which we have no control.

**Comment by Buzzardo** [comment]
What do you mean by "client specific"? Are you thinking of Maven and Gradle or something else?

**Comment by snicoll** [comment]
This service is consumed by three IDEs and at least 3 different command line clients. Adding any information in our Web UI would target a fraction of our users. I think this should be done elsewhere.
