### ISSUE TITLE
Get rid of org.json

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#507]
`org.json` is no longer managed as of Spring Boot 2 so we should replace its usage with something else. Plain jackson comes to mind.

**Comment by TimRiemer** [comment]
I would work on this issue if it's ok.

**Comment by snicoll** [comment]
Of course it is! Please come chat on Gitter if you have a question.

**Comment by snicoll** [comment]
I've implemented something  in 81b952a but that breaks the IDE support and I have no idea why so some additional tests have to be written before a rollout to prod.

**Comment by snicoll** [comment]
The problem was due to something running locally on my machine. In the meantime got it working properly with STS and IntelliJ IDEA.
