### ISSUE TITLE
initializr-service module parent entry points to 0.4.0.BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by jbellmann** [spring-io/initializr#509]
Version was updated to 0.5.0.BUILD-SNAPSHOT. But the [parent entry in initializr-service](https://github.com/spring-io/initializr/blob/master/initializr-service/pom.xml#L9) module still points to 0.4.0.BUILD-SNAPSHOT. Currently I'm not able to build the project with profile 'full' enabled in a clean environment (0.4.0.BUILD-SNAPSHOT not build before).

Regards

**Comment by snicoll** [comment]
Yep, good point. I forgot to fix that.
