### ISSUE TITLE
Upgrade to Gradle 4.2 for Spring Boot 2+

### ISSUE THREAD

**Issue by rwinch** [spring-io/initializr#513]
Currently the Gradle version for Boot 2.0.0.BUILD-SNAPSHOT is Gradle 4.0.0.2. It would be nice to update to Gradle 4.2 for Boot 2.0.0.BUILD-SNAPSHOT.  I realize this might require some downstream updates, but I thought this might be a good place to track those downstream updates if there are any.

**Comment by wilkinsona** [comment]
I believe this should work, but let's get compatibility testing against 4.2 in place for the dependency management plugin and Boot's plugin first. I'll report back here once that's been done.

**Comment by wilkinsona** [comment]
The compatibility tests are in place
