### ISSUE TITLE
Show Jetty as an option for web development in advanced mode

### ISSUE THREAD

**Issue by pablogrisafi1975** [spring-io/initializr#520]
For reasons I ignore, ( maybe just marketing), Jetty is somehow more popular than Tomcat, particularly between young developers. Tomcat is supposed to be more bloated, bigger and slower then Jetty.   

While switching from Tomcat to Jetty is fairly simple, and only implies some pom changes, and it is clearly documented, initializer is becoming the start page for most people, the 'Welcome to Spring' page, and I think it would be great to have a way to show beginners that Spring works with Jetty as well, and to avoid the small work of manually editing the pom.

The option we have is 

```
Web
Full-stack web development with Tomcat and Spring MVC
```

At the very least, it should say 
  
```
Web
Full-stack web development with Tomcat *or Jetty* and Spring MVC
```

And it would be better if a `Use Jetty instead of Tomcat`  checkbox were present (and maybe event the default)

Thanks for your wonderful job!

**Comment by snicoll** [comment]
Tomcat is the default container that's provided by the web starter. You may argue that's the wrong call and we should bring tomcat by default but that's not what we're doing.

Initializr is following Spring Boot's opinion. Feel free to raise that if you feel the default should change.
