### ISSUE TITLE
Remove reactive security starter

### ISSUE THREAD

**Issue by rwinch** [spring-io/initializr#524]
Spring Security moved code in spring-security-webflux into spring-security-web. Initializr needs updated to account for this

See https://github.com/spring-projects/spring-security/issues/4662 https://github.com/spring-projects/spring-boot/issues/10692

**Comment by snicoll** [comment]
@rwinch this is a duplicate of the Spring Boot issue: Spring Initializr does not (hopefully!) target individual artifacts (except a few corner cases) but uses the starter. Whatever the starter will bring will be used.

Let me know if I misunderstood something.

**Comment by rwinch** [comment]
Thanks @snicoll! I just didn't know how it worked so I created a ticket to ensure it was addressed. Thanks again!

**Comment by snicoll** [comment]
Actually you're spot on :) We need to deprecate the `reactive-security` starter now so I am going to use this issue for that.
