### ISSUE TITLE
Adoption of Spring Boot 2 will require a change to metrics collection

### ISSUE THREAD

**Issue by jkschneider** [spring-io/initializr#526]
We will need to migrate to Micrometer-based instrumentation away from the former `CounterService`/`GaugeService` API. See https://github.com/spring-io/initializr/blob/master/initializr-actuator/src/main/java/io/spring/initializr/actuate/metric/ProjectGenerationMetricsListener.java

**Comment by snicoll** [comment]
@jkschneider thanks, it's in my backlog even if this service is running behind due to lack of time. We don't use those metrics anymore as we index stats in elastic but the feature is quite interesting still and I'd love to get your feedback on that once I get going.

**Comment by snicoll** [comment]
We've deprecated metrics collection in favour of stats publishing.
