### ISSUE TITLE
Executable bit missing on wrapper when baseDir is set

### ISSUE THREAD

**Issue by dsyer** [spring-io/initializr#533]
I think we have a regression of #395 #162.

```
$ curl start.spring.io/starter.tgz -d dependencies=web -d baseDir=. | tar -xzvf -
$ ./mvnw install
bash: /.../mvnw: Permission denied
```

**Comment by snicoll** [comment]
Since the port to Java perhaps?

**Comment by dsyer** [comment]
I think I tested it back then. Could be wrong. IIRC we had a few tries at getting the tgz packaging to work using different libraries. Possibly I only tested it with one of the older attempts.

**Comment by mbhave** [comment]
Closing in favor of PR #533.
