### ISSUE TITLE
Spring Cloud Edgware.RELEASE

### ISSUE THREAD

**Issue by spencergibb** [spring-io/initializr#549]
Should replace Dalston.SR4 as the boot 1.5.x default.

**Comment by spencergibb** [comment]
Headed to maven central now

**Comment by spencergibb** [comment]
It is there now http://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dependencies/Edgware.RELEASE/

**Comment by snicoll** [comment]
> Should replace Dalston.SR4 as the boot 1.5.x default.

@spencergibb curious about that strategy  (though I haven't a  better idea). This would effectively remove `Dalston` from the list of releases (no Spring Boot  version would be mapped to it anymore). And `1.5.x` is in maintenance mode so `Dalston` feels more appropriate at  first sight.

Thoughts?

**Comment by wilkinsona** [comment]
Moving new apps that are using Spring Cloud to Edgware seems reasonable to me. Boot's long-term maintenance branch being 1.5.x shouldn't restrict Cloud from moving people from Dalston to Edgware.

**Comment by dsyer** [comment]
Agree. That was the intention.

**Comment by snicoll** [comment]
Alright, thanks for the feedback!
