### ISSUE TITLE
please add reactive Stream dependency

### ISSUE THREAD

**Issue by joshlong** [spring-io/initializr#557]
This is necessary if you want to use the Reactor support with Spring Cloud Stream. 

cc @mbogoevici @smaldini 

``` 
<dependency>
   <groupId>org.springframework.cloud</groupId>
   <artifactId>spring-cloud-stream-reactive</artifactId>
</dependency>
```

**Comment by snicoll** [comment]
@joshlong we usually don't add single dependency to Initializr (and Spring Cloud Stream itself isn't covered anymore). Am I missing something?

**Comment by joshlong** [comment]
Spring Cloud Stream is covered? I'm not sure what you mean. I am able to use it for Sleuth Stream and Zipkin Stream and the Stream RabbitMQ binders. 

would appreciate having that dependency surfaced as people may not know they need it. thanks in advance..

**Comment by snicoll** [comment]
It is a hard line to draw but anything that can be added as a single dependency (not starter) isn't a great candidate. We may reconsider this principle in the future (and I am happy to) but we need to have that discussion first.
