### ISSUE TITLE
Consider adding support for mixed-language projects

### ISSUE THREAD

**Issue by ggerard** [spring-io/initializr#561]
Seeing stale information to have mixed Kotlin 1.2 / Java project with Spring and Maven. Speedbump to getting started.

**Comment by snicoll** [comment]
@ggerard we've considered that option and we've decided not to go that route and make a clean cut. What do you mean by "Seeing stale information to have mixed Kotlin 1.2 / Java project with Spring and Maven"?

**Comment by snicoll** [comment]
Closing due to lack of feedback.
