### ISSUE TITLE
Upgrade to Kotlin 1.2.20

### ISSUE THREAD

**Issue by sdeleuze** [spring-io/initializr#576]
Once Boot 2.0.0.RC1 is available.

**Comment by snicoll** [comment]
Note that is decision will break previous 2.0 milestones that are using Spring Data with Kotlin. It is a pragmatic decision as previous milestones won't be available anymore.

**Comment by sdeleuze** [comment]
As a follow-up of https://github.com/spring-projects/spring-boot/commit/d1b18b75d72395e862686c12aeaf557cd4ffa19d, as part of this change Kotlin stdlib dependency should also be changed from `kotlin-stdlib-jre8` to `kotlin-stdlib-jdk8`.

**Comment by snicoll** [comment]
For the record there is also an artifact rename for `jre7` so it should be renamed for consistency
