### ISSUE TITLE
Inaccurate dependency search result

### ISSUE THREAD

**Issue by benas** [spring-io/initializr#581]
Hi,

When I type "Integration" or "integration" in the "Search for dependencies" field, I am expecting to see spring integration dependency in the proposed list, but it looks like it is not matched (It might be matched but not in the short list). 

This is probably not an issue since the form asks me to refine my research, and when I type "spring integration" (or "spring-integration" to have an exact match from the dependency description `Common spring-integration modules`), then spring integration appears in the 4th position. I was expecting it to appear in the first position with such an explicit search token.

What do you think?

Kr,
Mahmoud

**Comment by snicoll** [comment]
Relates to #439
