### ISSUE TITLE
Disable incremental compilation with Maven due to KT-21581

### ISSUE THREAD

**Issue by sdeleuze** [spring-io/initializr#584]
[KT-21581](https://youtrack.jetbrains.com/issue/KT-21581) has been reported by quite a lot of people and seems to impact people using Kotlin 1.2.20 compiler, incremental compilation and Maven. With #576, it may be a good idea to disable it for now at least until KT-21581 fix is widely deployed.

[For Maven, the default is incremental compilation disabled](https://kotlinlang.org/docs/reference/using-maven.html#incremental-compilation) so we should remove `<kotlin.compiler.incremental>true</kotlin.compiler.incremental>` from the generated POM.

As far I know, all issue reports concern Maven, not Gradle (where incremental compilation is the default) so I would let Gradle configuration as it is.

**Comment by snicoll** [comment]
Thanks but I am not keen to have different settings per build system.

**Comment by snicoll** [comment]
Sorry, I misunderstood the initial intention.
