### ISSUE TITLE
Add vavr option on http://start.spring.io/ just like lombok

### ISSUE THREAD

**Issue by daggerok** [spring-io/initializr#602]
Hello,

Is it possible to add vavr options to project generator just like lombok? Usually, I'm always adding this two libraries (vavr and lombok) to any of my new java project, so I can assume many other devs are doing same.

What do you think?

---
Regards,
Maksim

**Comment by snicoll** [comment]
Hello,

Sorry I am not keen to add such dependency (arguably, Lombok shouldn't have been added either). We're trying to rationalize and offer options for things that have an added value compared to "simply adding a jar".
