### ISSUE TITLE
Any new generated project is not buildable (tests failing)

### ISSUE THREAD

**Issue by sarbull** [spring-io/initializr#612]
Generate a new project, build and check if the build is failing or not.

In my case is failing and in order to fix it i had to add:

```xml
<dependency>
  <groupId>org.springframework</groupId>
  <artifactId>spring-aop</artifactId>
  <version>5.0.1.RELEASE</version>
</dependency>
```

Any other suggestions?

**Comment by snicoll** [comment]
@sarbull `spring-aop` `5.0.4.RELEASE` got corrupted when it was downloaded on your local machine. Check your maven cache and try to download the file again.
