### ISSUE TITLE
Creating a config-service doesn't add the proper annotation

### ISSUE THREAD

**Issue by sarbull** [spring-io/initializr#613]
I tried creating a new project by adding `Config Server` but the generated project doesn't contain in the `@EnableConfigServer` annotation on `ConfigServiceApplication`.

Is this behaviour normal?

**Comment by sarbull** [comment]
@snicoll any .idea? 💯

**Comment by sarbull** [comment]
@wilkinsona so it just created the `pom.xml` and the annotations and configuration files `bootstrap.yml` and `application.yml` needs to be added later?

I thought the `start.spring.io` configures everything after i check one or more modules.

**Comment by snicoll** [comment]
> configures everything

I have no idea where that idea came from. It does not.

**Comment by sarbull** [comment]
I did not knew about how `start.spring.io` works.

If this is the case, i'm fine with that but i got confused as i started the app and nothing really happened.

So basically what get's configured is the `pom.xml` with the required dependencies and the rest will be added at a later time.

Cool, thanks!

**Comment by snicoll** [comment]
If you have more questions, please ask on StackOverflow or join us on Gitter: we prefer to use GitHub issues only for bugs and enhancements

**Comment by sarbull** [comment]
@snicoll i thought it was a bug xD
