### ISSUE TITLE
Add flag/support for creating project with .yml properties

### ISSUE THREAD

**Issue by sarbull** [spring-io/initializr#614]
This is actually a feature request for `start.spring.io`.

I would like to generate a project with predefined `.yml` properties files.

**Comment by snicoll** [comment]
I don't understand what you mean. Can you please explain with a concrete use case?

**Comment by sarbull** [comment]
The possibility to use `.properties` or `.yml` files in the generated archive.

**Comment by snicoll** [comment]
Sorry, that doesn't help. Do you mean using `application.yml` rather than `application.properties`?

**Comment by sarbull** [comment]
yes, the possibility to choose which type of properties file to use. `.properties` or `.yml`.

**Comment by snicoll** [comment]
See #94 - the IDE support is still not in par with the properties support so I am not keen to offer an option (actually, I'd be more in favour of a switch than exposing yet another option). We can reconsider later when/if that changes.
