### ISSUE TITLE
When selecting Java 9, pom.xml contains java.version=1.8

### ISSUE THREAD

**Issue by rillig-ite** [spring-io/initializr#621]
To reproduce:
* https://start.spring.io/
* Switch to the full version
* Generate a `Maven` project with `Kotlin`
* Select Java version: `9`
* Generate project

The generated `pom.xml` contains the text `<java.version>1.8</java.version>`.

Furthermore, the project does not run because `java.xml.bind` is not available anymore in Java 9; see https://stackoverflow.com/q/43574426.

**Comment by snicoll** [comment]
This is done on purpose. When you chose Kotlin we stop at Java 8 source level (which is what that Java version basically does) as Kotlin doesn't support Java 9 bytecode generation. 

When that changes we can adapt the post-processor that force-switch to 8 source level.
