### ISSUE TITLE
More specific .gitignore filters

### ISSUE THREAD

**Issue by chrylis** [spring-io/initializr#623]
I was very confused why CI wouldn't build a project until I realized that files under a package with `.build.` in the name weren't being committed to git. The `.gitignore` included with the project is rather aggressive and blocks any directory named `build` at any level.

Since the default is intended to preemptively take care of IDE and Maven/Gradle directories, I suggest that most of them should be absolute specifications (e.g., `/build/`) to avoid collisions with otherwise sensible package-name components.

**Comment by snicoll** [comment]
@chrylis what specifically are you referring to? Is that the `/build` from Gradle? I can see that [gitignore now uses `**/build`](https://www.gitignore.io/api/gradle) which is not going to help you.

Let's first clarify what part of gitignore is causing the issue. I'd like to stay aligned to what gitignore does (potentially fixing it there if necessary).

**Comment by wilkinsona** [comment]
The current gitignore template is a bit odd as it ignores `build` twice:

```
/build/
…
### NetBeans ###
nbproject/private/
build/
```

**Comment by chrylis** [comment]
The one that was causing me trouble (from a freshly-generated 1.5 project) was the `build/` under NetBeans, which will match directories named `build` at any level in the hierarchy. The explicit `**/build/` is definitely The Wrong Thing.

**Comment by wilkinsona** [comment]
> The explicit `**/build/` is definitely The Wrong Thing.

I’m not sure about that. It seems useful for a multi-module project. Perhaps we should just target the single module case though? That’s what Initializr creates after all.

**Comment by chrylis** [comment]
That's what I mean--Initializr is creating a top-level source tree.
