### ISSUE TITLE
Create project at github

### ISSUE THREAD

**Issue by cemo** [spring-io/initializr#63]
It would be nice to create project directly at github instead of downloading them. This would make easier to start. It will also help to demonstrate a bug in case an error.

---

I forgot to add link of github api which is supporting to create a repository.

https://developer.github.com/v3/repos/#create

**Comment by snicoll** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.

**Comment by amihaiemil** [comment]
@snicoll I'm not a user of start.spring.io. I simply saw the website, the downloading of the ``.zip`` and thought it would be nice to have it sent to Github instead. 

I guess the user would just have to login into spring.io (Oauth2, via Github account), provide spring.io with the rights of creating a repo (+push rights) and that's about it. spring.io would then have to make a few calls to Github's API and a git push.

**Comment by snicoll** [comment]
@amihaiemil I am not asking you how you'd do it, I am asking for a motivation for such a change. See [this comment](https://github.com/spring-io/initializr/issues/63#issuecomment-375698286). Initializr is a client agnostic service so this also has to be taken into account.

**Comment by amihaiemil** [comment]
@snicoll Well, Github is the biggest platform for software development, that would be the motivation.

**Comment by meltsufin** [comment]
We're building tools with KNative where you can deploy applications to the cloud directly from GitHub, and because of the zip file download and then manually migrating it to GitHub, it creates a lot of friction. Having the ability to publish directly from Initializr to Github would make for a much better user experience.
cc/ @saturnism

**Comment by snicoll** [comment]
We discussed this request on the team call and I confirm we are not keen to implement such a feature for several reasons:

* While being able to go from a UI to a github project is nice for demoing CI/CD, we don't believe this is something our users are doing concretely. At the very least, I expect the user to actually implement something before pushing a first version
* If we push to github, it also means that we own the first commit on the repository which brings a potential compliance problem
* If we push code to Github, it is reasonable users expect to be able to chose a license for the code and we are not keen to add this extra complexity
* We believe most of our users base to be using git behind a firewall which would make this feature useless for them.

We do recognize that the developer experience with Git could be better. I've created #751 to handle that. Feel free to chime in with additional suggestions.

Thanks for the feedback!

**Comment by wilkinsona** [comment]
There are some interesting numbers around Git in the recent [JVM ecosystem report](https://snyk.io/blog/jvm-ecosystem-report-2018-tools). Git was used by 74% of respondents. Of Git users, 25% used GitHub. Of GitHub users, 52% used public GitHub and 48% used private.

Assuming that those numbers (from 10000 respondents) are indicative of the Spring Boot community, our focus on Git seems to be warranted. I also think it justifies not investing in integration with GitHub as it would only be of use to 9.6% of users.

**Comment by fangjian0423** [comment]
hi, @snicoll , @wilkinsona .

For the https://github.com/spring-io/initializr/issues/63#issuecomment-430581120 and https://github.com/spring-io/initializr/issues/63#issuecomment-430605168, I have some different thoughts:

> While being able to go from a UI to a github project is nice for demoing CI/CD, we don't believe this is something our users are doing concretely. At the very least, I expect the user to actually implement something before pushing a first version.

[Github Codespaces](https://github.com/features/codespaces) could make users develop their codes in cloud any time. So I think generate github project firstly is very userful.

> If we push to github, it also means that we own the first commit on the repository which brings a potential compliance problem

The first commit with "Initial commit" commit message(or something better) looks good to me, I don't think it will bring potential compliance problems.

Actually, when creating a github repository on github dashboard, the first commit message also is "Initial commit".

> If we push code to Github, it is reasonable users expect to be able to chose a license for the code and we are not keen to add this extra complexity.

Now [Every developer and team can now get private repositories with unlimited collaborators at no cost with GitHub Free](https://github.blog/2020-04-14-github-is-now-free-for-teams/).

For private repositories, I think they don't care which license they use.

For public repositories, we could don't choose any licenses or choose a default license.

> I also think it justifies not investing in integration with public GitHub as it would only be of use to 9.6% of users.

Now we can include github private repository users.

Finally, I hope community could reconsider this feature, thanks!

**Comment by stliu** [comment]
@wilkinsona according to Spring's state of 2021 report, it says 1/4 are using GitOps, with this pushing to github feature, it will help developers to better adopt the GitOps 

> Nearly 1 in 3 are adopting event streaming and 1 in 4 are using GitOps. The adoption rate
for event streaming aligns closely with that for Spring Kafka as mentioned above (Kafka
being an important and popular event streaming technology). We added GitOps-the use
of Git tools to automate infrastructure management-to this year's survey in recognition of
the buzz it has received over the last ear or so.

**Comment by wilkinsona** [comment]
It's usage of github.com that's important. Knowing that 25% of users are using GitOps doesn't tell us anything about that.
