### ISSUE TITLE
Remove Activiti entry

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#631]
See https://github.com/spring-io/initializr/issues/302#issuecomment-375716306

**Comment by ahmedsafwat** [comment]
@snicoll  A lot of starters are not heavily used. Why would you remove Activiti? You opened the issue and you decided to remove it. Committed the code without even a PR. 

This is not a service-upgrade by the way. I hate when a developer abuse his admin rights.

**Comment by wilkinsona** [comment]
@ahmedsafwat It’s not OK to disagree with a technical decision. It is not OK to make it personal and accuse someone of abusing their admin rights.

Every checkbox that is offered has a cost for every user of the service as it’s another choice that they need to understand and consider. When a starter is no longer justifying that cost it is removed. This upgrades the service for the vast majority of users at it’s one less choice to consider.

Making this change by PR would have made no difference. Firstly, that’s not how the core team works. Secondly, everyone on the team agreed with the decision to remove Activiti.

**Comment by ahmedsafwat** [comment]
Although nothing personal here. I have the rights for both. Thats called respect for your opens source community. Justifying the changes or at least open a PR.
