### ISSUE TITLE
Adding the same dependency twice from the search box deletes the dependency

### ISSUE THREAD

**Issue by mbhave** [spring-io/initializr#632]

**Comment by snicoll** [comment]
It actually was done on purpose to allow you to remove an entry without using the mouse. 

However, we should probably improve that. There are some nice ideas that we can take from https://www.gitignore.io/

**Comment by snicoll** [comment]
See also #463

**Comment by mbhave** [comment]
I don't think this is an issue anymore with the new UI because the search filters out dependencies that have already been added.
