### ISSUE TITLE
Revisit dependency categories

### ISSUE THREAD

**Issue by bclozel** [spring-io/initializr#634]
The current metadata for available starters lists many dependencies, each containing a list of starters.

The current list of dependency groups is not well balanced and too large (20 groups):
* Core
* Web
* Template Engines
* SQL
* NoSQL
* Messaging
* Cloud Core
* Cloud Config
* Cloud Discovery
* Cloud Routing
* Cloud Circuit Breaker
* Cloud Tracing
* Cloud Messaging
* Cloud AWS
* Cloud Contract
* Pivotal Cloud Foundry
* Azure
* Social
* I/O
* Ops

We could add a new metadata layer to regroup related dependencies under "profiles/categories". For example,  Spring Cloud related deps, Cloud platforms deps, could be regrouped under their own category/profile. Currently it's rather easy to mix those when they're not addressing the same use cases.

This could help drive improvements in the UI and new features, as the current structure is rather flat and forces the user to consider all these at the same level.

Note that a new level in the metadata is not strictly required, we could derive those categories from tags added to each dependency list.

**Comment by bclozel** [comment]
I'll try to summarize here the discussion I had today with @snicoll.

We've agreed that the current Web UI suffers from two issues:
1. the list of dependency groups is too large / not well organized, making things hard to read and navigate
2. the quick search bar has some usability issues

The second should be partially covered by #439 and by editing the metadata to avoid unnecessary word collisions between entries.

This issue is mostly about 1), and we're not sure that solving this could improve 2) in any way.

We'd like to add a new concept of dependency "category", to which groups can be assigned.

This could be help breaking big groups into smaller ones:

```
Category "Messaging":
- Group "JMS":
  - "Artemis"
  - "ActiveMQ"
- Group "Something":
  - "Other technology"
  - "Another technology"  
```

This could also help bring together technologies that are closely related but live in different groups to avoid very large lists:

```
Category "Cloud":
- Group "Config"
- Group "Routing"
- etc
```

Or bring together technologies offered by different providers, like:

```
Category "Platform":
- Group "Pivotal Cloud Foundry"
- Group "Azure"
- etc
```

At the metadata level, we could add a new "category" information that could be loosely used by clients:

```yml
dependencies:
  - name: Config
     category: Cloud
     content:
       - name: Config Client
  - name: Routing
     category: Cloud
     content:
       - name: Zuul
```

We could also introduce a hierarchical structure of dependencies like `Cloud > Config > Config Client`, but this would:
* break the current format
* would require a different way of dealing with the metadata
* would not necessarily limit the hierarchy depth - adding more levels would be confusing to users

In all cases, we should discuss that with IDE developers, as even if we choose a "non-breaking" way of doing this, we would probably move things around in the metadata, which will change the IDE user experience in the end.

**Comment by snicoll** [comment]
@bclozel I think we've done quite some progress there. Can you please close this one accordingly? Perhaps we need a separate issue for what's left? Thanks!

**Comment by bclozel** [comment]
This has been dealt with https://github.com/spring-io/start.spring.io/commit/fa647655f1362f08c083c40088a3b78a2366caa8#diff-5b750be579acca3f9e85b482abbb1f71
