### ISSUE TITLE
Create a settings.gradle file for Gradle projects

### ISSUE THREAD

**Issue by cjvogel1972** [spring-io/initializr#641]
This is related to issue #280.  It would be beneficial to create a `settings.gradle` for Gradle projects and add the `rootProject.name = '<artifact name>'` to it.  Some reasons to do this are:
* If not specified in the `settings.gradle` file, Gradle will populate the `project.name` variable with the name of the project's base directory.  For some CI servers, this is not the name that developers are expecting, whether they are random names or based on the project name with extra detail added.  Gradle will then build the artifact name based on the `project.name`, giving an artifact with an unexpected name.
* Other plugins, like `maven-publish` and `org.sonarqube` also use the `project.name` as the default value for settings.  It would be a convenience for others to have the value properly populated.

**Comment by wilkinsona** [comment]
Another reason is that this would align with Gradle's `init` task:

```
$: mkdir example
$: cd example
$: gradle init

BUILD SUCCESSFUL in 0s
2 actionable tasks: 2 executed
$: cat settings.gradle
/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user guide at https://docs.gradle.org/4.6/userguide/multi_project_builds.html
 */

rootProject.name = 'example'
```

**Comment by snicoll** [comment]
Closing in favour of PR #643
