### ISSUE TITLE
Offer Java 10 as an option when creating a project

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/initializr#646]
As of Spring Boot 2.0.1, we have JDK 10-based CI. We should consider offering Java 10 as an option for Spring Boot 2 projects.

**Comment by snicoll** [comment]
We can't really do that atm. We can have Java 10 listed and post-process the request to go back to 8 if Spring Boot < 2 is selected (as we're doing today with Java 9)

**Comment by wilkinsona** [comment]
My description's a bit ambiguous. I wasn't proposing that Java 10 only appears in the list when it's a Boot 2 project, but that we could offer it as a choice and then only honour that choice for Boot 2 projects. So, we're on the same page and should post-process back to Java 8 if the users chooses Boot 1.5 and Java 10.
