### ISSUE TITLE
Curl command builder

### ISSUE THREAD

**Issue by philwebb** [spring-io/initializr#66]
Since you can now do things like this:

```
$ curl start.spring.io/starter.tgz -d style=web -d style=security -d name=ui | tar -xzvf -
```

It might be nice if the UI dynamically build that command as you check options on the screen.

**Comment by philwebb** [comment]
Possibly also a `spring init` version as well?

**Comment by snicoll** [comment]
Can you share the exact use case?

**Comment by philwebb** [comment]
Reading http://spring.io/blog/2015/01/12/spring-and-angular-js-a-secure-single-page-application there is a section about "using curl". It struck me that unlike the `spring init` command there isn't any help for what you can do with curl. Adding to the UI would be a place to advertise the feature and help users guess the magic options.

**Comment by philwebb** [comment]
One benefit of using curl is that most users already have it. For blogs it's quite a nice way to offer a quick way to get started.

**Comment by dsyer** [comment]
More people have curl than a spring CLI. So I don't want to discourage anyone from using it (or either). A command builder on the web site would be useful IMO (for both).

**Comment by cemo** [comment]
As a feedback, I have just read blog before here and coincidentally I have created a gist for the part including curl statements. 

I found that curl is pretty useful. It does not require you install something else. In a few seconds you are getting ready.

**Comment by snicoll** [comment]
Thanks for the feedback. Check also #67

**Comment by snicoll** [comment]
`curl start.spring.io` provides a textual help with samples and you can create your project right from the IDE.
