### ISSUE TITLE
Remove Java9

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#662]
Now that Java 10 is out, Java 9 is no longer supported. I think we should remove the option so that we have 7, 8 and 10.

**Comment by bclozel** [comment]
Generally agree with this change, but just a couple of points.

Some vendors are/will support JDK9 as an LTS even if Oracle won't do it (for free). So JDK9 is not dead per se. If we do consider the "Initializr is about starting new projects so we should only consider versions that make sense for that purpose", then we should probably drop JDK7 as well.
