### ISSUE TITLE
mvn install failed on windows with Error creating assembly archive snippets

### ISSUE THREAD

**Issue by gravin** [spring-io/initializr#665]
mvnw.cmd clean package -DskipTests

 initializr-web: Failed to create assembly: Error creating assembly archive snippets: You must set at least one file.

**Comment by snicoll** [comment]
`initializer-web` provides code snippets using spring cloud contract. If you skip the tests, those aren't generated. Besides the usual joke about not skipping tests, I agree it would be nice to not fail but given that we need the output of the test to create those archives, I am not sure what to do. Silently creating an empty archive doesn't sound very good.

This fails on any OS really.

**Comment by gravin** [comment]
i run install for multiple times, and now it successfully compiled, but when i try to start a instance, it reports with errors.
C:\src\initializr>cd initializr-service
C:\src\initializr\initializr-service>..\mvnw.cmd spring-boot:run

C:\src\initializr\initializr-service>..\mvnw.cmd spring-boot:run
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for io.spring.initializr:initializr-service:[unknown-version]: Could not find artifact io.spring.initializr:initializr:pom:0.4.0.BUILD-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 6, column 10
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project io.spring.initializr:initializr-service:[unknown-version] (C:\src\initializr\initializr-service\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for io.spring.initializr:initializr-service:[unknown-version]: Could not find artifact io.spring.initializr:initializr:pom:0.4.0.BUILD-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 6, column 10 -> [Help 2]

any clues? or whats the correct process to start a instance?

**Comment by snicoll** [comment]
We don’t use the tracker for questions. Please review the readme and ask questions on StackOverflow or Gitter.

**Comment by gravin** [comment]
how about ..\mvnw.cmd spring-boot:run not work issue above by following the readme?

**Comment by gravin** [comment]
just found its because the version of initializer_service is not match with others, it is 0.4.0.SNAPSHOT, and other modules are 0.4.0.RELEAE , so cant start up. however, you with big fames company should make the steps really as simple as the doc, so that people dont need to waste time to figure it out. actually i just want to use the old version spring cloud to test the old functions and  i nearly give it up on setup this.

**Comment by snicoll** [comment]
It is really as simple as the doc and you wouldn’t be in that situation if you had followed it. 

Please review the contribution page and the code of conduct before contributing again. 

As for this issue, I already mentioned this isn’t a support forum so we’ll try to improve the build when tests are skipped.

**Comment by gravin** [comment]
ok, perhaps it really needs some patience, thanks
