### ISSUE TITLE
Explicit support for curl

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#67]
This idea came from a brainstorming with @philwebb on #66 

Since `curl` is sending a `user-agent` header we could react to that and instead of dumping the meta-data in JSON format, we could provide assistance as to how the commands can be written. 

Spring boot CLI has two kind of assistance:

* `spring help init` is a help page on the init command with a few examples and a description of the various options
* `spring init --list` contact the server and list its capabilities. This provides namely the supported dependencies (i.e. starters) and their respective ids.

Since we need to contact the server anyway, curl start.spring.io could return a text document tailored for curl with both a usage description and the capabilities of the server.

**Comment by cemo** [comment]
+1
