### ISSUE TITLE
Invalid meta-data if Sagan does not provide a default boot version #267 still unfixed?

### ISSUE THREAD

**Issue by boonyachengdu** [spring-io/initializr#680]
What should I do ? Does anyone still has this problem? How to solve it?

**Comment by boonyachengdu** [comment]
Where can I  set with My IDEA ?

**Comment by snicoll** [comment]
Can you please clarify what the problem is? I’ve checked the Sagan metadata and 2.0.3 is the default. 

I am not at a keyboard right now so I can’t check myself. Sharing the steps to reproduce would be a good start.
