### ISSUE TITLE
Upgrade to Gradle 4.8.1

### ISSUE THREAD

**Issue by pioterj** [spring-io/initializr#688]
Currently, projects are generated with Gradle 4.5.1. 

Gradle 4.8 comes with a particularly worthwhile improvement for the Spring Boot community. Thanks to the fix to https://github.com/gradle/gradle/issues/2128, stopping `bootRun` with Ctrl+C doesn't kill the [Gradle daemon](https://docs.gradle.org/current/userguide/gradle_daemon.html). This means the following builds are much faster thanks to the warm daemon.

**Comment by wilkinsona** [comment]
Boot's plugin is [already tested against 4.8](https://github.com/spring-projects/spring-boot/issues/13359) so things are good from that perspective.
