### ISSUE TITLE
Use Gradle new plugin syntax

### ISSUE THREAD

**Issue by sdeleuze** [spring-io/initializr#692]
[As of 4.10](https://github.com/gradle/gradle/issues/3902#issuecomment-400617865), Gradle new plugin syntax will support snapshot versions, enabling to use it for Spring Initializr.

This has been discussed as part of #334 since it is required for supporting Gradle Kotlin DSL in good conditions, but I think this deserve a dedicated issue since it will allow to follow Gradle best practices for the currently used Groovy DSL.

This issue could also be related to #688.

**Comment by snicoll** [comment]
That change must be 2.x specific as we don't support that version of Grade in Spring Boot 1.x

**Comment by snicoll** [comment]
This was actually fixed as part of the rewrite in #340
