### ISSUE TITLE
Release including Spring Boot 2

### ISSUE THREAD

**Issue by ArloL** [spring-io/initializr#696]
We have an internal version of the initializr running using initializr-web as a dependency. Currently we are using 0.5.0 with Spring Boot 1.x. Would it be possible to release the current version with Spring Boot 2? Thanks :)

**Comment by snicoll** [comment]
@ArloL yes, that makes sense. Thanks!

**Comment by snicoll** [comment]
`0.6.0.RELEASE` is now available on repo.spring.io/release
