### ISSUE TITLE
src/main/groovy is outdated

### ISSUE THREAD

**Issue by chrylis** [spring-io/initializr#71]
When using Groovy, Initializr puts Groovy sources in `src/main/groovy`. The `groovy-eclipse-compiler` supports putting both Groovy and Java files side-by-side in `src/main/java`, and this is the default setup for a polyglot project in STS. Using separate source directories can cause some issues when the classes refer to each other, and I suggest putting all the sources under `src/main/java`.

**Comment by snicoll** [comment]
that's legit when you are working with both languages but a bit weird if you're working on a groovy-based project, isn't it?

**Comment by chrylis** [comment]
Perhaps, but even with `@CompileStatic` none of my own projects are Groovy-only; I keep hitting spots where Java is easier or necessary (mostly relating to annotations, and in particular GROOVY-3278). GGTS has a keyboard shortcut for switching a file from Groovy to Java or back, but Maven gets confused if you put `.java` files in `src/main/groovy` (or at least it did a while back).

**Comment by snicoll** [comment]
alright, PR welcome :)

**Comment by snicoll** [comment]
What needs to be mentioned here is that it is a Maven-specific issue. Gradle actually advise to use `src/main/groovy` for Groovy-based projects. 

That means that the project layout should change according to the build system. Meh.
