### ISSUE TITLE
Add docker support while creating new project

### ISSUE THREAD

**Issue by dvsingh9** [spring-io/initializr#712]
It can be pretty good if user can add docker while creating new project with spring initilizr. I mean adding docker file and updating pom or gradle respectively for dependencies. That can make docker integration pretty simple.

**Comment by bclozel** [comment]
Thanks for the suggestion @dvsingh9, but with Initializr, we're not trying to provide opinions about the deployment model (VM, application server, PaaS, container, etc).

Also I doubt we could come up with an opinion or a standard that works with most container deployments and security considerations out there. The Spring team built [a getting started guide around that](https://spring.io/guides/gs/spring-boot-docker/), but at that point I guess it is quite outdated and you might disagree with many things in it.

**Comment by dvsingh9** [comment]
Yea, I do agree
