### ISSUE TITLE
Remove JTA entries

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#718]
We currently have three entries for JTA and the traffic on them is quite low. While supporting JTA is important for Spring Boot, I am not entirely sure we should promote its usage for new projects. 

In our effort to focus our proposition, I am wondering if we shouldn't remove them.

**Comment by rmannibucau** [comment]
Hi

Is it possible to keep at least one distributed jta entry? It is widely used and hard to replace cause of lib support.

Thanks

**Comment by wilkinsona** [comment]
The changes here don't really affect how you can use JTA with Spring Boot. You can still use the starters from Spring Boot. You just need to add the entry to your pom.xml or build.gradle manually now rather than putting a check in a box.

**Comment by rmannibucau** [comment]
Right but it makes the starter almost useless for these apps :(

**Comment by snicoll** [comment]
@rmannibucau I am sorry but I still don't get your point. Perhaps you can [join us on Gitter](https://gitter.im/spring-io/initializr) for a quick chat?

**Comment by rmannibucau** [comment]
Can do tmr but in short the point is that today when a dev got "do an amq+oracle app using spring boot", the starter was quite efficient, without jta you will end up doing it manually so the starter is no more really helping and errors are easier IMHO.

An interesting thing would be to let the starter grab the config from an url (gist?), a bit like swagger ui does, which would allow companies to have custom configs without the need of an instance. Can require more work but can be saner on the long term and compatible with your goal.

**Comment by snicoll** [comment]
Again, JTA support isn’t going anywhere. The support is not removed. We don’t offer a checkbox on the site anymore (there isn’t a checkbox for “oracle” either so I am not following the argument). Let’s continue this discussion on Gitter please.
