### ISSUE TITLE
Generate projects with enabled Kotlin Code Style "official" 

### ISSUE THREAD

**Issue by IRus** [spring-io/initializr#734]
Per https://blog.jetbrains.com/kotlin/2018/09/kotlin-1-3-rc-is-here-migrate-your-coroutines/:

> Code style
>
> It’s been a while since we introduced the official coding conventions guide, and now it’s time to move forward. Starting with Kotlin 1.3, all new projects created in IntelliJ IDEA will use the new code style settings, which comply with the coding conventions.
>
> While we recommend sharing the .idea directory via VCS, some people don’t like to do it, so we’ve introduced a Gradle property, kotlin.code.style, for setting up the project default, official or obsolete, during the IDE import. It also makes the style available to other IDEs.

So I think that would be good to have generated projects with this property defined by default to `official`.

I'm working on PR that fixes this issue.

**Comment by snicoll** [comment]
We don't have support for Kotlin 1.3 yet so I wonder if that makes sense to generate that property now. Perhaps @sdeleuze has an opinion?

**Comment by IRus** [comment]
@snicoll I think yes, because this properties has affect depending of kotlin plugin version in IDE, so project can use kotlin 1.2.x (or even 1.1 or 1.0), but this settings will have effect if IDE has kotlin plugin > 1.3.0-rc-57

**Comment by snicoll** [comment]
Thanks for the suggestion but we don't want to bring any convention to the bootstrap project and let users reformat their code the same way they are doing with other languages now. In particular, the official code style requests to use spaces and not tabs which is not what we're doing.
