### ISSUE TITLE
Expose infrastructure/support methods in ProjectGenerator

### ISSUE THREAD

**Issue by tgeens** [spring-io/initializr#744]
I'm overriding `generateProjectStructure(request, model)` to suit to our special needs, by creating a bean replacing (& subclassing) `ProjectGenerator`. 

There is a lot of infrastructure available in `ProjectGenerator` - for example temp-file-management, writeText/writeBinary to the generated project-folderstructure, ... but it's all inaccessible (private) and now I need to replicate that in my own implementation.

Would you consider a PR where these methods would either:
a) be made accessible (protected) for subclasses
b) or extracted into a separate Support-bean ?

**Comment by snicoll** [comment]
@tgeens Not at this very moment I am afraid. `ProjectGenerator` is reusable to some extent and not really "API-ready". I don't want to give the impression the current API can evolve in a backward compatible way while our intention is to provide a much better API eventually (see #340)

I'd suggest keeping the replication on your side for now. Thanks for asking in any case.
