### ISSUE TITLE
Upgrade to Maven Wrapper 0.4.2

### ISSUE THREAD

**Issue by loosebazooka** [spring-io/initializr#746]
https://github.com/spring-io/initializr/blob/master/mvnw#L188
This is a problem when someone expects to parse the output and good ol mvnw is just echo'ing out the projectDir without a care in the world.

It looks like the maven wrapper has been updated by editing the `./mvnw/wrapper/maven-wrapper.properties` directly, this unfortunately does not update the `mvnw` scripts.

I don't know how this project works or which mvnw it injects into generated projects.

To correct this problem, one option is to run
```
./mvnw -N io.takari:maven:wrapper
```
this should update all the necessary files.

**Comment by wilkinsona** [comment]
We’re still using Maven Wrapper 0.2.1. The echoing of the project’s basedir was moved behind a verbose flag in 0.2.2: https://github.com/takari/maven-wrapper/commit/719b562ff072dd3190eb87c997ab9c3092e15d92

**Comment by loosebazooka** [comment]
Ah I guess I was confused between the wrapper version and the maven dist version: https://github.com/spring-io/initializr/commit/269a26bfa9c8170a2df7c2814a09967bb1abbb9b
