### ISSUE TITLE
Upgrade Maven wrapper to Apache Maven 3.6.0

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#760]

**Comment by chtompki** [comment]
@snicoll - curious if I could both make this contribution as well as accommodating for a way to customize the maven download location in the https://github.com/spring-io/initializr/blob/master/initializr-generator/src/main/resources/project/maven/wrapper/maven-wrapper.properties file?

**Comment by snicoll** [comment]
@chtompki thanks for offering to contribute. I understand the need to be able to customize the download location but I am a bit nervous to do that officially as the wrapper may match a specific Maven version and it's a bit weird to be able to customize the location but not the version.

I am guessing you need to be able to customize that for your own fork of the service. Have you considered adding a `project/maven/wrapper/maven-wrapper.properties` in your custom service? I f that doesn't work, please join us on Gitter to chat or open a separate issue as this is not related to the upgrade per se. Thanks!

**Comment by snicoll** [comment]
Closing in favour of PR #794

**Comment by chtompki** [comment]
+1 to that. No stress.
