### ISSUE TITLE
Migrate asserts to Assertj

### ISSUE THREAD

**Issue by mbhave** [spring-io/initializr#764]
See PomAssert, GradleBuildAssert and ProjectAssert.

**Comment by rmartinus** [comment]
I can work on this as my first contribution to spring-io

**Comment by mbhave** [comment]
@rmartinus Thank you for offering to help but this issue is not quite ready for contribution yet.  We are in the process of refactoring parts of the generator and this might be affected by that. While we don't have any `ideal-for-contribution` issues in this repository at the time of writing, we do plan to add some in the future.

**Comment by rmartinus** [comment]
@mbhave not a problem at all. Looking forward to it in the future.
