### ISSUE TITLE
Projects can be generated with an empty artifactId

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#769]
You can generate a project with an empty artifactId (` `). This is not detected properly and we don't fallback to the default in such a case. We should probably trim and check the value has text. 

Other inputs are probably affected as well.

**Comment by kuldeepsidhu88** [comment]
@snicoll I would like to work on this one if nobody else is working on it.

**Comment by snicoll** [comment]
@kuldeepsidhu88 thanks for the offer! We're in a transition on the project now and we're in the process of merging a significant changes in the API. It's unusual and we should be done in a week or so. I'd suggest to start working off the new API. I'll ping here when we're done. Thanks!

**Comment by kuldeepsidhu88** [comment]
Okay. That would be fine.

**Comment by snicoll** [comment]
@kuldeepsidhu88 apologizes but I had a fix locally and forgot about our conversation.

**Comment by kuldeepsidhu88** [comment]
@snicoll no problem :)
