### ISSUE TITLE
Enhance CI pipeline

### ISSUE THREAD

**Issue by mbhave** [spring-io/initializr#771]
- [ ] Build Pull Requests
- [ ] Add slack notifications
- [ ] Add release job

**Comment by snicoll** [comment]
See also https://github.com/spring-projects/spring-boot/issues/15159 and https://github.com/spring-projects/spring-boot/issues/15120

**Comment by komsanpayboy-blip** [comment]
79623260f914b2806a275dddfdb8fff2d28fd3ff
