### ISSUE TITLE
When creating JPA starter with Spring Initializr there is no dependency for embedded DB

### ISSUE THREAD

**Issue by gtuz** [spring-io/initializr#776]
On https://start.spring.io/, if you create a simple project only with JPA module selected you will get the following pom.xml

```
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.example</groupId>
    <artifactId>demo</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>demo</name>
    <description>Demo project for Spring Boot</description>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.0.RELEASE</version>
        <relativePath/>
        <!-- lookup parent from repository -->
    </parent>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
```

There is no embedded DB dependency in test - this leads to a build issue
```
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   DemoApplicationTests.contextLoads » IllegalState Failed to load ApplicationCon...
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 29.827 s
[INFO] Finished at: 2018-11-22T20:19:42+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project demo: There are test failures.
```

Would't be better to have H2 (or anything else) by default in test scope?

**Comment by snicoll** [comment]
> Would't be better to have H2 (or anything else) by default in test scope?

Thanks for the suggestion but I don't think so. The JPA starter doesn't bring a database for very good reason and I am not keen to hide that from users when they generate a project on start.spring.io. I'd very much prefer the app to fail to let them know they have to express a choice. 

As a general rule, we stick on Spring Boot's default there to avoid differences when you get started on initializr or on your own. Adding that to tests only means the test will pass but starting the app will fail. Not really a good experience.

**Comment by fazl** [comment]
I thought the idea of spring boot was that it works out of the box. I just spent a day pulling my hair out trying to figure why the demo app generated from the initializr web page would not work 'out of the box'.. in March 2020.

Thanks to @gtuz for pointing out the missing maven dependency for hsql. (FWIW I didn't understand why the JPA guys thought that a demo generated from the initializr would be something that goes straight into production either..)
