### ISSUE TITLE
Link to https from http

### ISSUE THREAD

**Issue by coekie** [spring-io/initializr#78]
http://start.spring.io/ suggests you do `curl http://start.spring.io/install.sh | sh`. That is downloading code over plain http and then executing it. That is not ideal security-wise.
Similarly, `curl start.spring.io` also suggests you keep using http.

It would be nice if it always linked to https.

**Comment by snicoll** [comment]
Thanks! The next move is to redirect the user automatically to the https version when browsing  `http://start.spring.io` - Looking into that as well.
