### ISSUE TITLE
Use a single repo for snapshots

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#783]
Right now, if we work with a snapshot, we also add the milestone repo as the snapshot itself may rely on other projects that are in milestone phase (i.e. not available on Maven central). 

Rather than using the raw snapshot repo, we could use `libs-snapshot` that provides access to those if need to be.

(this has also the positive effect of shrinking the side of the generated pom a bit).

**Comment by snicoll** [comment]
cc @odrotbohm

**Comment by snicoll** [comment]
@wilkinsona just informed me that `libs-snapshot` also includes `release` and we want to make sure that a single repo is used for that (maven central).

**Comment by odrotbohm** [comment]
Definitely in favor of this. Thanks for filing.
