### ISSUE TITLE
Do not add snasphot repo unless absolutely necessary

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#784]
Right now we add both the milestone and snapshot repositories when a milestone is selected. The latter should not be added.

**Comment by wilkinsona** [comment]
This is complicated by Spring Cloud. At times, when a Spring Boot milestone is selected and Spring Cloud is being used, it will be necessary to use a Spring Cloud snapshot as a compatible milestone is not yet available. This is similar to #640, although it's talking about a Boot .RELEASE and a Cloud milestone.

**Comment by mbhave** [comment]
I'm a bit confused by [this](https://github.com/spring-io/initializr/issues/784#issuecomment-446528006). Maybe Andy's comment was applicable before the API rewrite? From what I can tell, the change needs to happen in `SpringBootVersionRepositoriesBuildCustomizer` which adds repositories based on the Spring Boot version. For this issue, changing `SpringBootVersionRepositoriesBuildCustomizer` to not add `spring-snapshots` if the qualifier is a milestone should be enough? Any repositories corresponding to dependencies and boms are added in `DependencyManagementBuildCustomizer` and that should stay as is.

**Comment by snicoll** [comment]
@mbhave I agree with the analysis. That's what I tried to convey in [my review of the PR](https://github.com/spring-io/initializr/pull/960#discussion_r304397236). I think we should write some tests without changing code and then see what needs to be fixed still.

**Comment by snicoll** [comment]
Closing in favour of PR #960
