### ISSUE TITLE
"Spring Boot" and "Spring" as application names make bad Java main classes

### ISSUE THREAD

**Issue by hho** [spring-io/initializr#79]
When using "Spring Boot" as the name for the application, the generated main class is `SpringBootApplication` which clashes with the imported annotation of the same name.

With "Spring" as the name, the main class becomes `SpringApplication` which clashes with the other imported class.

Either those names get banned :wink: or the Java template could use fully qualified names instead of imports in case clashes would otherwise occur.

**Comment by snicoll** [comment]
Ah, nice one! I'd go for the ban route :)

**Comment by hho** [comment]
But you don't know beforehand what conflicts might arise in the templates. That's why I discarded my first fix attempt with a filter in `ProjectRequest.generateApplicationName(String, String)`…

**Comment by snicoll** [comment]
I haven't thought too much about it but those two will be banned for sure. We can do something more smart for other corner cases, yes. The list of imports is fixed in the template.
