### ISSUE TITLE
Consider updating ext block syntax to match gradle documentation examples

### ISSUE THREAD

**Issue by mbhave** [spring-io/initializr#792]
Examples in the Gradle documentation use the following syntax for the `ext` block:

```
ext {
    foo.version = "1.2.3"
    internalVersion = "4.5.6"
}
```

We are currently using 

```
ext {
	set('foo.version', '1.2.3')
	set('internalVersion', '4.5.6')
}
```

**Comment by snicoll** [comment]
This was already considered and this only works as long as you follow a specific syntax. If you have a dot in a property, Groovy will try to crawl a relationship and obviously fail. 

What we have now is a compromise between the recommended way and the flexibility that we need (the Spring Boot bom has versions with dots and we can't change that).

There is more context in https://github.com/wilkinsona/project-generator/issues/44
