### ISSUE TITLE
war packaging causes compile error in created project

### ISSUE THREAD

**Issue by martinlippert** [spring-io/initializr#793]
I am using http://start-development.cfapps.io for testing purposes in our CI builds and came across a bug that causes the generated project to have compile errors.

Go to http://start-development.cfapps.io, select `war` as packaging type, Spring Boot 2.1.1, and the `web` module, and give it a different name than `demo`, for example `demo2` (in my case).

The generated project contains:
- `Demo2Application` (that is fine)
- `ServletInitializer` (contains the compile error)

It looks like the name of the main application doesn't get replaced correctly in the line:

`return application.sources(DemoApplication.class);`

which still contains `DemoApplication.class` where it should be `Demo2Application.class`.

Please note that this works fine with the initialize version currently deployed to https://start.spring.io.

**Comment by snicoll** [comment]
Thanks a lot for the report @martinlippert this looks like an outdated build of the new prototype. I'll double check and refresh the instance accordingly.

**Comment by snicoll** [comment]
@martinlippert the dev instance has been updated and it was a bug in the new API that's now fixed.

Superseded by https://github.com/wilkinsona/project-generator/issues/70

**Comment by martinlippert** [comment]
Awesome, thanks!!!
