### ISSUE TITLE
Do not generate configurations block for providedRuntime with war-based projects

### ISSUE THREAD

**Issue by mbhave** [spring-io/initializr#796]
We add the following section if a `providedRuntime` dependency is present.

```
configurations {
    providedRuntime
}
```

It seems like it isn't required anymore.

**Comment by wilkinsona** [comment]
I can't think of a reason to keep it. If one transpires, we can always reinstate it. +1 for getting rid of it.

**Comment by snicoll** [comment]
The dependency metadata allows you to flag a dependency as `provided` so in the case of a jar-based project that is still useful (see `ProjectGeneratorTests#gradleBuildWithCustomScope`). However we should not generate that snippet for war-based projects so I am going to change that.
