### ISSUE TITLE
Add Spring Cloud Alibaba starter

### ISSUE THREAD

**Issue by szihai** [spring-io/initializr#800]
Spring Cloud Alibaba is Spring Cloud's integration with Alibaba’s open source infrastructure, including Nacos, Sentinel and RocketMQ. Here is the release blog: https://spring.io/blog/2018/10/30/spring-cloud-for-alibaba-0-2-0-released 
And Josh Long has done a fantastic job introducing these features: http://spring.io/blog/2018/12/26/spring-tips-bootiful-alibaba
We would like to add the Spring Cloud Alibaba option amongst other integration choices in the Spring Initializr.
The following are the proposed changes:

## Spring Cloud Alibaba

* Nacos Config
   Configuration management

* Nacos Discovery
   Service discovery 

* Sentinel
   Circuit breaker 

* Sentinel Dashboard
   Circuit breaker Dashboard 

*  RocketMQ Stream
   Event-driven microservice framework based-on Apache RocketMQ

**Comment by snicoll** [comment]
@szihai thank you for reaching out. Request to add new entries to start.spring.io should be filled in the https://github.com/spring-io/start.spring.io project for which we have a process with several questions. I can't unfortunately move this as we'd prefer you create an issue following the process we've put in place.

**Comment by szihai** [comment]
Got it. Thank you.
