### ISSUE TITLE
Kotlin generator does not replace type of runApplication with specified value

### ISSUE THREAD

**Issue by alwyn** [spring-io/initializr#826]
When using start.spring.io to generate a Kotlin project with a custom artifact name,
the class name is correctly modified, but the runApplication statement has a type of DemoApplication.

For example:
`runApplication<DemoApplication>(*args)`
instead of
`runApplication<MyApplication>(*args)`

Java project generation works correctly.

**Comment by snicoll** [comment]
Ouch, thank you so much for reporting it.
