### ISSUE TITLE
Create an initializr-service sample

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#844]
Now that we have split the production site in a separate repository, there isn't an easy way to bootstrap the web ui.

I believe it would be interesting to restore this in a separate module that we would not deploy anywhere for a number of reasons:

1. It's a concrete showcase of what our docs describe (steps required to get your own instance running)
2. We could move our selenium tests there
3. Having another instance with dummy metadata showcases concretely the difference with our own opinions and start.spring.io.

**Comment by snicoll** [comment]
Rephrased to create a sample only as a showcase of how a custom instance can be built. We can keep the selenium tests as they are to avoid polluting the sample with it.

**Comment by bclozel** [comment]
Given the specifics of the web UI, I'd be in favor of:

* moving the whole Web UI and its tests to the start.spring.io project
* not provide a Web UI by default in initializr
* optionally providing infrastructure to help developers build their own; given that most of the Web UI is front-end stuff and the controller is really lightweight, I doubt we'll need any

**Comment by snicoll** [comment]
Flagging for team attention again as the proposal in #854 means we won't get any UI at all so if you want to build a sample, we'd need to build something from scratch or alternatively dropped that idea altogether.
