### ISSUE TITLE
Wrong dependency scopes for Gradle 3 builds

### ISSUE THREAD

**Issue by dashingsat** [spring-io/initializr#845]
Hey,
I generated a project with the following settings , 

Build type : Gradle, Language : Java, Spring boot version : 1.5.19 and with basic dependency of "web". 

Once I generate the jar file using ./gradlew build and then try to execute the jar using java -jar , I get the class not found exception. 

![image](https://user-images.githubusercontent.com/2674916/53178101-3a31ca00-3617-11e9-87ce-9389723ee2d5.png)

Whereas the build through Maven system , is working just fine.

**Comment by wilkinsona** [comment]
The 1.5 Gradle plugin doesn't know about the `implementation` configuration. We need to use the older `compile` configuration rather than `implementation`. For symmetry's sake, we should use `testCompile` rather than `testImplementation` as well.

**Comment by snicoll** [comment]
I broke it in #778, wrongly assuming that we'd be fine with the new scope (e.g. `implementation` rather than `compile`). It turns out our `1.5.x` plugin doesn't understand the new scopes so we need to revert that somehow.

**Comment by dashingsat** [comment]
Thanks a lot guys for such a quick turnaround.
