### ISSUE TITLE
Workaround the fact IntelliJ IDEA does not support Gradle's annotationProcessor scope

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#848]
Annotation processors have to be flagged properly to be able to move to Gradle 5 and it means we have to stop declaring annotation processors with `compileOnly` scope. 

If we do that, support in [IntelliJ IDEA will break](https://youtrack.jetbrains.com/issue/IDEA-187868) but there is a workaround we can apply here.

**Comment by snicoll** [comment]
Turns out we had this for Gradle 3 projects and we shouldn't as we don't use `annotationProcessor` there.

**Comment by snicoll** [comment]
Thank you very much, this should be available in production shortly.

**Comment by wilkinsona** [comment]
https://github.com/spring-io/initializr/commit/2647c19d5beb2f0c1b41583365191e285c7c0d7f didn't remove the logic in `GradleConfigurationBuildCustomizer` so this is still happening for Gradle 3 builds.

**Comment by snicoll** [comment]
😬

**Comment by KENNYSOFT** [comment]
Maybe now we can remove the following block:

```gradle
configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}
```
