### ISSUE TITLE
Support of multiple Gradle generations

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#849]
With the upcoming support of Gradle 5 we're in a situation where some of the infrastructure is shared with Gradle 4 and some isn't. To avoid duplicating configuration we should update `ConditionalOnGradleVersion` so that it is more flexible. 

While the version range comes to mind, I find it a bit odd for "generations" so the support of a `+` to indicate "anything after that" can be enough for now.

**Comment by wilkinsona** [comment]
How about making the `value` attribute a `String[]` so that you could do `@ConditionalOnGradleVersion({"4", "5"})` rather than having to parse a `+`?
