### ISSUE TITLE
Support of custom Gradle dependency configuration

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#850]
While the scope of a dependency should be picked up from a well-defined list, a contributors should be able to fine tune that decision based on build-system specific constraints. 

We already have that problem since Gradle 3 and Gradle 4 does not translate to the same concepts (`compile` vs. `implementation`). Being able to provide something that can resolve the scope rather than the standard enum value can be interesting.

This is required to implement https://github.com/spring-io/start.spring.io/issues/64

**Comment by snicoll** [comment]
Here is a custom instance that uses [a custom scope](https://github.com/xenit-eu/start.xenit.eu/blob/4abe80716c2345cfc21954113afc99a067efd450/src/main/java/eu/xenit/alfred/initializr/generator/buildsystem/ProjectDependency.java) for similar reasons

**Comment by tgeens** [comment]
From the discussion here https://github.com/spring-io/start.spring.io/issues/64
> This isn't an easy one unless devtools becomes a special entry that the initializr knows about and I really wouldn't like that.

A possible way to generalize that is to define a `GradleCustomConfigurationMapping` bean, where:

1. custom scopes/configurations can be defined
2. customizers can register their dependencies with a different scope

The `GradleBuildWriter` can check the `GradleCustomScopeConfigurationMapping` if a custom scope/configuration mapping has been registered for a given dependency.

Pro's:
1. no special treatment for `devtools`
2. initializr API supports custom dependency scopes
3. you can still "manage" the list of scopes/configurations

Cons:
1. logic in the `BuildWriter`

**Comment by tgeens** [comment]
As far as I can find, custom-scopes is a Gradle-only thing, correct ?
