### ISSUE TITLE
Remove default Web UI from initializr

### ISSUE THREAD

**Issue by bclozel** [spring-io/initializr#854]
Given the latest changes and [my comment in issue 844](https://github.com/spring-io/initializr/issues/844#issuecomment-469592284), I think the default Web UI should be removed from the initializr library and moved to the start.spring.io project.

We could optionally provide infrastructure to help developers build their own UI; given that most of the Web UI is front-end stuff and the controller is really lightweight, I doubt we'll need any.

One of the drivers behind this decision is that the Web UI is now too specific for the library. Pretty soon, we'll need to add a webpack based build for the Web UI and work on a more involved client application.

**Comment by snicoll** [comment]
Closing in favour of PR #844
