### ISSUE TITLE
Viewing all dependencies missing in web UI

### ISSUE THREAD

**Issue by DuncanCasteleyn** [spring-io/initializr#855]
With the new design from https://github.com/spring-io/initializr/commit/a72e6721389e21b8f37f833f22e9e8443949de1c, you can no longer get a view with all dependencies, you can only search them.

It would be nice to have the possibility to get list with all dependencies again.

**Comment by wkorando** [comment]
To add to @DuncanCasteleyn, I read the blog article and I don't agree with the reasoning. While it's especially bad that the alternative is not yet available, even if available it seems like a regression. 

It's spring _initializr_ and its most popular implementation is _start_.spring.io. It seems entirely appropriate to have the place where people go to start building an application also be the place where a person can learn _what they can build_.

**Comment by paulvi** [comment]
👍 I miss menu of older version.
And https://spring.io/blog/2019/03/05/spring-initializr-new-ui has no

At least STS has older full menu

![image](https://user-images.githubusercontent.com/1614482/53876095-05733900-4041-11e9-98d9-7ac18689ba71.png)


a72e672 is by @bclozel 
> * do not show the full list of dependencies anymore

**Comment by tiarebalbi** [comment]
I would consider having the full list again. It's really useful to see every single dependency that we have available. In case of adding new projects/integration to the dependency list will be hard for someone to find it as they are not aware.

**Comment by rafuru** [comment]
Wow agreed, I was looking for the full list because sometimes I don't remember the name of some libs

**Comment by tiarebalbi** [comment]
Let us know if this would be something that you guys would consider adding it back and I can prepare the changes to add it back.

**Comment by qq253498229** [comment]
There is no place to show all the dependencies, which makes me feel very flustered.

**Comment by MroZ11** [comment]
we need all dependencies list,please..

**Comment by CalanceHao** [comment]
+1. Show the full list of dependencies is helped.🙏
At least for my kind of newbies. I am not that familiar with the supported dependencies. Search will cost more time for quickly start a project.

**Comment by atkawa7** [comment]
+1

**Comment by songjunwang** [comment]
+1

**Comment by hekeki** [comment]
I agree with @DuncanCasteleyn, please bring back the full overview of available dependencies.

**Comment by lfmunoz** [comment]
+1 bring back the full overview of available dependencies.

**Comment by classicPintus** [comment]
+1. The list of all the available dependencies was very useful. Please bring back it

**Comment by atkawa7** [comment]
Thank you the the spring team

**Comment by bclozel** [comment]
See https://spring.io/blog/2019/03/21/spring-initializr-updates
