### ISSUE TITLE
Add Bazel Build Tool Support

### ISSUE THREAD

**Issue by 3nigm4** [spring-io/initializr#856]
We need to switch from maven to bazel to improve our build speeds and have a hard time with the spring boot parents and dependency management. If spring initializr had a template for this build tool to get one started this would help a lot to figure out how to use spring and bazel!

**Comment by jomartin-999** [comment]
Hello @3nigm4 

Thank you for the request.  At this time there is not a strong enough desire from the community for this feature to warrant an upgrade to the initializr library.  Additionally, we would require Bezel to be supported by Spring Boot, which it currently is not.  While we will decline the request, we will keep note of it and continue to monitor the needs from the community for such a feature.

Thank you.
