### ISSUE TITLE
Document how to update text capabilities defaults

### ISSUE THREAD

**Issue by ptaylor** [spring-io/initializr#857]
I want to run my own local version of the initializr and to set appropriate defaults for things like the default groupId, artifactId, version, name, description and packageName.   This is not possible yet as the InitializrProperties class does not have setters to allow them to be set in application.yml.

**Comment by snicoll** [comment]
I am not sure I understand the problem. Those are backed by the capability abstraction (`TextCapability`) and you can change it for sure.

[this is how we defined some of those defaults](https://github.com/spring-io/start.spring.io/blob/92161f33a0f2f260c6fb65872bdfd1c47fd2f31b/src/main/resources/application.yml#L1229-L1252) for start.spring.io. We could override those the same way.

**Comment by snicoll** [comment]
> Should I be setting the configuration in another way?

Yes, your example is wrong. As I've indicated, the text value must be set and that's not what you're doing. Here's an example:

```yml
initializr:
  group-id:
    value: org.acme
  artifact-id:
    value: my-app
```

Let's reuse this issue to update the documentation as [we document other pieces](https://docs.spring.io/initializr/docs/current/reference/html/#create-instance) but not text only ones

**Comment by ptaylor** [comment]
That's working for me now.   Thanks for the quick response.
