### ISSUE TITLE
Add CI job on Windows

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#865]
In the past, we've had several reports regarding failures with Windows (see #859 for the most recent). Having a CI build on Windows could help catch those sooner than later. It shouldn't probably run as often as the other ones.

**Comment by mbhave** [comment]
Reopening to fix the build.

**Comment by snicoll** [comment]
@mbhave [this comment] may be helpful I think.

**Comment by snicoll** [comment]
Setting `core.autocrlf` to `true` fixes the problem for me so we should try that on CI as well.

**Comment by mbhave** [comment]
There's no windows worker on Concourse anymore so I'm marking this as blocked till we have one.

**Comment by mbhave** [comment]
Setting `core.autocrlf` to `true` fixed the checkstyle issues. Some tests are still failing but I'm not sure if that's related to Windows.

**Comment by mbhave** [comment]
#954 seems to have fixed the windows build. Closing this issue now.
