### ISSUE TITLE
New start.spring.io web page doesn't list available dependencies 

### ISSUE THREAD

**Issue by lfmunoz** [spring-io/initializr#866]
The start.spring.io doesn't show a list of the available dependencies, it only lets you search. This is a feature regression in my opinion. 

I would always look through the list to know what I wanted. I can never remember what I need until I scroll through page and realize that I could use that dependency. Now I have to go to another website or look at old projects to remind myself of what I need.

Please add the list of available dependencies back.

**Comment by snicoll** [comment]
Duplicate of #855
