### ISSUE TITLE
Filter project contributors on the classpath

### ISSUE THREAD

**Issue by tgeens** [spring-io/initializr#870]
Is there any way to tweak/override/disable out-of-the-box `@ProjectGenerationConfiguration`s ?

They are not loaded as auto-config-beans, but with `spring.factories` (via `ProjectGenerator$CoreConfiguration`). I can't see any way to filter or customize these ?

I could try to provide my own `ProjectGenerationInvoker` bean (overriding the default bean from `InitializrAutoConfiguration`) and set up my own `ProjectGenerator`, but the interface requires me to construct a `ProjectGenerationResult` which has a package-private constructor. 

Am I missing something or is this just not supported ? Yet ?

**Comment by snicoll** [comment]
As mentioned in [the guidelines for contributing](https://github.com/spring-io/initializr/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to ask questions on StackOverflow or come chat with the community on Gitter.

Having said all that this is new API so I want to make sure we're not missing anything. You're asking several questions without explaining what you're trying to achieve. Can we take a step back and get a description of the problem rather?

**Comment by tgeens** [comment]
Thanks, I'll come and talk on gitter

**Comment by snicoll** [comment]
Let's reopen this issue to discuss the ability to tune the contributors. Right now, if you have `initializr-generator-spring` on the classpath, all contributors that it provides are loaded. There might be a need to reuse part of those conventions but not all. Alternatively, the infrastructure that's used could be of interest but not the contributors themselves. 

It would be nice if we had hook-points that support both those use cases

**Comment by mmoayyed** [comment]
> Alternatively, the infrastructure that's used could be of interest but not the contributors themselves.

This is exactly my use case at the moment. What I am trying to achieve is to reuse the APIs that are provided by this module, such as those inheriting from `MainSourceCodeCustomizer`, and yet I would want to disable or exclude `ApplicationConfigurationProjectGenerationConfiguration`. I do not need the beans that are declared by this configuration class, and today excluding such configuration classes seems not possible.

If this is something you'd like to see as a contribution, I am happy to put together a pull request with some guidance on the general approach.

**Comment by mmoayyed** [comment]
Thank you for the notes/update. I look forward to the trying the fixes whenever you get to them and if I can help with anything, please let me know.

**Comment by mmoayyed** [comment]
I am hitting this use case a lot more often now, and here's an *easy* option I thought of with low impact that could also align well with possible redesigns of this behavior in the future: perhaps contributors can be conditionally enabled via `ConditionalOnProperty` annotations, much like how actuator endpoints or health actuator contributors are turned on/off. This will allow control over each `ProjectContributor` and is not drastic enough to block or cause trouble for future enhancements. What do you think?

**Comment by mikomatic** [comment]
I have this use case too, seems related to https://github.com/spring-io/initializr/issues/887. 

I like the idea mentionned in this thread ( https://github.com/spring-io/initializr/issues/887#issuecomment-502736076 ), where there could be a separate module containing common functionality (like `BuildCustomizer` API, some "common" contributors like `MavenBuildProjectContributor` for example). That would make it easier for users to benefit from existing apis without autoconfiguring every convention.

The `initializr-generator-spring` would only autoconfigure such apis (instead of defining them + autoconfigure them).

**Comment by snicoll** [comment]
> perhaps contributors can be conditionally enabled via ConditionalOnProperty annotations, much like how actuator endpoints or health actuator contributors are turned on/off. This will allow control over each ProjectContributor and is not drastic enough to block or cause trouble for future enhancements. What do you think?

We thought of that as it would be a natural move with regards to what you can find in Spring Boot. We've ruled it out  with the current infrastructure as we don't have any way to debug this (similar to the auto-configuration report and the actuator endpoint). It is also something that can be a bit involved if you want to get this done per request or globally.

> The initializr-generator-spring would only autoconfigure such apis (instead of defining them + autoconfigure them).

This is a valid idea but I am not keen to do such a split at this level. The module with the `@ProjectGenerationConfiguration` would be a shell and the surface area is too small to warrant such work IMO. I'd like to explore how a `ProjectGenerator` can filter those upfront but I haven't had the time to look at a solution yet, sorry.

**Comment by wilkinsona** [comment]
I wonder if we could do this by allowing some control over the configuration class that's registered when creating the project generation context:

https://github.com/spring-io/initializr/blob/e97233b1077407661660925e7b5383a7ae972736/initializr-generator/src/main/java/io/spring/initializr/generator/project/ProjectGenerator.java#L107-L109

`CoreConfiguration` does nothing other than pulling in an `ImportSelector` that imports all of the `ProjectGenerationConfiguration` classes registered in `spring.factories`. Allowing `CoreConfiguration` to be replaced would allow a different import selector to be used. This different selector could use `spring.factories` and filter the registrations or it could implement a different registration mechanism entirely.

There are a few different way that this customisation could be enabled. We could make it the responsibility of the `ContextCustomizer`, we could pass something in as a new type, or we could perhaps provide a protected method that can be overridden.

**Comment by KeroZhai** [comment]
Sorry but I still don't know how to use my own sub-class of `ProjectGenerator`. Anyone can help?
