### ISSUE TITLE
Avoid writing plugin repositories section if no plugin repository is configured

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#874]
An empty app with no particular settings writes the following to `settings.gradle`:

```
pluginManagement { repositories { gradlePluginPortal() } }
```

If no repository is configured we should not write anything at all since that's the default Gradle's behaviour.  Adding a check on [this method](https://github.com/spring-io/initializr/blame/9c9cd09de550496c9837e8de595e18061fef3983/initializr-generator/src/main/java/io/spring/initializr/generator/buildsystem/gradle/GradleSettingsWriter.java#L45-L53) should be enough.

**Comment by roussi** [comment]
@snicoll should we have as result  `pluginManagement {  }`, or nothing at all ( if so we should check on `writePluginManagement` method ? )

**Comment by snicoll** [comment]
Probably. 

I've created the issue with enough references to remember where to look. That kind of stuff is managed when actually looking at the issue anyway.

**Comment by roussi** [comment]
hey @snicoll, can you please validate my pull request

**Comment by snicoll** [comment]
@roussi please don't notify all watchers of this repository that you sent a PR. We all received a notification when the PR was submitted.

**Comment by snicoll** [comment]
Closing in favour of PR #874
