### ISSUE TITLE
Add JUnit 5 Dependency

### ISSUE THREAD

**Issue by thombergs** [spring-io/initializr#876]
I like to use JUnit 5 when creating a new Spring Boot project (hoping that I'm not alone :)).

Each time I create a new project with Initializr, I repeat the steps of adding JUnit Jupiter, excluding Junit 4 from the `spring-boot-starter-test` dependency, and telling Gradle to use JUnit 5 instead of JUnit 4:

```groovy
dependencies {
	...
	testImplementation('org.junit.jupiter:junit-jupiter:5.4.0')
	testImplementation('org.springframework.boot:spring-boot-starter-test'){
		exclude group: 'org.junit', module: 'junit'
	}
}

test {
	useJUnitPlatform()
}
```

Similar with Maven.

I'm aware that ultimately JUnit 5 will probably be included in `spring-boot-starter-test` (https://github.com/spring-projects/spring-boot/issues/14736).

But since this may take a while yet, wouldn't it be an option to add JUnit 5 to the optional dependencies we can choose from when using Initializr to bootstrap a new project? If JUnit 5 is included, Initializr would then make the changes to the `build.gradle` or `pom.xml` I outlined above.

**Comment by snicoll** [comment]
Sorry but this was already requested and declined. We are following whatever defaults Spring Boot brings.
