### ISSUE TITLE
Replace the "Generate Project" implementation by a custom one

### ISSUE THREAD

**Issue by mrumpf** [spring-io/initializr#884]
The idea is to use the start.spring.io project without any modifications to execute the following steps:

1. Commit & Push the generated sources into a Git repository
1. Create a build & deployment pipeline on tools like Gitlab or Azure DevOps
1. Provision a Kubernetes cluster or use an existing one
1. Deploy the service into the K8s cluster

It would be great if I could just drop my custom "project provisioning" implementation into classpath when starting start.spring.io and by that replacing the "Download ZIP" implementation by my custom one.

In order to access the right destination, e.g. Gitlab group/project or Azure DevOps Org/project, it is probably required to pass a set of properties from a target selection UI via the start.spring.io main UI to the project provision implementation. 
Our plan is to select an Azure DevOps project/Azure subscription/AKS cluster in a central developer portal in which the microservice should be created and deployed into, then jump into the start.spring.io workflow. From there the Azure DevOps project/Azure subscription/AKS cluster context must be handed over to the "provision project" implementation to get the Git repo created in the right Azure DevOps project and created in the right AKS cluster. 

This is a very early idea and I would like to get feedback on how this could be solved with the new version of Spring Initializr. We would like to avoid modifying the start.spring.io sources to be able to easily integrate new versions into our workflow.

**Comment by snicoll** [comment]
The UI is now outside of this project and, as such, we're not heading in the direction of offering some advanced "project provisioning". What we've learned is that whatever API we would come up with would not fit with someone else's use case anyway.

I also think the initiative is a bit backwards here. If you want to implement all that, you can totally do that in your own instance. Once you've done it, we can look at the result and see if there are some extension points we can add to make that easier. Asking the API first sounds a bit odd to me.

Please give that a try in a custom fashion and feel free to create a more specific request if you think the current API goes in your way.
