### ISSUE TITLE
Make MavenWrapperContributor bean conditional

### ISSUE THREAD

**Issue by colin-shine** [spring-io/initializr#887]
Is it possible to add an `@ConditionalOnProperty` to the `MavenWrapperContributor` bean method? We don't need the wrapper, and we always end up deleting the files from generated projects.

https://github.com/spring-io/initializr/blob/357313c7bf838fd3cef0c733b3085696a638f4ed/initializr-generator-spring/src/main/java/io/spring/initializr/generator/spring/build/maven/MavenProjectGenerationConfiguration.java#L46-L49

**Comment by snicoll** [comment]
@colin-shine it's not very clear in which context you're asking this question. Is it as a user of start.spring.io or do you have your own instance based on this library?

**Comment by colin-shine** [comment]
We have our own instance based on the library.

**Comment by snicoll** [comment]
Thanks for the quick feedback. I am not keen to extend this at the moment. `initializr-generator-spring` represents our conventions and is a totally optional dependency and I'd like to keep that direction.

You can rollout your own conventions if you disagree. Or you can have a `ProjectContributor` that deletes the file if you don't want them.

Flagging for team attention to see what the rest of the team thinks.

**Comment by colin-shine** [comment]
OK, thanks @snicoll . I'll add a `ProjectContributor` as you suggest 👍

**Comment by wilkinsona** [comment]
We discussed this today and felt that having a property for something as low-level and focussed as the wrapper contributor was opening the door to having to offer a property for every individual piece of our conventions. We don't think we should do that.

As an alternative, we think their may be some merit in exploring an idea that we've also been considering for Spring Boot. We'd provide a module (something like `initializr-generator-spring-conventions`) that provides an API for using our conventions. The existing `initializr-generator-spring` module would then auto-configure those conventions. Users could then provide their own alternative that auto-configures as many or as few of those conventions as they want.

**Comment by wilkinsona** [comment]
We discussed this today and felt that having a property for something as low-level and focussed as the wrapper contributor was opening the door to having to offer a property for every individual piece of our conventions. We don't think we should do that.

As an alternative, we think their may be some merit in exploring an idea that we've also been considering for Spring Boot. We'd provide a module (something like `initializr-generator-spring-conventions`) that provides an API for using our conventions. The existing `initializr-generator-spring` module would then auto-configure those conventions. Users could then provide their own alternative that auto-configures as many or as few of those conventions as they want.

**Comment by colin-shine** [comment]
OK, thanks very much @snicoll @wilkinsona for considering my request. Keep up all the great work!

**Comment by snicoll** [comment]
This issue is superseded by #1283
