### ISSUE TITLE
Add support for fields in JavaSourceCodeWriter

### ISSUE THREAD

**Issue by colin-shine** [spring-io/initializr#889]
Would it be possible to add support for writing fields in the `JavaSourceCodeWriter`?

https://github.com/spring-io/initializr/blob/357313c7bf838fd3cef0c733b3085696a638f4ed/initializr-generator/src/main/java/io/spring/initializr/generator/language/java/JavaSourceCodeWriter.java#L106

**Comment by snicoll** [comment]
There is a PR for this already, feel free to have a look. 

Duplicates #881

**Comment by colin-shine** [comment]
Great! Apologies for not looking more closely at open PRs before raising this issue.
