### ISSUE TITLE
pom Error in Generated Demo Java App

### ISSUE THREAD

**Issue by Red-Five** [spring-io/initializr#897]
VS Code v 1.33.1
Spring Initializr v 0.4.5

Creating a demo Java app, get pom error:

Project build error: Non-resolvable parent POM for com.example:demo:0.0.1-SNAPSHOT: Failure to transfer org.springframework.boot:spring-boot-starter-parent:pom:2.2.0.M2 from https://repo.spring.io/snapshot was cached in the local repository, resolution will not be reattempted until the update interval of spring-snapshots has elapsed or updates are forced. Original error: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.2.0.M2 from/to spring-snapshots (https://repo.spring.io/snapshot): Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty and 'parent.relativePath' points at no local POMJava(0)

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.0.M2</version>
		<relativePath/> 
	</parent>

**Comment by snicoll** [comment]
> Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

That isn't related with how Spring Initializr generates a project but more how your environment connects to remote services (maven repositories). There are several threads on SO about this problem so I invite you to search there and ask a question if nothing matches your environnement.
