### ISSUE TITLE
consider migrating to gmavenplus

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#90]
As it sounds like a better option for both our own build and the groovy-based projects we generate with Maven support.

**Comment by sjyun** [comment]
how about gradle 
gradle can support groovy, java, scala, c++

i'm trying to make multiProject Gradle
https://github.com/sjyun/initializr

i have get project dependencies done
and check the ide import 

![2015-03-04_23-45-35](https://cloud.githubusercontent.com/assets/1390605/6485656/a56149d4-c2c8-11e4-86e2-4a3337e6d204.png)
![2015-03-04_23-48-07](https://cloud.githubusercontent.com/assets/1390605/6485727/013cf078-c2c9-11e4-892b-01be26593b03.png)
![2015-03-04_23-47-10](https://cloud.githubusercontent.com/assets/1390605/6485687/cfda4f12-c2c8-11e4-8252-3052680b8106.png)

**Comment by snicoll** [comment]
what about gradle? It's already supported. This issue is about Groovy projects using Maven.

**Comment by sjyun** [comment]
yes i saw groovy, maven and multi-project that got me thinking Gradle  so i just try ^^;;;
now i got your point

**Comment by sjyun** [comment]
add gmavenplus configuration in pom.xml

https://github.com/spring-io/initializr/compare/master...sjyun:gmavenplus
gmavenplus1.4 / invokeDynamic false

![2015-03-12_15-40-31](https://cloud.githubusercontent.com/assets/1390605/6613481/f61115f4-c8d0-11e4-9d05-4c15344966f0.png)

![2015-03-12_15-45-42](https://cloud.githubusercontent.com/assets/1390605/6613482/005f7b86-c8d1-11e4-830f-cff7d0b32309.png)

http://groovy.github.io/GMavenPlus/plugin-info.html

**Comment by spencergibb** [comment]
Maybe https://github.com/takari/polyglot-maven instead?

**Comment by snicoll** [comment]
what about it, @spencergibb ? We're referring to the compiler to use for Groovy code.

**Comment by spencergibb** [comment]
@snicoll yeah, disregard :-) my bad.

**Comment by mariuszs** [comment]
+1, gmavenplus is more user friendly and simpler to use

**Comment by dsyer** [comment]
-1 I think we should revert this change because gmavenplus doesn't work at all with Spring Tool Suite.

**Comment by snicoll** [comment]
Oh well. I have reverted the migration until we find a better solution.
