### ISSUE TITLE
Wrong java version on the Gradle Kotlin DSL

### ISSUE THREAD

**Issue by tiarebalbi** [spring-io/initializr#900]
Hi all, 

Just noticed on the current version that we have today in production a miss match on the Java version that we are selecting for the `Java version` option, let's say you select Java  12 the **build.gradle.kts** (#334) is coming with the Java_8 defined.

<img width="952" alt="Screen Shot 2019-05-16 at 8 05 18 AM" src="https://user-images.githubusercontent.com/103419/57865101-d51ee800-77b1-11e9-8573-19a444f2b2be.png">
<img width="658" alt="Screen Shot 2019-05-16 at 8 05 26 AM" src="https://user-images.githubusercontent.com/103419/57865102-d51ee800-77b1-11e9-9b05-3c5a594a8b16.png">

**Comment by snicoll** [comment]
This is on purpose. Kotlin generates java8 bytecode so raising the vm generation to 12 has no effect. For consistency we downgrade kotlin projects to Java8.
