### ISSUE TITLE
Kotlin DSL does not refer to bom version properly

### ISSUE THREAD

**Issue by Dontcampy** [spring-io/initializr#901]
```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
  id("org.springframework.boot") version "2.1.5.RELEASE"
  id("io.spring.dependency-management") version "0.6.0.RELEASE"
  kotlin("jvm") version "1.2.71"
  kotlin("plugin.spring") version "1.2.71"
}

group = "com.dont39"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_1_8

repositories {
  mavenCentral()
}

extra["springCloudVersion"] = "Greenwich.SR1"

dependencies {
  implementation("org.springframework.boot:spring-boot-starter-actuator")
  implementation("org.springframework.boot:spring-boot-starter-web")
  implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
  implementation("org.jetbrains.kotlin:kotlin-reflect")
  implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
  implementation("org.springframework.cloud:spring-cloud-config-server")
  implementation("org.springframework.cloud:spring-cloud-starter-config")
  implementation("org.springframework.cloud:spring-cloud-starter-consul-discovery")
  testImplementation("org.springframework.boot:spring-boot-starter-test")
}

dependencyManagement {
  imports {
    mavenBom("org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}") 
// Should use extra["springCloudVersion"]
  }
}

tasks.withType<KotlinCompile> {
  kotlinOptions {
    freeCompilerArgs = listOf("-Xjsr305=strict")
    jvmTarget = "1.8"
  }
}

```

In dependencyManagement, should use ${extra["springCloudVersion"]} instead of ${springCloudVersion}.

**Comment by driverpt** [comment]
Perhaps create a Checkbox asking if the user wants Kotlin Gradle?

**Comment by snicoll** [comment]
@driverpt please don't add suggestion to unrelated issues. This is a first round and we'll iterate based on community feedback. We have a gitter channel if you want to chat or you can engage with us on Twitter using the `@springboot` handle. Thanks.

**Comment by driverpt** [comment]
How is this off-topic?

**Comment by snicoll** [comment]
I can only assume based on the fact I don't see any link to this particular issue. We have to fix the generator and offering an option to bypass the bug is not really something we're considering. We're all at a conference this week and we'll try to get that fixed asap.

**Comment by driverpt** [comment]
It's not off-topic because Spring Initializr is generating code that is not compiling.

```
Line 45:         mavenBom("org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}")
                                                                                   ^ Unresolved reference
```

And since Gradle's Kotlin DSL is not yet recommended for Production stuff, when i choose Kotlin, it shouldn't generate by default Gradle Kotlin DSL, it should give me an option for that.

**Comment by wilkinsona** [comment]
> And since Gradle's Kotlin DSL is not yet recommended for Production stuff

That's no longer the case. Gradle declared the Kotlin DSL as being [ready for widespread use](https://blog.gradle.org/kotlin-dsl-1.0) when it reached 1.0. Furthermore, in the Gradle 5.0 release notes it was [described as being production ready](https://docs.gradle.org/5.0/release-notes.html#kotlin-dsl-1.0).

**Comment by wilkinsona** [comment]
>  by default it's generating code that is not compiling.

Thanks, but we're already aware of that. That's why this issue exists and is still open. As @snicoll has already indicated, a fix will be provided ASAP.

**Comment by snicoll** [comment]
@Dontcampy thank you very much for reporting the problem with a sample, that was very helpful.
