### ISSUE TITLE
Gradle is not configured to use JUnit Platform for Spring Boot 2.2

### ISSUE THREAD

**Issue by sbrannen** [spring-io/initializr#904]
If you create a Gradle project using Spring Boot 2.2 M3, the JUnit Platform is not configured to run tests. Consequently, if you introduce any JUnit Jupiter based tests (or any tests for a JUnit 5 `TestEngine` implementation), they will not be executed in the Gradle build.

Add the following to `build.gradle` to ensure that the JUnit Platform is used to executed tests (including JUnit Jupiter, JUnit 3, JUnit 4, etc.).

```groovy
test {
	useJUnitPlatform()
}
```

**Comment by snicoll** [comment]
That's the Groovy syntax, we also need the Kotlin DSL equivalent:

```
tasks.withType<Test> {
  useJUnitPlatform()
}
```
