### ISSUE TITLE
Provide idiomatic test setup when JUnit Jupiter is available

### ISSUE THREAD

**Issue by sbrannen** [spring-io/initializr#905]
If you create a Java project using Spring Boot 2.2 M3, the `DemoApplicationTests` test class is based on JUnit 4.

Proposal: generate the following JUnit Jupiter based test class as the example test case.

```java
package com.example.demo;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class DemoApplicationTests {

	@Test
	void contextLoads() {
	}

}
```

I have omitted `public` for the class and test method; however, those are optional omissions.

**Comment by sbrannen** [comment]
This is related to #904.

**Comment by snicoll** [comment]
Once #906 is implemented we should complement this issue to also exclude JUnit 4 from the classpath so that new projects start with JUnit 5 only.
