### ISSUE TITLE
HTTP 404 while generating  artifacts

### ISSUE THREAD

**Issue by natty4GitHub** [spring-io/initializr#911]
Folks, This is an awesome dashboard to plugin our package, artifact name and select our dependencies. Having said that, I just tried to generate the artifacts after plugging in all the required fields and i received a http 404. please let me know what's causing this problem..

<img width="1452" alt="Screen Shot 2019-05-29 at 3 35 47 PM" src="https://user-images.githubusercontent.com/9864568/58589577-d5929680-8227-11e9-8365-204de05527f8.png">

**

> 404 Not Found : Requested route ('start.spring.io') does not exist.

** Thank you, Sincerely, Natty

**Comment by wilkinsona** [comment]
There was an outage on PWS. See https://status.run.pivotal.io/incidents/tq5vmwswh9xn for details. It has been resolved and start.spring.io should be functioning normally again.
