### ISSUE TITLE
snippetsDir and the kotlin dsl

### ISSUE THREAD

**Issue by tristanlins** [spring-io/initializr#922]
I created a new project with Gradle + Kotlin + Boot 2.1.5 and these dependencies:
- Spring Boot Dev Tools
- Rest Repositories
- Spring Rest Docs
- Spring Boot Actuator

The Initializer create this `build.gradle.kts` file (shorten):

```kotlin
extra["snippetsDir"] = file("build/generated-snippets")

tasks.test {
	outputs.dir(snippetsDir)
}

tasks.asciidoctor {
	inputs.dir(snippetsDir)
	dependsOn(test)
}
```

But imo it should be:

```kotlin
val snippetsDir by extra { file("build/generated-snippets") }

tasks.test {
    outputs.dir(snippetsDir)
}

tasks.asciidoctor {
    inputs.dir(snippetsDir)
    dependsOn(tasks.test) // added tasks. prefix
}
```

**Comment by wilkinsona** [comment]
Thanks for the report.

In addition to the proposed solution, an alternative would be to leave the declaration of the `snippetsDir` property as it is and to change how it is referenced:

```
tasks.test {
	outputs.dir(project.property("snippetsDir"))
}

tasks.asciidoctor {
	inputs.dir(project.property("snippetsDir"))
	dependsOn(tasks.test)
}
```

The alternative is more closely aligned with what we currently do for bom imports, but I think I prefer the proposal from @tristanlins. If we go with that approach, we should review how we define and reference properties for bom imports as well.

**Comment by sdeleuze** [comment]
I also prefer @tristanlins proposal which seems more idiomatic Gradle Kotlin DSL code.

**Comment by AlexCzar** [comment]
I don't know how initializr composes the file, but when configuring multiple task related things I usually put it all into `tasks { }` block:
```
tasks {
	withType<KotlinCompile> {
		kotlinOptions {
			freeCompilerArgs = listOf("-Xjsr305=strict")
			jvmTarget = "1.8"
		}
	}

	test {
		outputs.dir(snippetsDir)
	}

	asciidoctor {
		inputs.dir(snippetsDir)
		dependsOn(test)
	}
}
```

**Comment by seyeon** [comment]
how about this code? It's auto-generated code by 'Intellij 2021.1'

```
tasks.test {
    project.property("snippetsDir")?.let { outputs.dir(it) }
}

tasks.asciidoctor {
    project.property("snippetsDir")?.let { inputs.dir(it) }
    dependsOn(tasks.test)
}

```

**Comment by ChrisMichl** [comment]
I changed it to this: ? -> !!

```
tasks.test {
    project.property("snippetsDir")!!.let { outputs.dir(it) }
}

tasks.asciidoctor {
    project.property("snippetsDir")!!.let { inputs.dir(it) }
    dependsOn(tasks.test)
}
```

**Comment by ChiromboKenT** [comment]
> I changed it to this: ? -> !!
> 
> ```
> tasks.test {
>     project.property("snippetsDir")!!.let { outputs.dir(it) }
> }
> 
> tasks.asciidoctor {
>     project.property("snippetsDir")!!.let { inputs.dir(it) }
>     dependsOn(tasks.test)
> }
> ```

Thanks a lot this really helped a ton!!

**Comment by Tommyten** [comment]
This still is an issue. When generating a project in the described way a gradle sync won't work unless you add the solution suggested by @ChrisMichl

**Comment by wilkinsona** [comment]
@Tommyten That is to be expected as this remains an open issue.

**Comment by massaynus** [comment]
Any plans on fixing this bug?

It's especially frustrating to a newbie just getting into SpringBoot and Kotlin !

**Comment by mhalbritter** [comment]
https://github.com/spring-io/start.spring.io/issues/581 is fixed now. If you create a project on the start.spring.io site with RESTdocs and Kotlin, it compiles out of the box.

Supporting the `extra` by delegation is not supported yet in the initialzr.
