### ISSUE TITLE
Move `RestTemplate` usage to `WebClient`

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#925]
Let's migrate our use of `RestTemplate` to the new `WebClient` API.

**Comment by mbhave** [comment]
#929 will take care of [this call](https://github.com/spring-io/initializr/blob/41e3c2c8bb3e8394bda87012d31d06dbab13f3d9/initializr-actuator/src/main/java/io/spring/initializr/actuate/stat/ProjectGenerationStatPublisher.java#L85) so we don't need to do anything there. There are a few other usages of `RestTemplate` which can be tackled as part of this issue.

@snicoll were you also thinking of migrating all the test usages? For example, [this test](https://github.com/spring-io/initializr/blob/41e3c2c8bb3e8394bda87012d31d06dbab13f3d9/initializr-web/src/test/java/io/spring/initializr/web/project/MainControllerIntegrationTests.java#L156)?

**Comment by snicoll** [comment]
> @snicoll were you also thinking of migrating all the test usages? For example, this test?

My plan is to remove usage of `RestTemplate` altogether.

**Comment by bclozel** [comment]
Is it worth it?
We don't use `RestTemplate` that much so I'm wondering if bringing new dependencies and reactive into the mix is really worth it.

**Comment by snicoll** [comment]
That's a very good point and given our current use case, it would be unreasonable to bring this over indeed. Let's close this for now, we can reconsider later.
