### ISSUE TITLE
Spring Boot 1.5 projects that use Lombok references non-existent annotationProcessor configuration

### ISSUE THREAD

**Issue by akiyu33333** [spring-io/initializr#932]
Hi, build error has occurred today.

at https://start.spring.io/
- Gradle
- Java8
- version:1.5.21,

Option is
- Spring Boot DevTools
- Lombok
- Spring Web Starter

Created a project.

Error occurred when building with IntelliJ.

```
Could not get unknown property 'annotationProcessor' for configuration ':compileOnly' of type org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.
Open File
```
I resolved when I commented out 
```
	compileOnly {
		extendsFrom annotationProcessor
	}
```

It was not possible in version 1.5.21, but it could be compiled in version 2.1.6.

Similar to this issue: 
[Workaround the fact IntelliJ IDEA does not support Gradle's annotationProcessor scope #848](https://github.com/spring-io/initializr/issues/848)

Thanks.

akiyu

**Comment by wilkinsona** [comment]
Thanks for the report. We're incorrectly applying some configuration that's for Gradle 4+ to a project that uses Gradle 3.

**Comment by akiyu33333** [comment]
Thanks wilkinsona.
I want to fix this problem and contribute to you.

**Comment by wilkinsona** [comment]
Thanks for the offer. The underlying problem was an incomplete fix for #848 which I have addressed in https://github.com/spring-io/initializr/commit/db2c867f71324bcb84e8782e1a0e5c577c9b4c85. The remaining piece is to improve the test coverage in start.spring.io. I've opened https://github.com/spring-io/start.spring.io/issues/170 to do that.

**Comment by wilkinsona** [comment]
@akiyu33333 The necessary changes have all made it to https://start.spring.io and a project that uses Boot 1.5 and Lombok should now work correctly. Please let us know if that's not the case for you and thanks again for reporting the problem.

**Comment by akiyu33333** [comment]
@wilkinsona 
Thanks for solving the problem.
Created a project at https://start.spring.io and confirmed the solution of the problem.
