### ISSUE TITLE
Review use of unzip and tar in ProjectAssert

### ISSUE THREAD

**Issue by mbhave** [spring-io/initializr#938]
#937 introduced the need for `unzip` and `tar` for testing executable files. We should see if this can be done using native Java support. ZeroTurnaround has some Zip utils that we might be able to use but it wouldn't work for tar.

**Comment by wilkinsona** [comment]
I used Commons Compress for this in the tests for Boot's Gradle Plugin. For example, [here](https://github.com/spring-projects/spring-boot/blob/0a02a3a19c0efb99e3a48b80d9c76dace84c0a45/spring-boot-project/spring-boot-tools/spring-boot-gradle-plugin/src/test/java/org/springframework/boot/gradle/plugin/ApplicationPluginActionIntegrationTests.java#L140-L156) is a test that checks that some scripts in a tar file have the expected permissions.

**Comment by mbhave** [comment]
We're going to look at changing `ProjectAssert` to work with the archive rather than the exploded project. Exploding the archive beforehand could possibly lead to differences in the project generated by the API and the project available for assertions.

**Comment by mbhave** [comment]
#951 took care of this as well.

**Comment by wilkinsona** [comment]
It didn't take care of your [suggestion above](https://github.com/spring-io/initializr/issues/938#issuecomment-509278548) though. Should we still do that?
