### ISSUE TITLE
Allow to customize Version structure and parsing

### ISSUE THREAD

**Issue by tgeens** [spring-io/initializr#945]
Use case: I'm trying to use initializr as a project-generation library in a custom (non spring-boot) project. In general this works very well, as all Spring conventions are contained in the optional module `initializr-generator-spring`.

When I try to use a 4-part version number as base platform, this blows up:

In `application.yml`:

```
  bootVersions:
  - name: My Custom Platform
    id: 6.1.0.2
```

runs into issues when you try to generate a project:

```
Could not determine version based on '6.1.0.2': version format is Minor.Major.Patch.Qualifier (e.g. 1.0.5.RELEASE)
io.spring.initializr.generator.version.InvalidVersionException: Could not determine version based on '6.1.0.2': version format is Minor.Major.Patch.Qualifier (e.g. 1.0.5.RELEASE)
    at io.spring.initializr.generator.version.VersionParser.parse(VersionParser.java:73)
    at io.spring.initializr.generator.version.Version.parse(Version.java:87)
    at io.spring.initializr.web.project.ProjectRequestToDescriptionConverter.getResolvedDependencies(ProjectRequestToDescriptionConverter.java:229)
```

It looks like `ProjectRequestToDescriptionConverter` has Spring Boot versioning conventions embedded and I see no straight forward way to override this.

@snicoll suggested on gitter:
> This is annoying it can’t handle such version right now, perhaps making `VersionParser` an interface would help

**Comment by snicoll** [comment]
I thought I had closed this one already. Given the contract of the version, I am afraid we can't tune it as the `String` is parsed by remote clients and they can't just adapt to a format they don't know. If we implemented this, it'd break all remote clients so I don't think that's a viable option for the library.

**Comment by wilkinsona** [comment]
Stephane and I just discussed this and we have some sympathy for supporting version numbers that don't match the Spring conventions. It feels aligned with all of the other Spring conventions being in an optional module. That said, supporting the generation of non-Spring projects is low priority for the core team and, given the available bandwidth, adding support for a custom version scheme isn't something that we'll be able to justify implementing.

@tgeens if this is functionality that you'd like to see then please consider opening a pull request that allows the parser to be customised. I can't promise that it'll be merged, but I can promise that we'll make time to review it and provide feedback.

**Comment by tgeens** [comment]
Thanks for the considerate response :+1:
