### ISSUE TITLE
Remove support for style

### ISSUE THREAD

**Issue by mbhave** [spring-io/initializr#959]
`dependencies` has been an alias for `style` since #50. I think we can remove `style` as it's quite confusing and doesn't look like it's documented anyway.

**Comment by snicoll** [comment]
@mbhave I think we're good to go with this one, right?

**Comment by mbhave** [comment]
I think we decided that we wanted to return a specific http status code in the response if the project request has style in it to make the removal more obvious? I haven't updated my branch with that yet.

**Comment by mbhave** [comment]
We're going to return a 400 error code if the style attribute is in the project generation request.
