### ISSUE TITLE
MultipleResourcesProjectContributor fails when argument rootResource has trailing /

### ISSUE THREAD

**Issue by tgeens** [spring-io/initializr#963]
In a custom setup, I'm using `MultipleResourcesProjectContributor` to add some static assets to the generated project. By instinct I added a trailing `/` to the `rootResource` argument.

```
new MultipleResourcesProjectContributor("classpath:grafana/").contribute()
```

**Result:**
Resources under `src/main/resources/grafana/` are picked up, but the first character of the filename is dropped. This issue goes away when you remove the trailing `/` from `rootResource` - like `"classpath:grafana"`

**Reproduction:**

```
class MultipleResourcesProjectContributorTest {

    private static final String classLocation = MultipleResourcesProjectContributorTest.class.getPackage().getName().replace('.', '/');
    private static final String classFile = MultipleResourcesProjectContributorTest.class.getSimpleName() + ".class";

    @Test
    void contribute_ok(@TempDir Path directory) throws IOException {
        String rootResource = "classpath:"+classLocation;
        MultipleResourcesProjectContributor contributor = new MultipleResourcesProjectContributor(rootResource);

        contributor.contribute(directory);

        assertThat(directory.resolve(classFile)).exists();
    }

    @Test
    void contributeWithTrailingSlash_NOT_ok(@TempDir Path directory) throws IOException {
        // Trailing slash here is the difference
        String rootResource = "classpath:"+classLocation + "/";
        MultipleResourcesProjectContributor contributor = new MultipleResourcesProjectContributor(rootResource);

        contributor.contribute(directory);

        assertThat(directory.resolve(classFile)).exists();
    }
}
```

**Possible solution:**

In `MultipleResourcesProjectContributor#contribute` the filename is calculated:
```
String filename = resource.getURI().toString().substring(root.getURI().toString().length() + 1);
```

Is there a particular reason why `resource.getFilename()` is not sufficient ?

**Comment by tgeens** [comment]
So `resource.getFilename()` doesn't work, because it's not really the _filename_ but rather the path relative to `rootResource`.

Result: When we would use `resource.getFilename()`, the tests fail because it puts for example "maven-wrapper.properties" in the project root.

**Comment by snicoll** [comment]
Thanks for the report, closing in favour of PR #964
