### ISSUE TITLE
Documentation assumes "Spring Boot" versions

### ISSUE THREAD

**Issue by snicoll** [spring-io/initializr#976]
Even if we still have a `bootVersions` field at the metadata level, most of the API has moved to the concept of `platformVersion`. We need to update the documentation to remove the fact Spring Boot is assumed.

**Comment by Ayushnita** [comment]
Hi Sir, Can I work on this issue?

**Comment by snicoll** [comment]
@Ayushnita thanks for asking. Feel free to raise a PR and we'd be happy to review it.
