### ISSUE TITLE
Add an option to configure Gradle/Maven for generating JPA Metamodel classes

### ISSUE THREAD

**Issue by behrangsa** [spring-io/initializr#985]
When the Spring Data JPA dependency is selected, give users an option to enable Metamodel generation out of the box.

**Comment by snicoll** [comment]
> give users an option

Thanks for the suggestion but that's not how the service works. Whenever we can infer something from selected dependencies or other existing settings, we're happy to tune the getting started experience. Offering an option is making the workflow of creating new projects harder (and has impact on all clients out there - IDEs namely).

I don't know if enabling metadata model generation out-of-the-box is a good idea. Flagging for team attention to see what the rest of the team thinks.

**Comment by behrangsa** [comment]
Roger that. I think enabling out of the box would be nice as it is easier
to comment out the metamodel generation sections when users don't need it
than googling around to find plugins and/or dependencies if it is not
enabled out of the box but users want to enable it.

Alternatively the relevant dependencies, plugins, and configuration could
be added to build.gradle and pom.xml but commented out.

Regards,
Behrang (sent from my mobile)

**Comment by wilkinsona** [comment]
> I don't know if enabling metadata model generation out-of-the-box is a good idea.

I don't think it's something that enough people need for it to be enabled out-of-the-box. When enabled but not needed it adds unnecessary complexity to the build.

If we want to surface metamodel generation on start.spring.io, I think the best way to do so would be via a checkbox for `org.hibernate:hibernate-jpamodelgen` dependency. When selected, we'd then add any additional configuration automatically.Looking at [Hibernate's documentation](https://docs.jboss.org/hibernate/orm/5.4/topical/html_single/metamodelgen/MetamodelGenerator.html#chapter-usage) that doesn't look like it'll be particularly easy to do. It recommends configuration the compiler to disable annotation processing and using Maven's processor plugin instead. We'd have to figure out how to deal with that for every other annotation processor that's offered.

**Comment by wilkinsona** [comment]
The team discussed this today and decided that the complexity and downsides of offering this would outweigh the benefits. Thanks anyway for the suggestion.
