### ISSUE TITLE
Disable @ProjectGenerationContext bean overriding

### ISSUE THREAD

**Issue by tgeens** [spring-io/initializr#999]
Spring Boot disabled bean overriding to prevent a bean being accidentally overridden.

Can bean overriding be disabled for the ProjectGenerationContext too ?

**Comment by snicoll** [comment]
We've decide this feature request at the team call and decided to proceed with it. We also want it to enable it by default.

**Comment by snicoll** [comment]
Thanks for the suggestion @tgeens. Disabling that led to a number of test failures showing things we should have designed differently so I've fixed that too!
